/**
 * Categorie della modalità LIIIL CRAZY.
 * Le parole non esistono in locale: vengono generate dall'IA a partire dalla categoria,
 * con vincoli di vocabolario italiano corrente e zero riferimenti cult solo statunitensi.
 */
export const CRAZY_CATEGORIES: string[] = [
  "Oggetti di casa",
  "Cucina e utensili",
  "Colazione italiana",
  "Dolci e pasticceria",
  "Frutta e verdura",
  "Bevande",
  "Cibo di strada",
  "Ristorante e trattoria",
  "Supermercato",
  "Mercato rionale",
  "Bagno e igiene",
  "Camera da letto",
  "Salotto",
  "Garage e attrezzi",
  "Giardino e piante",
  "Balcone",
  "Animali domestici",
  "Animali selvatici",
  "Animali marini",
  "Insetti",
  "Uccelli",
  "Fattoria",
  "Bosco e montagna",
  "Mare e spiaggia",
  "Meteo e fenomeni naturali",
  "Stagioni",
  "Spazio e astronomia",
  "Corpo umano",
  "Emozioni",
  "Malattie e sintomi",
  "Ospedale",
  "Farmacia",
  "Sport di squadra",
  "Sport individuali",
  "Palestra",
  "Olimpiadi",
  "Ciclismo",
  "Motori",
  "Mezzi di trasporto",
  "Aeroporto",
  "Stazione e treni",
  "Città e arredo urbano",
  "Vacanze",
  "Campeggio",
  "Hotel",
  "Monumenti e architettura",
  "Musei e arte",
  "Strumenti musicali",
  "Generi musicali",
  "Concerti e festival",
  "Cinema e set",
  "Teatro",
  "Televisione",
  "Radio e podcast",
  "Libri e lettura",
  "Fumetti",
  "Giochi da tavolo",
  "Giochi di carte",
  "Parco giochi",
  "Luna park",
  "Circo",
  "Scuola",
  "Università",
  "Ufficio",
  "Mestieri e professioni",
  "Cantiere",
  "Banca e soldi",
  "Poste e spedizioni",
  "Tribunale e legge",
  "Polizia e sicurezza",
  "Pompieri ed emergenze",
  "Tecnologia e informatica",
  "Telefono e app",
  "Internet e social",
  "Videogiochi",
  "Fotografia",
  "Elettrodomestici",
  "Abbigliamento",
  "Scarpe e accessori",
  "Gioielli",
  "Trucco e bellezza",
  "Parrucchiere",
  "Matrimonio",
  "Feste e ricorrenze",
  "Natale",
  "Carnevale",
  "Halloween all'italiana",
  "Compleanno",
  "Superstizioni",
  "Mitologia classica",
  "Fiabe e leggende",
  "Storia antica",
  "Medioevo",
  "Invenzioni",
  "Scienza e laboratorio",
  "Matematica e geometria",
  "Chimica",
  "Geografia italiana",
  "Regioni e dialetti",
  "Piazze e chiese",
  "Religione e riti",
  "Politica e istituzioni",
  "Economia e lavoro",
  "Ecologia e ambiente",
  "Rifiuti e riciclo",
  "Agricoltura",
  "Pesca",
  "Caccia al tesoro",
  "Oggetti vintage",
  "Anni Ottanta e Novanta in Italia",
  "Modi di dire",
  "Parolone difficili",
  "Concetti astratti",
  "Sogni e incubi",
  "Paure comuni",
  "Rumori e suoni",
  "Odori e profumi",
  "Sapori",
  "Materiali",
  "Forme e colori",
  "Misure e strumenti",
  "Traffico e strada",
  "Condominio e vicini",
  "Coda e attesa",
  "Burocrazia italiana",
  "Palestra della vita quotidiana",
  "Estate al mare in Italia",
  "Settimana bianca",
  "Gita scolastica",
  "Domenica in famiglia",
];
