export const ANIME: [string, string][] = [
  ["Goku", "Personaggio"],
  ["Naruto", "Personaggio"],
  ["Luffy", "Avventura"],
  ["Pikachu", "Infanzia"],
  ["Sailor Moon", "Personaggio"],
  ["Doraemon", "Infanzia"],
  ["Lupin", "Personaggio"],
  ["Totoro", "Fantasia"],
  ["Death Note", "Storia cupa"],
  ["Attack on Titan", "Storia cupa"],
  ["Evangelion", "Fantascienza"],
  ["Dragon Ball", "Titolo famoso"],
  ["One Piece", "Avventura"],
  ["Jujutsu Kaisen", "Titolo recente"],
  ["Demon Slayer", "Titolo recente"],
  ["Holly e Benji", "Nostalgia"],
  ["Ken il Guerriero", "Nostalgia"],
  ["Mila e Shiro", "Nostalgia"],
  ["Manga", "Carta"],
  ["Cosplay", "Passione"],
];
