export const ANIMALI: [string, string][] = [
  ["Leone", "Criniera regale"],
  ["Elefante", "Memoria lenta"],
  ["Pinguino", "Frac ghiacciato"],
  ["Serpente", "Freddo strisciante"],
  ["Delfino", "Sorriso marino"],
  ["Gatto", "Indipendenza morbida"],
  ["Cane", "Fedeltà"],
  ["Aquila", "Vertigine"],
  ["Squalo", "Pinna"],
  ["Formica", "Fatica minuscola"],
  ["Ape", "Ronzio dorato"],
  ["Lupo", "Branco notturno"],
  ["Tartaruga", "Lentezza corazzata"],
  ["Scimmia", "Imitazione"],
  ["Coccodrillo", "Lacrime false"],
  ["Farfalla", "Metamorfosi"],
  ["Cavallo", "Galoppo"],
  ["Gufo", "Insonnia saggia"],
  ["Riccio", "Difesa pungente"],
  ["Balena", "Immensità blu"],
];
