export const ANIMALI: [string, string][] = [
  ["Leone", "Natura"],
  ["Elefante", "Creatura"],
  ["Pinguino", "Freddo"],
  ["Serpente", "Natura"],
  ["Delfino", "Acqua"],
  ["Gatto", "Casa"],
  ["Cane", "Compagnia"],
  ["Aquila", "Cielo"],
  ["Squalo", "Acqua"],
  ["Formica", "Piccolo"],
  ["Ape", "Estate"],
  ["Lupo", "Bosco"],
  ["Tartaruga", "Lentezza"],
  ["Scimmia", "Foresta"],
  ["Coccodrillo", "Paura"],
  ["Farfalla", "Colore"],
  ["Cavallo", "Campagna"],
  ["Gufo", "Notte"],
  ["Riccio", "Giardino"],
  ["Balena", "Mare"],
];
