export const ANIME: [string, string][] = [
  ["One Piece", "Orizzonte"],
  ["Dragon Ball", "Desiderio"],
  ["Naruto", "Riconoscimento"],
  ["Death Note", "Giustizia"],
  ["Evangelion", "Angoscia"],
  ["L'Attacco dei Giganti", "Libertà"],
  ["Fullmetal Alchemist", "Equilibrio"],
  ["Sailor Moon", "Luna"],
  ["Pokémon", "Collezione"],
  ["Akira", "Esplosione"],
  ["Berserk", "Eclissi"],
  ["JoJo", "Eredità"],
  ["Hunter x Hunter", "Esame"],
  ["Bleach", "Aldilà"],
  ["My Hero Academia", "Eroismo"],
  ["Demon Slayer", "Respiro"],
  ["Jujutsu Kaisen", "Maledizione"],
  ["Chainsaw Man", "Rumore"],
  ["Spirited Away", "Bagno"],
  ["Il mio vicino Totoro", "Foresta"],
  ["Cowboy Bebop", "Jazz"],
  ["Gundam", "Metallo"],
  ["Ken il Guerriero", "Stelle"],
  ["Lupin III", "Inseguimento"],
  ["Capitan Tsubasa", "Campo"],
  ["Slam Dunk", "Canestro"],
  ["Haikyuu!!", "Volo"],
  ["Goku", "Appetito"],
  ["Luffy", "Cappello"],
  ["Naruto Uzumaki", "Volpe"],
  ["Vegeta", "Orgoglio"],
  ["Zoro", "Direzione"],
  ["Sasuke Uchiha", "Vendetta"],
  ["L", "Dolci"],
  ["Light Yagami", "Mela"],
  ["Shinji Ikari", "Sedia"],
  ["Asuka Langley", "Rosso"],
  ["Rei Ayanami", "Vetro"],
  ["Edward Elric", "Alchimia"],
  ["Roy Mustang", "Scintilla"],
  ["Spike Spiegel", "Sigaretta"],
  ["Faye Valentine", "Debito"],
  ["Vicious", "Corvo"],
  ["Guts", "Spada"],
  ["Griffith", "Ambizione"],
  ["Casca", "Memoria"],
  ["Dio Brando", "Tempo"],
  ["Jotaro Kujo", "Dito"],
  ["Joseph Joestar", "Viaggio"],
  ["Gon Freecss", "Canna"],
  ["Killua Zoldyck", "Elettricità"],
  ["Kurapika", "Catena"],
  ["Hisoka", "Gomma"],
  ["Saitama", "Pugno"],
  ["Genos", "Bullone"],
  ["Mob Psycho 100", "Percentuale"],
  ["Kamehameha", "Energia"],
  ["Rasengan", "Turbine"],
  ["Bankai", "Nome"],
  ["Domain Expansion", "Spazio"],
  ["Gear Fourth", "Vapore"],
  ["Super Saiyan", "Capelli"],
  ["Titan", "Mura"],
  ["Survey Corps", "Ali"],
  ["Colossal Titan", "Vapore"],
  ["Eren Yeager", "Cantina"],
  ["Mikasa Ackerman", "Sciarpa"],
  ["Levi Ackerman", "Pulizia"],
  ["Tanjiro Kamado", "Orecchini"],
  ["Nezuko Kamado", "Bambù"],
  ["Zenitsu Agatsuma", "Tuono"],
  ["Inosuke Hashibira", "Cinghiale"],
  ["Muzan Kibusti", "Cappello"],
  ["Ryuk", "Noia"],
  ["Misa Amano", "Quaderno"],
  ["Detective Conan", "Orologio"],
  ["Ran Mouri", "Corno"],
  ["Kaito Kid", "Bianco"],
  ["Astro Boy", "Cuore"],
  ["Doraemon", "Tasca"],
  ["Nobita", "Occhiali"],
  ["Shizuka", "Doccia"],
  ["Gian", "Microfono"],
  ["Suneo", "Ricchezza"],
  ["Urusei Yatsura", "Fulmine"],
  ["Lamù", "Corna"],
  ["Ranma 1/2", "Acqua"],
  ["Inuyasha", "Pozzo"],
  ["Kagome", "Frammento"],
  ["Sesshomaru", "Pelliccia"],
  ["Miroku", "Vuoto"],
  ["Sango", "Boomerang"],
  ["Kenshin Himura", "Cicatrice"],
  ["Yu-Gi-Oh!", "Carte"],
  ["Yugi Muto", "Puzzle"],
  ["Seto Kaiba", "Drago"],
  ["Exodia", "Pezzi"],
  ["Digimon", "Digitale"],
  ["Tai Kamiya", "Coraggio"],
  ["Agumon", "Fiamma"],
  ["Gatomon", "Anello"],
  ["Code Geass", "Obbedienza"],
  ["Lelouch Lamperouge", "Scacchi"],
  ["C.C.", "Pizza"],
  ["Suzaku Kururugi", "Lealtà"],
  ["Death Parade", "Ascensore"],
  ["Black Lagoon", "Pistola"],
  ["Revy", "Sigaro"],
  ["Hellsing", "Sangue"],
  ["Alucard", "Pistola"],
  ["Seras Victoria", "Ombra"],
  ["Trigun", "Ciambella"],
  ["Vash the Stampede", "Pace"],
  ["Wolfwood", "Croce"],
  ["Great Teacher Onizuka", "Moto"],
  ["Eikichi Onizuka", "Educazione"],
  ["Blue Exorcist", "Fiamme"],
  ["Rin Okumura", "Coda"],
  ["Sword Art Online", "Realtà"],
  ["Kirito", "Nero"],
  ["Asuna", "Cucina"],
  ["Log Horizon", "Database"],
  ["Overlord", "Scheletro"],
  ["Ainz Ooal Gown", "Trono"],
  ["Re:Zero", "Morte"],
  ["Subaru Natsuki", "Ritorno"],
  ["Rem", "Blu"],
  ["Emilia", "Ghiaccio"],
  ["Konosuba", "Inutilità"],
  ["Aqua", "Alcol"],
  ["Megumin", "Esplosione"],
  ["Darkness", "Armatura"],
  ["Shield Hero", "Scudo"],
  ["No Game No Life", "Gioco"],
  ["Shiro", "Corona"],
  ["Made in Abyss", "Profondità"],
  ["Riko", "Fischietto"],
  ["Reg", "Braccio"],
  ["Nanachi", "Odore"],
  ["Steins;Gate", "Microonde"],
  ["Rintaro Okabe", "Scienza"],
  ["Kurisu Makise", "Cerebro"],
  ["Mayuri Shiina", "Orologio"],
  ["Parasyte", "Mano"],
  ["Migi", "Libro"],
  ["Tokyo Ghoul", "Maschera"],
  ["Ken Kaneki", "Caffè"],
  ["Touka Kirishima", "Ali"],
  ["Rize Kamishiro", "Libro"],
  ["Fate/Stay Night", "Graal"],
  ["Saber", "Spada"],
  ["Archer", "Arco"],
  ["Rin Tohsaka", "Gemme"],
  ["Gilgamesh", "Tesoro"],
  ["Your Name", "Cometa"],
  ["Taki Tachibana", "Corpo"],
  ["Mitsuha Miyamizu", "Nastro"],
  ["Weathering with You", "Pioggia"],
  ["Princess Mononoke", "Lupo"],
  ["San", "Maschera"],
  ["Ashitaka", "Freccia"],
  ["Howl's Moving Castle", "Fuoco"],
  ["Sophie Hatter", "Cappello"],
  ["Calcifer", "Cuore"],
  ["Nausicaä", "Valle"],
  ["Porco Rosso", "Maiale"],
  ["Kiki", "Scopa"],
  ["Jiji", "Gatto"],
  ["Ponyo", "Pesce"],
  ["Akira Toriyama", "Matita"],
  ["Eiichiro Oda", "Paglia"],
  ["Masashi Kishimoto", "Spirale"],
  ["Hayao Miyazaki", "Nuvola"],
  ["Osamu Tezuka", "Dio"],
  ["Rumiko Takahashi", "Destino"],
  ["Naoko Takeuchi", "Cristallo"],
  ["Kentaro Miura", "Metallo"],
  ["Yoshihiro Togashi", "Dadi"],
  ["Tsundere", "Calore"],
  ["Yandere", "Coltello"],
  ["Kuudere", "Ghiaccio"],
  ["Isekai", "Camion"],
  ["Mecha", "Cabina"],
  ["Shonen", "Urlo"],
  ["Shojo", "Fiori"],
  ["Seinen", "Oscurità"],
  ["Josei", "Vita"],
  ["Amaterasu", "Fiamme"],
  ["Beelit", "Uovo"],
  ["Pokeball", "Sfera"],
  ["Millennium Puzzle", "Oro"],
  ["Z-Sword", "Roccia"],
  ["Zanpakuto", "Anima"],
  ["Konoha", "Foglia"],
  ["Grand Line", "Corrente"],
  ["Soul Society", "Passaggio"],
  ["Namek", "Verde"],
  ["Black Clover", "Trifoglio"],
  ["Asta", "Urlo"],
  ["Fire Force", "Suola"],
  ["Vinland Saga", "Coltello"],
  ["Thorfinn", "Rabbia"],
  ["Dr. Stone", "Pietra"],
  ["Senku", "Molecola"],
  ["Blue Lock", "Egoismo"],
  ["Isagi", "Puzzle"],
  ["Spy x Family", "Segreto"],
  ["Anya Forger", "Noccioline"],
  ["Loid Forger", "Bugia"],
  ["Yor Forger", "Aghi"],
  ["Your Lie in April", "Primavera"],
  ["Kosei Arima", "Spartito"],
  ["Kaori Miyazono", "Violino"],
  ["Clannad", "Famiglia"],
  ["Anohana", "Estate"],
  ["Violet Evergarden", "Lettera"],
  ["Psycho-Pass", "Colore"],
  ["Akane Tsunemori", "Sistema"],
  ["Shinya Kogami", "Fumo"],
  ["Ghost in the Shell", "Guscio"],
  ["Motoko Kusanagi", "Cavo"]
];
