export const ANIME: [string, string][] = [
  ["Goku", "Capelli dorati"],
  ["Naruto", "Ninja arancione"],
  ["Luffy", "Ciurma elastica"],
  ["Pikachu", "Scintilla gialla"],
  ["Sailor Moon", "Luna magica"],
  ["Doraemon", "Tasca futura"],
  ["Lupin", "Furto elegante"],
  ["Totoro", "Bosco gigante"],
  ["Death Note", "Quaderno fatale"],
  ["Attack on Titan", "Mura giganti"],
  ["Evangelion", "Angeli meccanici"],
  ["Dragon Ball", "Sette sfere"],
  ["One Piece", "Tesoro pirata"],
  ["Jujutsu Kaisen", "Maledizioni"],
  ["Demon Slayer", "Spada respiro"],
  ["Holly e Benji", "Campo infinito"],
  ["Ken il Guerriero", "Pugni deserto"],
  ["Mila e Shiro", "Schiacciata"],
  ["Manga", "Lettura rovesciata"],
  ["Cosplay", "Travestimento fiera"],
];
