export const CALCIO: [string, string][] = [
  ["Gol", "Rete"],
  ["Portiere", "Guanti"],
  ["Arbitro", "Fischietto"],
  ["VAR", "Monitor"],
  ["Fuorigioco", "Bandierina"],
  ["Rigore", "Dischetto"],
  ["Cartellino Rosso", "Doccia"],
  ["Cartellino Giallo", "Ammonizione"],
  ["Corner", "Bandierina"],
  ["Tribuna", "Applausi"],
  ["Curva", "Cori"],
  ["Derby", "Rivalità"],
  ["Scudetto", "Tricolore"],
  ["Champions League", "Notturna"],
  ["Europa League", "Giovedì"],
  ["Mondiale", "Estate"],
  ["Pallone d'Oro", "Cerimonia"],
  ["Panchina", "Riserva"],
  ["Allenatore", "Tuta"],
  ["Capitano", "Fascia"],
  ["Terzino", "Fascia"],
  ["Difensore", "Muro"],
  ["Centrocampista", "Regia"],
  ["Attaccante", "Fiuto"],
  ["Trequartista", "Fantasia"],
  ["Bomber", "Cinico"],
  ["Numero Dieci", "Talento"],
  ["Falco", "Guardialinee"],
  ["Tifoso", "Sciarpa"],
  ["Ultras", "Striscione"],
  ["Stadio", "Prato"],
  ["San Siro", "Meneghina"],
  ["Olimpico", "Colosseo"],
  ["Maracanã", "Samba"],
  ["Wembley", "Arco"],
  ["Camp Nou", "Catalana"],
  ["Bernabéu", "Bianca"],
  ["Allianz Arena", "Mole"],
  ["Serie A", "Domenica"],
  ["Serie B", "Cadetta"],
  ["Coppa Italia", "Mercoledì"],
  ["Nazionale", "Azzurri"],
  ["Panenka", "Cucchiaio"],
  ["Rovesciata", "Acrobazia"],
  ["Colpo di Testa", "Salto"],
  ["Tunnel", "Umiliazione"],
  ["Dribbling", "Finta"],
  ["Cross", "Traversone"],
  ["Assist", "Servito"],
  ["Autogol", "Sfortuna"],
  ["Traversa", "Legno"],
  ["Palo", "Legno"],
  ["Tacco", "Elegante"],
  ["Sombrero", "Beffa"],
  ["Contropiede", "Velocità"],
  ["Catenaccio", "Difesa"],
  ["Tiki-Taka", "Palleggio"],
  ["Tridente", "Attacco"],
  ["Modulo", "Lavagna"],
  ["Formazione", "Undici"],
  ["Mercato", "Trattativa"],
  ["Prestito", "Provvisorio"],
  ["Svincolato", "Libero"],
  ["Clausola Rescissoria", "Cifra"],
  ["Procuratore", "Commissione"],
  ["Ingaggio", "Stipendio"],
  ["Ritiro", "Silenzio"],
  ["Spogliatoio", "Confidenze"],
  ["Massaggiatore", "Lettino"],
  ["Fisioterapista", "Recupero"],
  ["Infortunio", "Sfortuna"],
  ["Crociato", "Ginocchio"],
  ["Squalifica", "Punizione"],
  ["Sostituzione", "Cambio"],
  ["Recupero", "Extra"],
  ["Tempi Supplementari", "Stanchezza"],
  ["Rigori", "Lotteria"],
  ["Dischetto", "Undici Metri"],
  ["Barriera", "Muro Umano"],
  ["Punizione", "Precisione"],
  ["Calcio d'Angolo", "Bandierina"],
  ["Rimessa Laterale", "Mani"],
  ["Retropassaggio", "Sicurezza"],
  ["Marcatura", "Ombra"],
  ["Pressing", "Fiato"],
  ["Fuoriclasse", "Genio"],
  ["Vecchia Signora", "Bianconera"],
  ["Diavolo", "Rossonero"],
  ["Nerazzurri", "Milano"],
  ["Giallorossi", "Capitale"],
  ["Biancocelesti", "Aquila"],
  ["Partenopei", "Vulcano"],
  ["Bianconeri", "Torino"],
  ["Blucerchiati", "Genova"],
  ["Viola", "Firenze"],
  ["Rossoblù", "Emilia"],
  ["Ct", "Selezionatore"],
  ["Osservatore", "Taccuino"],
  ["Vivaio", "Cantera"],
  ["Primavera", "Giovani"],
  ["Baby Prodigio", "Promessa"],
  ["Bandiera", "Fedeltà"],
  ["Veterano", "Esperienza"],
  ["Esordiente", "Debutto"],
  ["Numero Nove", "Centravanti"],
  ["Falso Nueve", "Inganno"],
  ["Ala", "Fascia"],
  ["Libero", "Ultimo"],
  ["Stopper", "Duro"],
  ["Regista", "Cervello"],
  ["Metronomo", "Ritmo"],
  ["Incursore", "Sorpresa"],
  ["Goleador", "Cecchino"],
  ["Cecchino", "Precisione"],
  ["Fantacalcio", "Asta"],
  ["Formazione Fantacalcio", "Schema"],
  ["Bonus", "Premio"],
  ["Malus", "Penalità"],
  ["Capocannoniere", "Classifica"],
  ["Classifica Marcatori", "Podio"],
  ["Scommessa", "Rischio"],
  ["Pronostico", "Indovinello"],
  ["Schedina", "Foglio"],
  ["Telecronista", "Voce"],
  ["Commentatore", "Microfono"],
  ["Moviola", "Replay"],
  ["Highlights", "Riassunto"],
  ["Diretta", "Live"],
  ["Radiocronaca", "Orecchio"],
  ["Bar Sport", "Discussione"],
  ["Rissa da Bar", "Accanito"],
  ["Aperitivo Post Partita", "Chiacchiere"],
  ["Sciarpa", "Colori"],
  ["Coreografia", "Colpo d'Occhio"],
  ["Fumogeno", "Curva"],
  ["Petardo", "Botto"],
  ["Trasferta", "Viaggio"],
  ["Amichevole", "Test"],
  ["Ritiro Estivo", "Montagna"],
  ["Preparazione Atletica", "Fatica"],
  ["Scarpini", "Tacchetti"],
  ["Pallone", "Sfera"],
  ["Rete", "Maglie"],
  ["Dischetto del Rigore", "Tensione"],
  ["Cerchio di Centrocampo", "Simmetria"],
  ["Area di Rigore", "Confine"],
  ["Area di Porta", "Piccola"],
  ["Bandierine d'Angolo", "Colore"],
  ["Panchina Lunga", "Alternative"],
  ["Rosa", "Elenco"],
  ["Cartellino Verde", "Novità"],
  ["Bomber di Provincia", "Sorpresa"],
  ["Sorpresa del Campionato", "Cenerentola"],
  ["Retrocessione", "Lacrime"],
  ["Promozione", "Festa"],
  ["Playoff", "Tensione"],
  ["Playout", "Ansia"],
  ["Spareggio", "Nervi"],
  ["Girone", "Tabella"],
  ["Calendario", "Date"],
  ["Turno Infrasettimanale", "Fatica"],
  ["Big Match", "Attesa"],
  ["Scontro Diretto", "Verità"],
  ["Bomber Storico", "Leggenda"],
  ["Idolo", "Poster"],
  ["Beniamino", "Coro"],
  ["Fischi", "Contestazione"],
  ["Applausi", "Standing Ovation"],
  ["Onda", "Curva"],
  ["Bandiera Club", "Simbolo"],
  ["Inno", "Coro"],
  ["Terzo Tempo", "Sportività"],
  ["Fair Play", "Rispetto"],
  ["Cartellino Blu", "Ipotesi"],
  ["Goal Line Technology", "Sensore"],
  ["Chip Nel Pallone", "Tecnologia"],
  ["Tabellone", "Punteggio"],
  ["Cronometro", "Tempo"],
  ["Sirena", "Fine"],
  ["Triplice Fischio", "Fine Gara"],
  ["Primo Tempo", "Inizio"],
  ["Secondo Tempo", "Ripresa"],
  ["Intervallo", "Pausa"],
  ["Riscaldamento", "Stretching"],
  ["Numero di Maglia", "Identità"],
  ["Fascia da Capitano", "Onore"],
  ["Coppa", "Trofeo"],
  ["Medaglia", "Ricordo"],
  ["Podio", "Gradini"],
  ["Festeggiamenti", "Champagne"],
  ["Pullman Scoperto", "Corteo"],
  ["Parata", "Folla"],
  ["Presidente", "Palco"],
  ["Direttore Sportivo", "Ufficio"],
  ["Settore Giovanile", "Futuro"],
  ["Osservatorio Scout", "Binocolo"],
  ["Talent Scout", "Fiuto"],
  ["Casting Portieri", "Selezione"],
  ["Uno Contro Uno", "Duello"],
  ["Testa a Testa", "Sfida"],
  ["Marcamento a Uomo", "Ombra"],
  ["Zona", "Spazio"],
  ["Fuorigioco Tattico", "Trappola"],
  ["Pressing Alto", "Aggressività"],
  ["Ripartenza", "Lampo"],
  ["Palleggio", "Possesso"],
  ["Possesso Palla", "Controllo"],
  ["Tiro da Fuori", "Azzardo"],
  ["Conclusione", "Tentativo"],
  ["Deviazione", "Rimbalzo"],
  ["Super Parata", "Riflessi"],
  ["Uscita Bassa", "Tuffo"],
  ["Presa Alta", "Volo"],
  ["Respinta", "Rimbalzo"],
  ["Recupero Palla", "Furto"],
  ["Contrasto", "Scontro"],
  ["Fallo", "Sanzione"],
  ["Simulazione", "Teatro"],
  ["Proteste", "Discussione"],
  ["Espulsione", "Anticipo"],
  ["Ammonizione", "Avviso"],
];
