export const CALCIO: [string, string][] = [
  ["Gol", "Azione calcio"],
  ["Portiere", "Ruolo calcio"],
  ["Arbitro", "Ufficio di gara"],
  ["VAR", "Tecnologia calcio"],
  ["Fuorigioco", "Regola calcio"],
  ["Rigore", "Tiro calcio"],
  ["Cartellino Rosso", "Sanzione arbitrale"],
  ["Cartellino Giallo", "Sanzione arbitrale"],
  ["Corner", "Calcio piazzato"],
  ["Tribuna", "Settore stadio"],
  ["Curva", "Settore stadio"],
  ["Derby", "Tipo di partita"],
  ["Scudetto", "Trofeo calcio italiano"],
  ["Champions League", "Coppa europea"],
  ["Europa League", "Coppa europea"],
  ["Mondiale", "Torneo nazionali"],
  ["Pallone d'Oro", "Premio calcistico"],
  ["Panchina", "Ruolo di squadra"],
  ["Allenatore", "Ruolo tecnico"],
  ["Capitano", "Ruolo di squadra"],
  ["Terzino", "Ruolo difensivo"],
  ["Difensore", "Ruolo calcio"],
  ["Centrocampista", "Ruolo calcio"],
  ["Attaccante", "Ruolo calcio"],
  ["Trequartista", "Ruolo calcio"],
  ["Bomber", "Tipo attaccante"],
  ["Numero Dieci", "Maglia calcio"],
  ["Falco", "Assistente arbitro"],
  ["Tifoso", "Sostenitore squadra"],
  ["Ultras", "Gruppo di tifosi"],
  ["Stadio", "Impianto sportivo"],
  ["San Siro", "Stadio italiano"],
  ["Olimpico", "Stadio italiano"],
  ["Maracanã", "Stadio brasiliano"],
  ["Wembley", "Stadio inglese"],
  ["Camp Nou", "Stadio spagnolo"],
  ["Bernabéu", "Stadio spagnolo"],
  ["Allianz Arena", "Stadio tedesco"],
  ["Serie A", "Campionato calcio"],
  ["Serie B", "Campionato calcio"],
  ["Coppa Italia", "Torneo nazionale"],
  ["Nazionale", "Squadra di stato"],
  ["Panenka", "Tipo di rigore"],
  ["Rovesciata", "Gesto tecnico"],
  ["Colpo di Testa", "Gesto tecnico"],
  ["Tunnel", "Gesto tecnico"],
  ["Dribbling", "Gesto tecnico"],
  ["Cross", "Passaggio calcio"],
  ["Assist", "Passaggio decisivo"],
  ["Autogol", "Errore calcio"],
  ["Traversa", "Parte della porta"],
  ["Palo", "Parte della porta"],
  ["Tacco", "Gesto tecnico"],
  ["Sombrero", "Gesto tecnico"],
  ["Contropiede", "Tattica calcio"],
  ["Catenaccio", "Tattica difensiva"],
  ["Tiki-Taka", "Stile di gioco"],
  ["Tridente", "Schema d'attacco"],
  ["Modulo", "Schema tattico"],
  ["Formazione", "Schieramento squadra"],
  ["Mercato", "Trattativa calcio"],
  ["Prestito", "Formula di mercato"],
  ["Svincolato", "Status giocatore"],
  ["Clausola Rescissoria", "Termine contrattuale"],
  ["Procuratore", "Figura del mercato"],
  ["Ingaggio", "Termine contrattuale"],
  ["Ritiro", "Preparazione squadra"],
  ["Spogliatoio", "Ambiente stadio"],
  ["Massaggiatore", "Staff squadra"],
  ["Fisioterapista", "Staff squadra"],
  ["Infortunio", "Problema fisico"],
  ["Crociato", "Legamento ginocchio"],
  ["Squalifica", "Sanzione sportiva"],
  ["Sostituzione", "Cambio calcio"],
  ["Recupero", "Minuti extra"],
  ["Tempi Supplementari", "Prolungamento partita"],
  ["Rigori", "Serie decisiva"],
  ["Dischetto", "Punto della porta"],
  ["Barriera", "Schieramento su punizione"],
  ["Punizione", "Calcio piazzato"],
  ["Calcio d'Angolo", "Calcio piazzato"],
  ["Rimessa Laterale", "Ripresa del gioco"],
  ["Retropassaggio", "Passaggio al portiere"],
  ["Marcatura", "Copertura difensiva"],
  ["Pressing", "Tattica offensiva"],
  ["Fuoriclasse", "Giocatore talentuoso"],
  ["Vecchia Signora", "Soprannome squadra"],
  ["Diavolo", "Soprannome squadra"],
  ["Nerazzurri", "Colori squadra"],
  ["Giallorossi", "Colori squadra"],
  ["Biancocelesti", "Colori squadra"],
  ["Partenopei", "Soprannome squadra"],
  ["Bianconeri", "Colori squadra"],
  ["Blucerchiati", "Colori squadra"],
  ["Viola", "Soprannome squadra"],
  ["Rossoblù", "Colori squadra"],
  ["Ct", "Guida della nazionale"],
  ["Osservatore", "Figura del mercato"],
  ["Vivaio", "Settore giovanile"],
  ["Primavera", "Categoria giovanile"],
  ["Baby Prodigio", "Giovane promessa"],
  ["Bandiera", "Simbolo di squadra"],
  ["Veterano", "Giocatore esperto"],
  ["Esordiente", "Primo giocatore in campo"],
  ["Numero Nove", "Maglia calcio"],
  ["Falso Nueve", "Ruolo tattico"],
  ["Ala", "Ruolo calcio"],
  ["Libero", "Ruolo difensivo"],
  ["Stopper", "Ruolo difensivo"],
  ["Regista", "Ruolo calcio"],
  ["Metronomo", "Tipo di centrocampista"],
  ["Incursore", "Tipo di centrocampista"],
  ["Goleador", "Tipo attaccante"],
  ["Cecchino", "Tipo attaccante"],
  ["Fantacalcio", "Gioco da tifosi"],
  ["Formazione Fantacalcio", "Gioco da tifosi"],
  ["Bonus", "Punteggio fantacalcio"],
  ["Malus", "Punteggio fantacalcio"],
  ["Capocannoniere", "Titolo di classifica"],
  ["Classifica Marcatori", "Graduatoria calcio"],
  ["Scommessa", "Gioco d'azzardo"],
  ["Pronostico", "Previsione risultato"],
  ["Schedina", "Modulo scommesse"],
  ["Telecronista", "Professione tv"],
  ["Commentatore", "Professione tv"],
  ["Moviola", "Analisi tv"],
  ["Highlights", "Sintesi tv"],
  ["Diretta", "Trasmissione tv"],
  ["Radiocronaca", "Trasmissione radio"],
  ["Bar Sport", "Luogo di tifo"],
  ["Rissa da Bar", "Discussione da tifosi"],
  ["Aperitivo Post Partita", "Tradizione tifosi"],
  ["Sciarpa", "Oggetto da tifoso"],
  ["Coreografia", "Spettacolo da stadio"],
  ["Fumogeno", "Oggetto da stadio"],
  ["Petardo", "Oggetto rumoroso stadio"],
  ["Trasferta", "Partita fuori casa"],
  ["Amichevole", "Partita di prova"],
  ["Ritiro Estivo", "Preparazione squadra"],
  ["Preparazione Atletica", "Allenamento fisico"],
  ["Scarpini", "Calzatura calcio"],
  ["Pallone", "Attrezzo calcio"],
  ["Rete", "Parte della porta"],
  ["Dischetto del Rigore", "Punto della porta"],
  ["Cerchio di Centrocampo", "Zona del campo"],
  ["Area di Rigore", "Zona del campo"],
  ["Area di Porta", "Zona del campo"],
  ["Bandierine d'Angolo", "Segnale di campo"],
  ["Panchina Lunga", "Rosa numerosa"],
  ["Rosa", "Elenco giocatori"],
  ["Cartellino Verde", "Sanzione sperimentale"],
  ["Bomber di Provincia", "Attaccante sorprendente"],
  ["Sorpresa del Campionato", "Squadra rivelazione"],
  ["Retrocessione", "Esito negativo campionato"],
  ["Promozione", "Esito positivo campionato"],
  ["Playoff", "Fase finale campionato"],
  ["Playout", "Spareggio salvezza"],
  ["Spareggio", "Partita decisiva"],
  ["Girone", "Fase di torneo"],
  ["Calendario", "Programma partite"],
  ["Turno Infrasettimanale", "Giornata di campionato"],
  ["Big Match", "Partita importante"],
  ["Scontro Diretto", "Partita decisiva"],
  ["Bomber Storico", "Attaccante leggendario"],
  ["Idolo", "Beniamino tifosi"],
  ["Beniamino", "Preferito dei tifosi"],
  ["Fischi", "Reazione dei tifosi"],
  ["Applausi", "Reazione dei tifosi"],
  ["Onda", "Coreografia da stadio"],
  ["Bandiera Club", "Simbolo di squadra"],
  ["Inno", "Canto da stadio"],
  ["Terzo Tempo", "Tradizione rugbistica"],
  ["Fair Play", "Valore sportivo"],
  ["Cartellino Blu", "Sanzione ipotetica"],
  ["Goal Line Technology", "Tecnologia arbitrale"],
  ["Chip Nel Pallone", "Tecnologia calcio"],
  ["Tabellone", "Display dello stadio"],
  ["Cronometro", "Strumento di gara"],
  ["Sirena", "Segnale di fine gara"],
  ["Triplice Fischio", "Segnale arbitrale"],
  ["Primo Tempo", "Frazione di gara"],
  ["Secondo Tempo", "Frazione di gara"],
  ["Intervallo", "Pausa di gara"],
  ["Riscaldamento", "Preparazione pre-partita"],
  ["Numero di Maglia", "Identificativo giocatore"],
  ["Fascia da Capitano", "Simbolo di ruolo"],
  ["Coppa", "Trofeo sportivo"],
  ["Medaglia", "Premio sportivo"],
  ["Podio", "Cerimonia sportiva"],
  ["Festeggiamenti", "Celebrazione vittoria"],
  ["Pullman Scoperto", "Festa cittadina"],
  ["Parata", "Corteo cittadino"],
  ["Presidente", "Dirigente di club"],
  ["Direttore Sportivo", "Dirigente di club"],
  ["Settore Giovanile", "Categoria vivaio"],
  ["Osservatorio Scout", "Attività di scouting"],
  ["Talent Scout", "Cacciatore di talenti"],
  ["Casting Portieri", "Selezione ruolo specifico"],
  ["Uno Contro Uno", "Duello di gioco"],
  ["Testa a Testa", "Sfida diretta"],
  ["Marcamento a Uomo", "Tattica difensiva"],
  ["Zona", "Tattica difensiva"],
  ["Fuorigioco Tattico", "Trappola difensiva"],
  ["Pressing Alto", "Tattica offensiva"],
  ["Ripartenza", "Azione veloce"],
  ["Palleggio", "Tecnica di possesso"],
  ["Possesso Palla", "Stile di gioco"],
  ["Tiro da Fuori", "Conclusione a rete"],
  ["Conclusione", "Tiro in porta"],
  ["Deviazione", "Effetto sul tiro"],
  ["Super Parata", "Intervento del portiere"],
  ["Uscita Bassa", "Intervento del portiere"],
  ["Presa Alta", "Intervento del portiere"],
  ["Respinta", "Intervento del portiere"],
  ["Recupero Palla", "Azione difensiva"],
  ["Contrasto", "Duello di gioco"],
  ["Fallo", "Infrazione di gioco"],
  ["Simulazione", "Comportamento scorretto"],
  ["Proteste", "Reazione dei giocatori"],
  ["Espulsione", "Sanzione arbitrale"],
  ["Ammonizione", "Sanzione arbitrale"],
];
