export const CALCIO: [string, string][] = [
  ["Rigore", "Undici metri"],
  ["Fuorigioco", "Bandierina alzata"],
  ["Cartellino rosso", "Doccia anticipata"],
  ["Portiere", "Guanti soli"],
  ["Traversa", "Legno amaro"],
  ["Derby", "Città divisa"],
  ["Ultras", "Curva rumorosa"],
  ["Fantacalcio", "Asta autunnale"],
  ["Coppa", "Argento alzato"],
  ["Arbitro", "Fischietto odiato"],
  ["Rovesciata", "Acrobazia"],
  ["Mondiali", "Ogni quattro anni"],
  ["Panchina", "Attesa"],
  ["Tifoso", "Sciarpa"],
  ["Scudetto", "Cucito sul petto"],
  ["Var", "Schermo bordocampo"],
  ["Autogol", "Errore beffardo"],
  ["Calcio d'angolo", "Bandierina"],
  ["Maradona", "Mano celebre"],
  ["Stadio", "Boato"],
];
