export const CHARLIE_KIRK: [string, string][] = [
  // Meme e fisico
  ["Faccia Piccola", "Proporzione"],
  ["Testa a Forma di Pollice", "Comparazione online"],
  ["Fronte Generosa", "Cinque dita"],
  ["Mascella Assente", "Mewing"],
  ["Linea dei Capelli", "Ritirata"],
  ["Collo Invisibile", "Foto ritagliata"],
  ["Sorriso da Campagna", "Denti"],
  ["Giacca Blu Elettorale", "Bottone"],
  ["Cravatta a Righe", "Nodo"],
  ["Cappellino Rosso", "Visiera"],

  // Meme iconici
  ["Pannolino", "Scandalo universitario"],
  ["Diaper Gate", "Scandalo universitario, meme"],
  ["Toilet Paper USA", "Parodia online"],
  ["Microfono Aperto", "Tour campus"],
  ["Gazebo", "Dibattito all'aperto"],
  ["Fila di Studenti", "Pazienza"],
  ["Domanda Scomoda", "Sudore"],
  ["Applauso Scrosciante", "Palmo"],
  ["Fischio dal Pubblico", "Labbra"],
  ["Chat del Live", "Scorrimento"],

  // Organizzazione e brand
  ["Turning Point USA", "Organizzazione"],
  ["TPUSA", "Acronimo"],
  ["Turning Point Action", "Braccio politico"],
  ["Students for Trump", "Gruppo alleato"],
  ["Campus Tour", "Ateneo"],
  ["Young Republicans", "Base"],
  ["Conservative Student", "Target"],

  // Idee politiche
  ["Capitalismo", "Sistema difeso"],
  ["Socialismo", "Spettro rosso"],
  ["Venezuela", "Argomento socialismo"],
  ["Big Government", "Stato troppo grande"],
  ["Tassazione", "Furto per lui"],
  ["Secondo Emendamento", "Diritto armato"],
  ["Costituzione", "Carta sacra"],
  ["America First", "Slogan"],
  ["Build the Wall", "Muro"],
  ["Immigrazione", "Tema caldo"],
  ["Pro-Life", "Posizione aborto"],
  ["Valori Famiglia", "Istituto difeso"],
  ["Libertà Religiosa", "Primo emendamento"],
  ["Free Speech", "Libertà parola"],
  ["Safe Space", "Spazio odiato"],
  ["Snowflake", "Insulto generazionale"],
  ["Liberal Tears", "Bere"],
  ["Fake News", "Media bugiardi"],
  ["Mainstream Media", "Nemico"],
  ["Deep State", "Teoria"],

  // Trump e alleati
  ["MAGA", "Cappello rosso"],
  ["Trump", "Presidente amato"],
  ["Rally", "Comizio"],
  ["Stop the Steal", "Slogan elezioni"],
  ["Truth Social", "Piattaforma politica"],
  ["Fox News", "Canale preferito"],
  ["Tucker Carlson", "Collega televisivo"],
  ["Ben Shapiro", "Amico veloce"],
  ["Candace Owens", "Amica attivista"],
  ["Steven Crowder", "Amico comico"],
  ["PragerU", "Alleato video"],
  ["Daily Wire", "Alleato media"],
  ["CPAC", "Conferenza conservatrice"],

  // Internet e gergo
  ["Twitter", "Social preferito"],
  ["X", "Piattaforma social"],
  ["Elon Musk", "Miliardario amico"],
  ["Tweet Virale", "Diffusione"],
  ["Screenshot", "Ritaglio"],
  ["Meme Template", "Cornice"],
  ["Hashtag", "Cancelletto"],
  ["Trend su X", "Grafico"],
  ["Spunta Blu", "Colore"],
  ["Commento Ironico", "Sarcasmo"],

  // Controversie e cultura online
  ["Cena con Kanye", "Tavolo"],
  ["Ye", "Rapper ospite"],
  ["Streamer Amico", "Community online, controverso"],
  ["Manosphere", "Ambiente online"],
  ["Alpha Male", "Autodefinizione"],
  ["Sigma Grindset", "Meme lavoro"],
  ["Rizz", "Gergo giovane"],
  ["Looksmaxxing", "Ossessione estetica"],
  ["Mewing", "Esercizio mascella"],
  ["Jawline", "Linea desiderata"],

  // Vita personale (leggera, pubblica)
  ["Moglie", "Sposa"],
  ["Matrimonio", "Evento pubblicato"],
  ["Anello", "Fidanzamento"],
  ["Foto di Coppia", "Social"],
  ["Vita Familiare", "Istituto"],

  // Formati e spettacolo
  ["Podcast", "Cuffie"],
  ["Spettacolo dal vivo", "Palco"],
  ["Intervista", "Orologio"],
  ["Diretta Streaming", "Buffering"],
  ["Studio Televisivo", "Riflettori"],
  ["Cue Card", "Cartoncino"],
  ["Gobbo Elettronico", "Vetro"],
  ["Applausometro", "Decibel"],
  ["Volantino", "Carta"],
  ["Merchandising", "Scatola"],
];
