export const CHARLIE_KIRK: [string, string][] = [
  ["Charlie Kirk", "Persona pubblica"],
  ["Campus", "Luogo"],
  ["Microfono", "Oggetto"],
  ["Podcast", "Ascolto"],
  ["Meme", "Internet"],
  ["Cappellino rosso", "Abbigliamento"],
  ["Conservatore", "Posizione"],
  ["Capitalismo", "Sistema"],
  ["Socialismo", "Sistema"],
  ["Tasse", "Soldi"],
  ["Libertà di parola", "Diritto"],
  ["Fake news", "Informazione"],
  ["Diretta streaming", "Internet"],
  ["Applauso", "Reazione"],
  ["Fischio", "Reazione"],
  ["Comizio", "Evento"],
  ["Domanda scomoda", "Confronto"],
  ["Elon Musk", "Persona pubblica"],
  ["Trump", "Persona pubblica"],
  ["Merchandising", "Commercio"],
];
