export const CHARLIE_KIRK: [string, string][] = [
  ["Dibattito al campus", "Gazebo"],
  ["Turning Point USA", "Zainetto"],
  ["Microfono aperto", "Cavo"],
  ["Cappellino rosso", "Visiera"],
  ["Podcast politico", "Cuffie"],
  ["Studente universitario", "Zaino"],
  ["Fila per parlare", "Pazienza"],
  ["Conservatore", "Cravatta"],
  ["Liberal", "Sciarpa"],
  ["Comizio", "Bandierine"],
  ["Applauso scrosciante", "Palmo"],
  ["Fischio dal pubblico", "Labbra"],
  ["Domanda scomoda", "Sudore"],
  ["Slogan da campagna", "Rima"],
  ["Bandiera americana", "Stelle"],
  ["Freedom", "Aquila"],
  ["Talk show serale", "Divano"],
  ["Intervista in diretta", "Orologio"],
  ["Social media manager", "Notifica"],
  ["Tweet virale", "Retweet"],
  ["Meme politico", "Risata"],
  ["Commento sotto il video", "Emoji"],
  ["Sedia vuota sul palco", "Polvere"],
  ["Registratore vocale", "Nastro"],
  ["Giacca blu elettorale", "Bottone"],
  ["Cravatta a righe", "Nodo"],
  ["Palco improvvisato", "Legno"],
  ["Ventilatore in sala", "Rumore"],
  ["Bottiglia d'acqua sul leggio", "Etichetta"],
  ["Applausometro", "Decibel"],
  ["Sondaggio d'opinione", "Percentuale"],
  ["Giornalista in prima fila", "Taccuino"],
  ["Telecamera a mano", "Batteria"],
  ["Diretta streaming", "Buffering"],
  ["Chat del live", "Scorrimento"],
  ["Hashtag di tendenza", "Cancelletto"],
  ["Coro da stadio", "Eco"],
  ["Fan accanito", "Adesivo"],
  ["Detrattore online", "Faccina"],
  ["Podio di legno", "Vernice"],
  ["Cartellone di protesta", "Pennarello"],
  ["Volantino elettorale", "Carta"],
  ["Banchetto informativo", "Tovaglia"],
  ["Firma di petizione", "Penna"],
  ["Selfie col pubblico", "Flash"],
  ["Autografo su un libro", "Dedica"],
  ["Libro di saggistica", "Copertina"],
  ["Presentazione del libro", "Sedia"],
  ["Coda all'entrata", "Serpentina"],
  ["Metal detector all'ingresso", "Bip"],
  ["Guardia del corpo", "Auricolare"],
  ["Backstage caotico", "Cavi"],
  ["Camerino improvvisato", "Specchio"],
  ["Trucco prima della diretta", "Cipria"],
  ["Sponsor del podcast", "Logo"],
  ["Pubblicità in mezzo al video", "Countdown"],
  ["Cartello Applause", "Freccia"],
  ["Studio televisivo minimal", "Riflettori"],
  ["Domanda dal pubblico anonima", "Bigliettino"],
  ["Battuta pungente", "Silenzio"],
  ["Frase citata fuori contesto", "Virgolette"],
  ["Screenshot condiviso", "Ritaglio"],
  ["Clip tagliata ad arte", "Forbici"],
  ["Commento ironico", "Sarcasmo"],
  ["Trend su X", "Grafico"],
  ["Bio del profilo social", "Emoji"],
  ["Spunta blu", "Colore"],
  ["Follower in aumento", "Numero"],
  ["Algoritmo dei social", "Mistero"],
  ["Live reaction", "Popcorn"],
  ["Debunking in tempo reale", "Fact"],
  ["Fact checking", "Lente"],
  ["Meme con font Impact", "Bordo"],
  ["Screenshot sfocato", "Pixel"],
  ["Caption sarcastica", "Punto"],
  ["Compilation di gaffe", "Montaggio"],
  ["Reaction video", "Faccia"],
  ["Streamer commentatore", "Webcam"],
  ["Chat impazzita", "Spam"],
  ["Donazione in diretta", "Suono"],
  ["Superchat colorata", "Colore"],
  ["Cartellone universitario", "Puntina"],
  ["Zaino con adesivi politici", "Cucitura"],
  ["Felpa con logo", "Cappuccio"],
  ["Cappello da baseball rosso", "Curva"],
  ["Occhiali da sole scuri", "Riflesso"],
  ["Barba curata", "Pettine"],
  ["Sorriso da campagna", "Denti"],
  ["Stretta di mano ufficiale", "Anello"],
  ["Foto con supporter", "Sfondo"],
  ["Bandiera sul palco", "Vento"],
  ["Inno prima del comizio", "Coro"],
  ["Applauso in piedi", "Sedia"],
  ["Standing ovation", "Fatica"],
  ["Domanda retorica", "Punto"],
  ["Battibecco acceso", "Volume"],
  ["Zittire l'interlocutore", "Gesto"],
  ["Interruzione improvvisa", "Pausa"],
  ["Turno di parola", "Cronometro"],
  ["Cronometro del dibattito", "Lancetta"],
  ["Moderatore neutrale", "Taccuino"],
  ["Regole del confronto", "Foglio"],
  ["Palco a due leggii", "Simmetria"],
  ["Pubblico diviso a metà", "Corridoio"],
  ["Sezione tifoseria pro", "Sinistra"],
  ["Sezione tifoseria contro", "Destra"],
  ["Cartello con freccia", "Vernice"],
  ["Megafono improvvisato", "Batteria"],
  ["Volantinaggio in piazza", "Vento"],
  ["Banchetto raccolta firme", "Tavolino"],
  ["Adesivo sul laptop", "Angolo"],
  ["Sticker sul paraurti", "Colla"],
  ["Furgone della campagna", "Altoparlante"],
  ["Bus del tour elettorale", "Finestrino"],
  ["Tappa universitaria", "Mappa"],
  ["Locandina dell'evento", "Puntine"],
  ["Biglietto omaggio", "Coda"],
  ["Fila per la foto ricordo", "Pazienza"],
  ["Firma sul cappellino", "Pennarello"],
  ["T-shirt con slogan", "Taglia"],
  ["Merchandising politico", "Scatola"],
  ["Bandana elettorale", "Nodo"],
  ["Spilla sul bavero", "Puntina"],
  ["Distintivo del volontario", "Nastro"],
  ["Volontario con clipboard", "Penna"],
  ["Registro dei votanti", "Elenco"],
  ["Seggio elettorale", "Cabina"],
  ["Scheda elettorale", "Matita"],
  ["Urna trasparente", "Fessura"],
  ["Exit poll", "Microfono"],
  ["Proiezione dei risultati", "Schermo"],
  ["Notte elettorale", "Caffè"],
  ["Party post elezione", "Coriandoli"],
  ["Discorso di vittoria", "Palco"],
  ["Discorso di sconfitta", "Silenzio"],
  ["Confetti sul palco", "Pavimento"],
  ["Bandiere sventolate", "Braccia"],
  ["Coro da campagna", "Ritmo"],
  ["Claque organizzata", "Applauso"],
  ["Cori da stadio politico", "Eco"],
  ["Fischietto della protesta", "Fiato"],
  ["Cartello ironico", "Colore"],
  ["Costume satirico", "Cucitura"],
  ["Maschera caricaturale", "Elastico"],
  ["Vignetta satirica", "Matita"],
  ["Fumetto politico", "Nuvoletta"],
  ["Editoriale al vetriolo", "Inchiostro"],
  ["Titolo clickbait", "Font"],
  ["Notizia rilanciata", "Condivisione"],
  ["Bufala smentita", "Lente"],
  ["Screenshot del tweet cancellato", "Archivio"],
  ["Thread infinito", "Scroll"],
  ["Risposta al thread", "Notifica"],
  ["Blocco su X", "Icona"],
  ["Silenziato in chat", "Simbolo"],
  ["Ban temporaneo", "Timer"],
  ["Deplatforming", "Cartello"],
  ["Contro-narrativa online", "Specchio"],
  ["Sala conferenze affollata", "Sedie"],
  ["Domande preselezionate", "Bigliettino"],
  ["Q&A infuocato", "Timer"],
  ["Applauso finale", "Mani"],
  ["Uscita di sicurezza affollata", "Cartello"],
  ["Firma del contratto libro", "Penna"],
  ["Tour promozionale", "Valigia"],
  ["Firma copie in libreria", "Fila"],
  ["Scaffale bestseller", "Etichetta"],
  ["Recensione online", "Stelle"],
  ["Commento negativo", "Pollice"],
  ["Commento entusiasta", "Cuore"],
  ["Rubrica radiofonica", "Antenna"],
  ["Chiamata in diretta radio", "Squillo"],
  ["Ospite in studio", "Sedia"],
  ["Sedia degli ospiti", "Cuscino"],
  ["Pausa pubblicitaria", "Orologio"],
  ["Jingle del programma", "Nota"],
  ["Sigla di apertura", "Titoli"],
  ["Sigla di chiusura", "Crediti"],
  ["Compilation di highlights", "Forbici"],
  ["Riassunto della puntata", "Elenco"],
  ["Grafica a schermo", "Pixel"],
  ["Sottopancia con nome", "Font"],
  ["Ticker di notizie", "Scorrimento"],
  ["Breaking news improvvisa", "Sirena"],
  ["Conferenza stampa affollata", "Flash"],
  ["Domanda dal fondo sala", "Eco"],
  ["Microfono che fischia", "Feedback"],
  ["Cavo del microfono aggrovigliato", "Nodo"],
  ["Assistente di palco", "Cuffia"],
  ["Cue card fuori campo", "Cartoncino"],
  ["Gobbo elettronico", "Vetro"],
  ["Prompt del discorso", "Scorrimento"],
  ["Applauso registrato", "Altoparlante"],
  ["Pubblico in studio", "Poltrone"],
  ["Biglietti gratuiti per lo show", "Coda"],
  ["Selfie post spettacolo", "Flash"],
  ["Autografo su una maglietta", "Pennarello"],
  ["Fan club dedicato", "Adesivi"],
  ["Gruppo Facebook di supporto", "Icona"],
  ["Server Discord politico", "Canale"],
  ["Meme template riciclato", "Cornice"],
  ["Caption in maiuscolo", "Volume"],
  ["Font Impact bianco", "Bordo"],
  ["Sottotitoli automatici sbagliati", "Errore"],
  ["Traduzione approssimativa", "Dizionario"],
  ["Clip doppiata ironicamente", "Voce"],
  ["Remix audio virale", "Beat"],
  ["Suoneria del meme", "Volume"],
  ["Challenge social nata dal video", "Hashtag"],
  ["Reaction compilation", "Montaggio"],
  ["Video reazione a caldo", "Sorpresa"],
  ["Analisi punto per punto", "Lavagna"],
  ["Lavagna con appunti", "Gesso"],
  ["Grafico a torta improvvisato", "Colore"],
  ["Statistica citata a memoria", "Numero"],
  ["Fonte non verificata", "Punto interrogativo"],
  ["Nota a piè di pagina", "Asterisco"],
  ["Citazione fuori contesto", "Virgolette"],
  ["Screenshot con freccia rossa", "Cerchio"],
  ["Cerchiatura in rosso", "Pennarello"],
  ["Freccia esplicativa", "Grafica"],
  ["Montaggio con musica epica", "Orchestra"],
  ["Slow motion drammatico", "Fotogramma"],
];
