export const CIBO: [string, string][] = [
  ["Pizza", "Forno domenicale"],
  ["Carbonara", "Discussione infinita"],
  ["Caffè", "Rito mattutino"],
  ["Tiramisù", "Cucchiaio finale"],
  ["Nutella", "Colazione golosa"],
  ["Pane", "Profumo caldo"],
  ["Mozzarella", "Filo bianco"],
  ["Peperoncino", "Fuoco"],
  ["Gelato", "Estate sciolta"],
  ["Lasagna", "Strati domenicali"],
  ["Vino", "Brindisi"],
  ["Aperitivo", "Sei di sera"],
  ["Panettone", "Dicembre"],
  ["Pesto", "Verde ligure"],
  ["Cornetto", "Bar mattina"],
  ["Parmigiano", "Grattugia"],
  ["Birra", "Schiuma"],
  ["Sushi", "Bacchette"],
  ["Ananas", "Eresia sulla pizza"],
  ["Ketchup", "Rosso industriale"],
];
