export const CIBO: [string, string][] = [
  ["Carbonara", "Discussione"],
  ["Pizza", "Litigio"],
  ["Lasagne", "Domenica"],
  ["Tiramisù", "Cucchiaio bagnato"],
  ["Risotto", "Pazienza"],
  ["Gnocchi", "Pollice"],
  ["Ravioli", "Nonna"],
  ["Tortellini", "Ombelico"],
  ["Parmigiana", "Teglia"],
  ["Cannoli", "Sicilia"],
  ["Panettone", "Dicembre"],
  ["Pandoro", "Zucchero a velo"],
  ["Colomba", "Aprile"],
  ["Focaccia", "Olio"],
  ["Pane", "Lievito"],
  ["Pasta", "Vapore"],
  ["Sugo", "Macchia"],
  ["Ragù", "Ore"],
  ["Pesto", "Mortaio"],
  ["Aglio", "Alito"],
  ["Cipolla", "Lacrime"],
  ["Olio d'oliva", "Bottiglia"],
  ["Aceto", "Naso"],
  ["Sale", "Pizzico"],
  ["Pepe", "Starnuto"],
  ["Basilico", "Vaso"],
  ["Prezzemolo", "Denti"],
  ["Rosmarino", "Arrosto"],
  ["Formaggio", "Buchi"],
  ["Mozzarella", "Filo"],
  ["Parmigiano", "Grattugia"],
  ["Ricotta", "Cucchiaino"],
  ["Gorgonzola", "Odore"],
  ["Pecorino", "Ape"],
  ["Prosciutto", "Osso"],
  ["Salame", "Coltello"],
  ["Mortadella", "Rosa"],
  ["Bresaola", "Limone"],
  ["Speck", "Montagna"],
  ["Uova", "Guscio"],
  ["Frittata", "Padella"],
  ["Omelette", "Piega"],
  ["Bistecca", "Griglia"],
  ["Cotoletta", "Impanatura"],
  ["Arrosto", "Termometro"],
  ["Salsiccia", "Griglia calda"],
  ["Polpette", "Palla"],
  ["Hamburger", "Panino"],
  ["Hot dog", "Senape"],
  ["Patatine", "Busta"],
  ["Panino", "Carta"],
  ["Insalata", "Forchetta"],
  ["Zuppa", "Cucchiaio"],
  ["Minestrone", "Nonna"],
  ["Brodo", "Vapore"],
  ["Polenta", "Legno"],
  ["Riso", "Chicco"],
  ["Farro", "Campo"],
  ["Orzo", "Estate"],
  ["Cous cous", "Sabbia"],
  ["Quinoa", "Moda"],
  ["Pane carasau", "Sardegna"],
  ["Piadina", "Romagna"],
  ["Arancini", "Palla di riso"],
  ["Supplì", "Filo"],
  ["Crocchette", "Olio bollente"],
  ["Fritto misto", "Carta oleata"],
  ["Baccalà", "Venerdì"],
  ["Alici", "Barattolo"],
  ["Tonno", "Scatoletta"],
  ["Salmone", "Rosa"],
  ["Gamberi", "Sgusciare"],
  ["Vongole", "Sabbia"],
  ["Cozze", "Guscio nero"],
  ["Polpo", "Ventosa"],
  ["Calamari", "Anello"],
  ["Frutti di mare", "Piatto grande"],
  ["Zuppa di pesce", "Lisca"],
  ["Melanzane", "Viola"],
  ["Zucchine", "Fiore"],
  ["Peperoni", "Bruciacchiati"],
  ["Pomodoro", "Ombelico"],
  ["Carote", "Vista"],
  ["Patate", "Terra"],
  ["Funghi", "Bosco"],
  ["Tartufo", "Cane"],
  ["Carciofi", "Spina"],
  ["Asparagi", "Odore"],
  ["Broccoli", "Verde"],
  ["Cavolfiore", "Bianco"],
  ["Spinaci", "Marinaio"],
  ["Fagioli", "Fischio"],
  ["Ceci", "Farinata"],
  ["Lenticchie", "Capodanno"],
  ["Piselli", "Bacello"],
  ["Mele", "Maestra"],
  ["Pere", "Formaggio"],
  ["Uva", "Grappolo"],
  ["Fragole", "Panna"],
  ["Pesche", "Vino"],
  ["Albicocche", "Nocciolo"],
  ["Ciliegie", "Peduncolo"],
  ["Anguria", "Semi"],
  ["Melone", "Prosciutto"],
  ["Banana", "Buccia"],
  ["Ananas", "Corona"],
  ["Kiwi", "Peluria"],
  ["Limone", "Spicchio"],
  ["Arancia", "Buccia"],
  ["Mandarino", "Spicchio piccolo"],
  ["Fichi", "Miele"],
  ["Castagne", "Caldarroste"],
  ["Noci", "Guscio"],
  ["Nocciole", "Ferrero"],
  ["Mandorle", "Sicilia dolce"],
  ["Pistacchi", "Verde"],
  ["Cioccolato", "Scatola"],
  ["Nutella", "Cucchiaio"],
  ["Gelato", "Cono"],
  ["Sorbetto", "Freddo"],
  ["Granita", "Brioche"],
  ["Cannolo", "Guscio"],
  ["Zeppole", "San Giuseppe"],
  ["Bignè", "Crema"],
  ["Millefoglie", "Strati"],
  ["Crostata", "Griglia di pasta"],
  ["Torta", "Candeline"],
  ["Cheesecake", "Biscotto"],
  ["Ciambella", "Buco"],
  ["Brioche", "Colazione"],
  ["Croissant", "Francia"],
  ["Cornetto", "Bar"],
  ["Biscotti", "Barattolo"],
  ["Wafer", "Cioccolato bianco"],
  ["Caramelle", "Carta colorata"],
  ["Cioccolatini", "Scatola rossa"],
  ["Marmellata", "Vasetto"],
  ["Miele", "Ape"],
  ["Nutella e pane", "Merenda"],
  ["Yogurt", "Cucchiaino"],
  ["Latte", "Bicchiere"],
  ["Panna", "Sifone"],
  ["Burro", "Panetto"],
  ["Caffè", "Tazzina"],
  ["Espresso", "Schiuma"],
  ["Cappuccino", "Cacao"],
  ["Macchiato", "Goccia"],
  ["Cioccolata calda", "Inverno"],
  ["Tè", "Bustina"],
  ["Camomilla", "Sonno"],
  ["Vino", "Calice"],
  ["Prosecco", "Bollicine"],
  ["Champagne", "Tappo"],
  ["Birra", "Schiuma"],
  ["Grappa", "Bicchierino"],
  ["Limoncello", "Costiera"],
  ["Amaro", "Digestione"],
  ["Cocktail", "Ombrellino"],
  ["Spritz", "Aperitivo"],
  ["Mojito", "Menta"],
  ["Margarita", "Sale"],
  ["Sangria", "Frutta a pezzi"],
  ["Acqua", "Rubinetto"],
  ["Succo di frutta", "Cannuccia"],
  ["Frullato", "Cannuccia"],
  ["Centrifuga", "Buccia"],
  ["Bibita", "Ghiaccio"],
  ["Aranciata", "Etichetta arancione"],
  ["Chinotto", "Bottiglia scura"],
  ["Gazzosa", "Bollicine piccole"],
  ["Aperitivo", "Stuzzichini"],
  ["Antipasto", "Attesa"],
  ["Primo", "Fumo"],
  ["Secondo", "Contorno"],
  ["Contorno", "Piattino"],
  ["Dolce", "Ultimo"],
  ["Digestivo", "Bicchierino"],
  ["Menù", "Carta"],
  ["Ricetta", "Quaderno"],
  ["Ingrediente", "Bilancia"],
  ["Condimento", "Bottiglietta"],
  ["Marinatura", "Attesa lunga"],
  ["Cottura", "Timer"],
  ["Bollitura", "Vapore"],
  ["Frittura", "Schizzo"],
  ["Grigliata", "Fumo"],
  ["Forno", "Guanto"],
  ["Fornello", "Fiamma"],
  ["Pentola", "Coperchio"],
  ["Padella", "Manico"],
  ["Coltello", "Tagliere"],
  ["Tagliere", "Legno"],
  ["Mestolo", "Legno"],
  ["Frullatore", "Rumore"],
  ["Grattugia", "Nocche"],
  ["Mattarello", "Farina"],
  ["Tovaglia", "Macchia"],
  ["Tovagliolo", "Piega"],
  ["Piatto", "Cerchio"],
  ["Bicchiere", "Impronta"],
  ["Forchetta", "Rebbio"],
  ["Cucchiaio", "Riflesso"],
  ["Tavola", "Sedia"],
  ["Cena", "Candela"],
  ["Pranzo", "Sveglia"],
  ["Colazione", "Alba"],
  ["Merenda", "Scuola"],
  ["Spuntino", "Fretta"],
  ["Buffet", "Piatto pieno"],
  ["Ristorante", "Conto"],
  ["Trattoria", "Tovaglia a quadri"],
  ["Osteria", "Vino sfuso"],
  ["Pizzeria", "Forno a legna"],
  ["Cameriere", "Vassoio"],
  ["Chef", "Cappello alto"],
  ["Sommelier", "Naso"],
  ["Pasticciere", "Zucchero"],
  ["Fornaio", "Alba"],
  ["Macellaio", "Grembiule"],
  ["Mercato", "Cassetta"],
  ["Sagra", "Palco piccolo"],
  ["Festa del paese", "Luci"],
  ["Cena di Natale", "Camino"],
  ["Pranzo di Pasqua", "Uova colorate"],
  ["Ferragosto", "Cocomero"],
  ["Aperitivo con amici", "Chiasso"],
  ["Dieta", "Bilancia"],
  ["Digiuno", "Stomaco"],
  ["Abbuffata", "Cintura"],
  ["Avanzi", "Frigo"],
  ["Frigorifero", "Ronzio"],
  ["Dispensa", "Barattoli"],
  ["Lista della spesa", "Foglietto"],
  ["Spesa", "Carrello"],
  ["Etichetta", "Scadenza"],
  ["Scontrino", "Portafoglio"],
];
