export const CIBO: [string, string][] = [
  ["Pizza", "Domenica"],
  ["Carbonara", "Tavola"],
  ["Caffè", "Mattina"],
  ["Tiramisù", "Fine pasto"],
  ["Nutella", "Dolcezza"],
  ["Pane", "Quotidiano"],
  ["Mozzarella", "Frigorifero"],
  ["Peperoncino", "Sapore forte"],
  ["Gelato", "Estate"],
  ["Lasagna", "Festa"],
  ["Vino", "Serata"],
  ["Aperitivo", "Sera"],
  ["Panettone", "Feste"],
  ["Pesto", "Regione"],
  ["Cornetto", "Bar"],
  ["Parmigiano", "Cucina"],
  ["Birra", "Serata"],
  ["Sushi", "Fuori casa"],
  ["Ananas", "Polemica"],
  ["Ketchup", "Condimento"],
];
