export const CINEMA: [string, string][] = [
  ["Popcorn", "Serata"],
  ["Regista", "Mestiere"],
  ["Ciak", "Set"],
  ["Oscar", "Premio"],
  ["Colonna sonora", "Suono"],
  ["Trailer", "Prima"],
  ["Doppiaggio", "Voce"],
  ["Comparsa", "Ruolo"],
  ["Cinepanettone", "Stagione"],
  ["Sala", "Luogo"],
  ["Proiettore", "Macchina"],
  ["Sceneggiatura", "Carta"],
  ["Attore", "Mestiere"],
  ["Effetti speciali", "Tecnica"],
  ["Titoli di coda", "Fine"],
  ["Sequel", "Seguito"],
  ["Horror", "Genere"],
  ["Commedia", "Genere"],
  ["Festival", "Evento"],
  ["Biglietto", "Ingresso"],
];
