export const CINEMA: [string, string][] = [
  ["Titanic", "Film nave affondata"],
  ["Il Padrino", "Film mafia americana"],
  ["Pulp Fiction", "Film crime intrecciato"],
  ["Star Wars", "Saga fantascienza spaziale"],
  ["Il Signore degli Anelli", "Saga fantasy anello"],
  ["Forrest Gump", "Film vita straordinaria"],
  ["Rocky", "Film pugilato riscatto"],
  ["Jurassic Park", "Film dinosauri clonati"],
  ["Matrix", "Film realtà simulata"],
  ["Il Gladiatore", "Film epico romano"],
  ["Avatar", "Film fantascienza pianeta alieno"],
  ["Inception", "Film sogni multipli"],
  ["Il Grande Lebowski", "Film comico surreale"],
  ["Fight Club", "Film lotte clandestine"],
  ["Shining", "Film horror hotel isolato"],
  ["Psycho", "Film horror thriller storico"],
  ["Casablanca", "Film romantico bellico"],
  ["Via col Vento", "Film epico guerra civile"],
  ["La La Land", "Film musicale romantico"],
  ["Amelie", "Film francese sognante"],
  ["Nuovo Cinema Paradiso", "Film italiano proiezionista"],
  ["La Vita è Bella", "Film italiano campo concentramento"],
  ["Il Silenzio degli Innocenti", "Film thriller serial killer"],
  ["Se7en", "Film thriller peccati capitali"],
  ["Il Corvo", "Film vendetta gotica"],
  ["Blade Runner", "Film fantascienza replicanti"],
  ["E.T.", "Film alieno amico bambino"],
  ["Ritorno al Futuro", "Film viaggio nel tempo"],
  ["Jaws", "Film squalo spiaggia"],
  ["Alien", "Film mostro spaziale"],
  ["Terminator", "Film robot dal futuro"],
  ["Rambo", "Film ex militare guerriero"],
  ["Scarface", "Film gangster cocaina"],
  ["Goodfellas", "Film mafia americana"],
  ["Taxi Driver", "Film tassista solitario"],
  ["Il Cavaliere Oscuro", "Film supereroe pipistrello"],
  ["Spider-Man", "Film supereroe ragno"],
  ["Superman", "Film supereroe kryptoniano"],
  ["Iron Man", "Film supereroe armatura"],
  ["Avengers", "Film supereroi squadra"],
  ["Toy Story", "Film animazione giocattoli"],
  ["Il Re Leone", "Film animazione savana"],
  ["Frozen", "Film animazione ghiaccio"],
  ["Aladdin", "Film animazione principe finto"],
  ["La Sirenetta", "Film animazione mare"],
  ["Biancaneve", "Film animazione fiaba classica"],
  ["Cenerentola", "Film animazione fiaba scarpetta"],
  ["Up", "Film animazione casa volante"],
  ["Wall-E", "Film animazione robot spazzino"],
  ["Coco", "Film animazione messicano musica"],
  ["Inside Out", "Film animazione emozioni"],
  ["Shrek", "Film animazione orco"],
  ["Kung Fu Panda", "Film animazione arti marziali"],
  ["Madagascar", "Film animazione zoo"],
  ["Ice Age", "Film animazione preistorico"],
  ["Cars", "Film animazione automobili"],
  ["Monsters & Co.", "Film animazione mostri"],
  ["Ratatouille", "Film animazione topo cuoco"],
  ["Il Discorso del Re", "Film storico monarchia inglese"],
  ["Braveheart", "Film epico scozzese"],
  ["Il Trono di Spade", "Serie fantasy medievale"],
  ["Harry Potter", "Saga fantasy maghi"],
  ["Il Diavolo Veste Prada", "Film mondo della moda"],
  ["Colazione da Tiffany", "Film romantico newyorkese"],
  ["Un Americano a Parigi", "Musical romantico parigino"],
  ["Cantando sotto la Pioggia", "Musical classico"],
  ["West Side Story", "Musical bande rivali"],
  ["Grease", "Musical scolastico anni 50"],
  ["Dirty Dancing", "Film ballo estivo"],
  ["Flashdance", "Film ballo operaia"],
  ["Footloose", "Film ballo proibito"],
  ["Saturday Night Fever", "Film discoteca anni 70"],
  ["Chicago", "Musical crime anni 20"],
  ["Il Fantasma dell'Opera", "Musical mistero teatrale"],
  ["Moulin Rouge", "Musical cabaret parigino"],
  ["Il Grande Showman", "Musical circo americano"],
  ["Cabaret", "Musical d'epoca"],
  ["Sweeney Todd", "Musical horror barbiere"],
  ["Dracula", "Film horror vampiro classico"],
  ["Frankenstein", "Film horror mostro creato"],
  ["La Mummia", "Film avventura egizia"],
  ["Il Fantasma della Cripta", "Film horror non morti"],
  ["L'Esorcista", "Film horror possessione"],
  ["Poltergeist", "Film horror casa infestata"],
  ["It", "Film horror clown"],
  ["Nightmare", "Film horror sogni"],
  ["Halloween", "Film horror slasher maschera"],
  ["Venerdì 13", "Film horror slasher lago"],
  ["Scream", "Film horror slasher maschera bianca"],
  ["Saw", "Film horror trappole mortali"],
  ["Hostel", "Film horror turismo"],
  ["Ring", "Film horror videocassetta"],
  ["The Grudge", "Film horror giapponese"],
  ["La Casa", "Film horror cabina bosco"],
  ["Insidious", "Film horror dimensione oscura"],
  ["The Conjuring", "Film horror investigatori paranormali"],
  ["Annabelle", "Film horror bambola posseduta"],
  ["Hereditary", "Film horror famiglia maledetta"],
  ["Midsommar", "Film horror setta scandinava"],
  ["Get Out", "Film horror sociale ipnosi"],
  ["Us", "Film horror doppelganger"],
  ["A Quiet Place", "Film horror silenzio obbligato"],
  ["Bird Box", "Film horror bendati"],
  ["Il Miglio Verde", "Film drammatico prigione"],
  ["Le Ali della Libertà", "Film drammatico carcere"],
  ["American History X", "Film drammatico razzismo"],
  ["Full Metal Jacket", "Film di guerra addestramento"],
  ["Apocalypse Now", "Film di guerra vietnam"],
  ["Platoon", "Film di guerra soldati"],
  ["Salvate il Soldato Ryan", "Film di guerra sbarco"],
  ["Il Paziente Inglese", "Film romantico bellico deserto"],
  ["Il Cacciatore", "Film di guerra amicizia"],
  ["Momenti di Gloria", "Film sportivo olimpiadi"],
  ["Un Uomo Tranquillo", "Film romantico irlandese"],
  ["Balla coi Lupi", "Film epico nativi americani"],
  ["Mission Impossible", "Film spionaggio acrobatico"],
  ["James Bond 007", "Saga spionaggio inglese"],
  ["Ocean's Eleven", "Film colpo grosso casinò"],
  ["Heat", "Film poliziesco rapina"],
  ["Il Sesto Senso", "Film thriller soprannaturale"],
  ["The Truman Show", "Film satirico realtà finta"],
  ["Donnie Darko", "Film mistero adolescenziale"],
  ["Memento", "Film thriller memoria"],
  ["Il Grande Freddo", "Film drammatico amicizia adulta"],
  ["American Beauty", "Film drammatico crisi familiare"],
  ["Magnolia", "Film corale drammatico"],
  ["Little Miss Sunshine", "Film commedia familiare on the road"],
  ["Juno", "Film commedia gravidanza adolescente"],
  ["500 Giorni Insieme", "Film romantico non convenzionale"],
  ["Eternal Sunshine", "Film romantico memoria cancellata"],
  ["Her", "Film romantico intelligenza artificiale"],
  ["Lost in Translation", "Film drammatico in Oriente"],
  ["Il Favoloso Mondo di Amelie", "Film francese fantasioso"],
  ["Midnight in Paris", "Film romantico fuori dal tempo"],
  ["Vicky Cristina Barcelona", "Film romantico spagnolo"],
  ["Manhattan", "Film romantico newyorkese classico"],
  ["Annie Hall", "Film commedia romantica classica"],
  ["Chinatown", "Film noir investigativo"],
  ["Il Grande Sonno", "Film noir detective"],
  ["L.A. Confidential", "Film noir poliziesco"],
  ["Sunset Boulevard", "Film drammatico sul cinema"],
  ["Quarto Potere", "Film drammatico giornalismo"],
  ["La Finestra sul Cortile", "Film thriller di Hitchcock"],
  ["Vertigo", "Film thriller vertigini"],
  ["Gli Uccelli", "Film horror con animali"],
  ["La Donna che Visse Due Volte", "Film thriller identità"],
  ["Intrigo Internazionale", "Film spionaggio classico"],
  ["Rear Window", "Film thriller finestra"],
  ["Il Terzo Uomo", "Film noir viennese"],
  ["Ladri di Biciclette", "Film neorealista italiano"],
  ["Roma Città Aperta", "Film neorealista guerra"],
  ["La Dolce Vita", "Film italiano mondano"],
  ["8½", "Film italiano crisi creativa"],
  ["Amarcord", "Film italiano nostalgico"],
  ["C'era una Volta il West", "Film western epico"],
  ["Il Buono il Brutto il Cattivo", "Film western trio"],
  ["Per un Pugno di Dollari", "Film western spaghetti"],
  ["Django", "Film western vendetta"],
  ["Kill Bill", "Film vendetta katana"],
  ["Le Iene", "Film crime rapina fallita"],
  ["Bastardi Senza Gloria", "Film di guerra nazisti"],
  ["Django Unchained", "Film western schiavitù"],
  ["C'era una Volta a Hollywood", "Film corale anni Sessanta"],
  ["Jackie Brown", "Film crime contrabbando"],
  ["Death Proof", "Film horror auto killer"],
  ["Il Piano", "Film drammatico muta"],
  ["Lezioni di Piano", "Film romantico neozelandese"],
  ["Il Curioso Caso di Benjamin Button", "Film fantastico invecchiamento inverso"],
  ["Big Fish", "Film fantastico racconti padre"],
  ["Edward Mani di Forbice", "Film fantastico gotico"],
  ["Batman Returns", "Film supereroe natalizio"],
  ["La Sposa Cadavere", "Film animazione stop motion gotico"],
  ["Nightmare Before Christmas", "Film animazione stop motion natalizio"],
  ["Charlie e la Fabbrica di Cioccolato", "Film fantastico dolciario"],
  ["James e la Pesca Gigante", "Animazione con un frutto"],
  ["Matilda", "Film fantastico bambina prodigio"],
  ["Le Cronache di Narnia", "Saga fantasy mondo magico"],
  ["Il Labirinto del Fauno", "Film fantasy spagnolo bellico"],
  ["La Vita degli Altri", "Film drammatico spionaggio tedesco"],
  ["Il Nastro Bianco", "Film drammatico rurale tedesco"],
  ["Parasite", "Film drammatico coreano classi sociali"],
  ["Old Boy", "Film thriller coreano vendetta"],
  ["Snowpiercer", "Film fantascienza treno post-apocalittico"],
  ["Memories of Murder", "Film thriller coreano indagine"],
  ["Il Buco", "Film thriller spagnolo prigione verticale"],
  ["Roma (Cuarón)", "Film drammatico messicano bianco e nero"],
  ["Gravity", "Film fantascienza spazio orbitale"],
  ["The Martian", "Fantascienza di sopravvivenza"],
  ["Interstellar", "Film fantascienza viaggio spaziale"],
  ["Contact", "Film fantascienza contatto alieno"],
  ["Arrival", "Film fantascienza linguaggio alieno"],
  ["Blade Runner 2049", "Film fantascienza replicanti sequel"],
  ["Dune", "Film fantascienza pianeta desertico"],
  ["Mad Max Fury Road", "Film azione post-apocalittico deserto"],
  ["Waterworld", "Film fantascienza pianeta sommerso"],
  ["Il Postino", "Film italiano poesia"],
  ["Cinema Paradiso", "Film italiano proiezionista siciliano"],
  ["La Grande Bellezza", "Film italiano vita romana"],
  ["Perfetti Sconosciuti", "Film italiano cena tra amici"],
  ["Il Sorpasso", "Film italiano viaggio in auto"],
  ["Amici Miei", "Film italiano comico amicizia"],
  ["Un Sacco Bello", "Film italiano commedia anni 80"],
  ["Non ci Resta che Piangere", "Film commedia viaggio nel tempo italiano"],
  ["Il Marchese del Grillo", "Film commedia storico romano"],
  ["Fantozzi", "Film comico impiegato sfortunato"],
  ["Bianco Rosso e Verdone", "Film commedia italiana on the road"],
  ["Ecce Bombo", "Film italiano generazionale"],
  ["Caro Diario", "Film italiano autobiografico"],
  ["Mediterraneo", "Film italiano isola greca guerra"],
  ["La Vita è Bella Benigni", "Film italiano campo di concentramento"],
  ["Il Postino di Troisi", "Film italiano con un poeta"],
  ["Nuovomondo", "Film drammatico emigrazione italiana"],
  ["Io non ho Paura", "Film drammatico infanzia italiana"],
  ["Gomorra", "Film drammatico camorra"],
  ["Romanzo Criminale", "Film crime banda romana"],
  ["Suburra", "Film crime romano corruzione"],
  ["La Grande Guerra", "Film bellico italiano"],
];
