export const CINEMA: [string, string][] = [
  ["Titanic", "Freddo"],
  ["Il Padrino", "Arancia"],
  ["Pulp Fiction", "Valigetta"],
  ["Star Wars", "Deserto"],
  ["Il Signore degli Anelli", "Sentiero"],
  ["Forrest Gump", "Panchina"],
  ["Rocky", "Scalinata"],
  ["Jurassic Park", "Bicchiere"],
  ["Matrix", "Pillola"],
  ["Il Gladiatore", "Sabbia"],
  ["Avatar", "Foresta"],
  ["Inception", "Trottola"],
  ["Il Grande Lebowski", "Tappeto"],
  ["Fight Club", "Sapone"],
  ["Shining", "Corridoio"],
  ["Psycho", "Doccia"],
  ["Casablanca", "Aeroporto"],
  ["Via col Vento", "Tramonto"],
  ["La La Land", "Stelle"],
  ["Amelie", "Nano"],
  ["Nuovo Cinema Paradiso", "Pellicola"],
  ["La Vita è Bella", "Bicicletta"],
  ["Il Silenzio degli Innocenti", "Farfalla"],
  ["Se7en", "Scatola"],
  ["Il Corvo", "Pioggia"],
  ["Blade Runner", "Neon"],
  ["E.T.", "Bicicletta"],
  ["Ritorno al Futuro", "Orologio"],
  ["Jaws", "Boa"],
  ["Alien", "Uovo"],
  ["Terminator", "Occhiali"],
  ["Rambo", "Bandana"],
  ["Scarface", "Scrivania"],
  ["Goodfellas", "Cucina"],
  ["Taxi Driver", "Specchietto"],
  ["Il Cavaliere Oscuro", "Moneta"],
  ["Spider-Man", "Ombrello"],
  ["Superman", "Telefonata"],
  ["Iron Man", "Officina"],
  ["Avengers", "Palazzo"],
  ["Toy Story", "Cassetto"],
  ["Il Re Leone", "Roccia"],
  ["Frozen", "Guanto"],
  ["Aladdin", "Lampada"],
  ["La Sirenetta", "Conchiglia"],
  ["Biancaneve", "Mela"],
  ["Cenerentola", "Scarpetta"],
  ["Up", "Palloncino"],
  ["Wall-E", "Pianta"],
  ["Coco", "Ponte"],
  ["Inside Out", "Scatola"],
  ["Shrek", "Palude"],
  ["Kung Fu Panda", "Ciotola"],
  ["Madagascar", "Cassa"],
  ["Ice Age", "Ghiandola"],
  ["Cars", "Vernice"],
  ["Monsters & Co.", "Porta"],
  ["Ratatouille", "Cappello"],
  ["Il Discorso del Re", "Microfono"],
  ["Braveheart", "Collina"],
  ["Il Trono di Spade", "Cornice"],
  ["Harry Potter", "Gufo"],
  ["Il Diavolo Veste Prada", "Sciarpa"],
  ["Colazione da Tiffany", "Vetrina"],
  ["Un Americano a Parigi", "Tela"],
  ["Cantando sotto la Pioggia", "Lampione"],
  ["West Side Story", "Scalinata"],
  ["Grease", "Jukebox"],
  ["Dirty Dancing", "Stagno"],
  ["Flashdance", "Sedia"],
  ["Footloose", "Fienile"],
  ["Saturday Night Fever", "Specchio"],
  ["Chicago", "Sipario"],
  ["Il Fantasma dell'Opera", "Candelabro"],
  ["Moulin Rouge", "Elefante"],
  ["Il Grande Showman", "Circo"],
  ["Cabaret", "Trucco"],
  ["Sweeney Todd", "Rasoio"],
  ["Dracula", "Pipistrello"],
  ["Frankenstein", "Fulmine"],
  ["La Mummia", "Sabbia"],
  ["Il Fantasma della Cripta", "Ragnatela"],
  ["L'Esorcista", "Crocifisso"],
  ["Poltergeist", "Statica"],
  ["It", "Tombino"],
  ["Nightmare", "Cappello"],
  ["Halloween", "Zucca"],
  ["Venerdì 13", "Lago"],
  ["Scream", "Telefono"],
  ["Saw", "Sedia"],
  ["Hostel", "Valigia"],
  ["Ring", "Pozzo"],
  ["The Grudge", "Scala"],
  ["La Casa", "Cantina"],
  ["Insidious", "Corda"],
  ["The Conjuring", "Bambola"],
  ["Annabelle", "Vetrina"],
  ["Hereditary", "Casetta"],
  ["Midsommar", "Ghirlanda"],
  ["Get Out", "Tazza"],
  ["Us", "Forbici"],
  ["A Quiet Place", "Sabbia"],
  ["Bird Box", "Benda"],
  ["Il Miglio Verde", "Topolino"],
  ["Le Ali della Libertà", "Poster"],
  ["American History X", "Marciapiede"],
  ["Full Metal Jacket", "Elmetto"],
  ["Apocalypse Now", "Fiume"],
  ["Platoon", "Fango"],
  ["Salvate il Soldato Ryan", "Spiaggia"],
  ["Il Paziente Inglese", "Mappa"],
  ["Il Cacciatore", "Roulette"],
  ["Momenti di Gloria", "Spiaggia"],
  ["Un Uomo Tranquillo", "Cottage"],
  ["Balla coi Lupi", "Bisonte"],
  ["Mission Impossible", "Corda"],
  ["James Bond 007", "Champagne"],
  ["Ocean's Eleven", "Dado"],
  ["Heat", "Furgone"],
  ["Il Sesto Senso", "Bottone"],
  ["The Truman Show", "Nuvola"],
  ["Donnie Darko", "Coniglio"],
  ["Memento", "Polaroid"],
  ["Il Grande Freddo", "Vinile"],
  ["American Beauty", "Petalo"],
  ["Magnolia", "Rana"],
  ["Little Miss Sunshine", "Furgoncino"],
  ["Juno", "Chitarra"],
  ["500 Giorni Insieme", "Panchina"],
  ["Eternal Sunshine", "Neve"],
  ["Her", "Cuffie"],
  ["Lost in Translation", "Karaoke"],
  ["Il Favoloso Mondo di Amelie", "Innaffiatoio"],
  ["Midnight in Paris", "Orologio"],
  ["Vicky Cristina Barcelona", "Chitarra"],
  ["Manhattan", "Panchina"],
  ["Annie Hall", "Occhiali"],
  ["Chinatown", "Occhiali"],
  ["Il Grande Sonno", "Pioggia"],
  ["L.A. Confidential", "Distintivo"],
  ["Sunset Boulevard", "Piscina"],
  ["Quarto Potere", "Slitta"],
  ["La Finestra sul Cortile", "Binocolo"],
  ["Vertigo", "Scala"],
  ["Gli Uccelli", "Gabbia"],
  ["La Donna che Visse Due Volte", "Spirale"],
  ["Intrigo Internazionale", "Aereo"],
  ["Rear Window", "Cortile"],
  ["Il Terzo Uomo", "Fogna"],
  ["Ladri di Biciclette", "Muro"],
  ["Roma Città Aperta", "Portone"],
  ["La Dolce Vita", "Fontana"],
  ["8½", "Circo"],
  ["Amarcord", "Bicicletta"],
  ["C'era una Volta il West", "Orologio"],
  ["Il Buono il Brutto il Cattivo", "Cimitero"],
  ["Per un Pugno di Dollari", "Poncho"],
  ["Django", "Bara"],
  ["Kill Bill", "Katana"],
  ["Le Iene", "Orecchio"],
  ["Bastardi Senza Gloria", "Cinema"],
  ["Django Unchained", "Neve"],
  ["C'era una Volta a Hollywood", "Piscina"],
  ["Jackie Brown", "Valigia"],
  ["Death Proof", "Autoradio"],
  ["Il Piano", "Spiaggia"],
  ["Lezioni di Piano", "Riva"],
  ["Titanic II", "Iceberg"],
  ["Il Curioso Caso di Benjamin Button", "Orologio"],
  ["Big Fish", "Fiume"],
  ["Edward Mani di Forbice", "Siepe"],
  ["Batman Returns", "Neve"],
  ["Sweeney Todd Burton", "Poltrona"],
  ["La Sposa Cadavere", "Farfalla"],
  ["Nightmare Before Christmas", "Zucca"],
  ["Charlie e la Fabbrica di Cioccolato", "Ascensore"],
  ["James e la Pesca Gigante", "Verme"],
  ["Matilda", "Gessetto"],
  ["Le Cronache di Narnia", "Armadio"],
  ["Il Labirinto del Fauno", "Porta"],
  ["Pan's Labyrinth", "Gessetto"],
  ["Amélie Poulain", "Gnomo"],
  ["La Vita degli Altri", "Cuffie"],
  ["Il Nastro Bianco", "Fienile"],
  ["Parasite", "Scala"],
  ["Old Boy", "Martello"],
  ["Snowpiercer", "Vagone"],
  ["Memories of Murder", "Ombrello"],
  ["Il Buco", "Piatto"],
  ["Roma (Cuarón)", "Aereo"],
  ["Gravity", "Cavo"],
  ["The Martian", "Patata"],
  ["Interstellar", "Orologio"],
  ["Contact", "Radiotelescopio"],
  ["Arrival", "Inchiostro"],
  ["Blade Runner 2049", "Neve"],
  ["Dune", "Sabbia"],
  ["Mad Max Fury Road", "Ruggine"],
  ["Waterworld", "Bottiglia"],
  ["Il Postino", "Bicicletta"],
  ["Cinema Paradiso", "Proiettore"],
  ["La Grande Bellezza", "Terrazza"],
  ["Perfetti Sconosciuti", "Tavolo"],
  ["Il Sorpasso", "Clacson"],
  ["Amici Miei", "Bicchiere"],
  ["Un Sacco Bello", "Valigia"],
  ["Non ci Resta che Piangere", "Cavallo"],
  ["Il Marchese del Grillo", "Carrozza"],
  ["Fantozzi", "Bocia"],
  ["Bianco Rosso e Verdone", "Autobus"],
  ["Ecce Bombo", "Motorino"],
  ["Caro Diario", "Vespa"],
  ["Mediterraneo", "Isola"],
  ["La Vita è Bella Benigni", "Chiave"],
  ["Il Postino di Troisi", "Poesia"],
  ["Nuovomondo", "Nave"],
  ["Io non ho Paura", "Grano"],
  ["Gomorra", "Motorino"],
  ["Romanzo Criminale", "Piscina"],
  ["Suburra", "Statua"],
  ["La Grande Guerra", "Trincea"],
];
