export const CLASSICHE: [string, string][] = [
  ["Ombrello", "Oggetto"],
  ["Specchio", "Casa"],
  ["Chiave", "Tasca"],
  ["Sedia", "Casa"],
  ["Orologio", "Tempo"],
  ["Scala", "Movimento"],
  ["Letto", "Notte"],
  ["Semaforo", "Strada"],
  ["Valigia", "Partenza"],
  ["Candela", "Luce"],
  ["Telefono", "Contatto"],
  ["Frigorifero", "Cucina"],
  ["Cuscino", "Notte"],
  ["Bicicletta", "Strada"],
  ["Porta", "Casa"],
  ["Finestra", "Casa"],
  ["Coltello", "Cucina"],
  ["Sapone", "Bagno"],
  ["Zaino", "Spalle"],
  ["Fotografia", "Ricordo"],
];
