export const CLASSICHE: [string, string][] = [
  ["Ombrello", "Pioggia dimenticata"],
  ["Specchio", "Verità muta"],
  ["Chiave", "Tasca ansiosa"],
  ["Sedia", "Attesa"],
  ["Orologio", "Ansia circolare"],
  ["Scala", "Salita"],
  ["Letto", "Rifugio"],
  ["Semaforo", "Impazienza"],
  ["Valigia", "Partenza"],
  ["Candela", "Buio dolce"],
  ["Telefono", "Squillo"],
  ["Frigorifero", "Ronzio notturno"],
  ["Cuscino", "Segreti"],
  ["Bicicletta", "Equilibrio"],
  ["Porta", "Soglia"],
  ["Finestra", "Sguardo lungo"],
  ["Coltello", "Prudenza"],
  ["Sapone", "Scivoloso"],
  ["Zaino", "Spalle pesanti"],
  ["Fotografia", "Ricordo fermo"],
];
