export const CLASSICHE: [string, string][] = [
  ["Pizza", "Domenica sera"],
  ["Dentista", "Poltrona"],
  ["Ombrello", "Dimenticato"],
  ["Autobus", "Ritardo"],
  ["Panettone", "Dicembre"],
  ["Calcio", "Domenica"],
  ["Spiaggia", "Asciugamano"],
  ["Montagna", "Rifugio"],
  ["Matrimonio", "Confetti"],
  ["Compleanno", "Candeline"],
  ["Carnevale", "Coriandoli"],
  ["Natale", "Luci"],
  ["Pasqua", "Uovo"],
  ["Ferragosto", "Traffico"],
  ["Capodanno", "Botti"],
  ["Barbiere", "Forbici"],
  ["Sarto", "Metro"],
  ["Idraulico", "Chiave inglese"],
  ["Elettricista", "Cavo"],
  ["Muratore", "Cazzuola"],
  ["Panettiere", "Alba"],
  ["Macellaio", "Grembiule"],
  ["Pescivendolo", "Ghiaccio"],
  ["Falegname", "Segatura"],
  ["Fabbro", "Scintille"],
  ["Postino", "Bicicletta"],
  ["Vigile", "Fischietto"],
  ["Maestra", "Lavagna"],
  ["Infermiere", "Turno"],
  ["Avvocato", "Toga"],
  ["Notaio", "Timbro"],
  ["Farmacista", "Camice"],
  ["Giardiniere", "Potatura"],
  ["Cameriere", "Vassoio"],
  ["Cuoco", "Grembiule"],
  ["Autista", "Volante"],
  ["Pilota", "Cielo"],
  ["Marinaio", "Onda"],
  ["Contadino", "Trattore"],
  ["Pastore", "Gregge"],
  ["Sci", "Neve"],
  ["Nuoto", "Cuffia"],
  ["Tennis", "Rete"],
  ["Basket", "Canestro"],
  ["Pallavolo", "Bagher"],
  ["Ciclismo", "Salita"],
  ["Boxe", "Guantoni"],
  ["Judo", "Cintura"],
  ["Scherma", "Maschera"],
  ["Atletica", "Pista"],
  ["Golf", "Buca"],
  ["Rugby", "Meta"],
  ["Pallanuoto", "Piscina"],
  ["Vela", "Vento"],
  ["Canottaggio", "Remi"],
  ["Equitazione", "Sella"],
  ["Bowling", "Corsia"],
  ["Biliardo", "Stecca"],
  ["Freccette", "Bersaglio"],
  ["Scacchi", "Silenzio"],
  ["Poker", "Bluff"],
  ["Monopoli", "Fallimento"],
  ["Puzzle", "Pazienza"],
  ["Nascondino", "Conta"],
  ["Campana", "Gesso"],
  ["Altalena", "Cortile"],
  ["Scivolo", "Cortile"],
  ["Aquilone", "Vento"],
  ["Bicicletta", "Catena"],
  ["Motorino", "Casco"],
  ["Automobile", "Benzina"],
  ["Treno", "Binario"],
  ["Aereo", "Decollo"],
  ["Nave", "Porto"],
  ["Metropolitana", "Tornello"],
  ["Taxi", "Tariffa"],
  ["Semaforo", "Rosso"],
  ["Parcheggio", "Multa"],
  ["Autostrada", "Pedaggio"],
  ["Benzinaio", "Rifornimento"],
  ["Officina", "Ruggine"],
  ["Supermercato", "Carrello"],
  ["Mercato", "Bancarella"],
  ["Farmacia", "Croce verde"],
  ["Biblioteca", "Silenzio"],
  ["Museo", "Custode"],
  ["Cinema", "Popcorn"],
  ["Teatro", "Sipario"],
  ["Concerto", "Bis"],
  ["Discoteca", "Buttafuori"],
  ["Bar", "Bancone"],
  ["Ristorante", "Conto"],
  ["Trattoria", "Menu del giorno"],
  ["Pizzeria", "Forno a legna"],
  ["Gelateria", "Coppetta"],
  ["Panetteria", "Profumo"],
  ["Pasticceria", "Vetrina"],
  ["Macelleria", "Grembiule"],
  ["Fioraio", "Vetrina"],
  ["Edicola", "Quotidiano"],
  ["Tabaccheria", "Gratta e vinci"],
  ["Lavanderia", "Detersivo"],
  ["Parrucchiere", "Specchio"],
  ["Estetista", "Crema"],
  ["Palestra", "Sudore"],
  ["Piscina", "Cloro"],
  ["Sauna", "Vapore"],
  ["Ospedale", "Corsia"],
  ["Scuola", "Campanella"],
  ["Università", "Matricola"],
  ["Asilo", "Pisolino"],
  ["Chiesa", "Campane"],
  ["Municipio", "Sindaco"],
  ["Stazione", "Binario"],
  ["Aeroporto", "Bagaglio"],
  ["Porto", "Gabbiani"],
  ["Faro", "Costa"],
  ["Deserto", "Sabbia"],
  ["Foresta", "Sentiero"],
  ["Vulcano", "Lava"],
  ["Cascata", "Spruzzi"],
  ["Grotta", "Eco"],
  ["Isola", "Barca"],
  ["Lago", "Riva"],
  ["Fiume", "Corrente"],
  ["Mare", "Onde"],
  ["Neve", "Fiocco"],
  ["Pioggia", "Impermeabile"],
  ["Temporale", "Fulmine"],
  ["Arcobaleno", "Pentola d'oro"],
  ["Sole", "Occhiali"],
  ["Luna", "Notte"],
  ["Stelle", "Desiderio"],
  ["Vento", "Foglie"],
  ["Fumo", "Camino"],
  ["Fuoco", "Falò"],
  ["Terremoto", "Scosse"],
  ["Sciopero", "Cartelli"],
  ["Traffico", "Clacson"],
  ["Coda", "Pazienza"],
  ["Ferie", "Valigia"],
  ["Vacanza", "Cartolina"],
  ["Campeggio", "Tenda"],
  ["Zaino", "Spalle"],
  ["Valigia", "Etichetta"],
  ["Passaporto", "Timbro"],
  ["Visto", "Ambasciata"],
  ["Dogana", "Controllo"],
  ["Souvenir", "Calamita"],
  ["Cartolina", "Francobollo"],
  ["Lettera", "Busta"],
  ["Pacco", "Nastro"],
  ["Regalo", "Fiocco"],
  ["Sorpresa", "Torta"],
  ["Festa", "Palloncini"],
  ["Invito", "Busta"],
  ["Brindisi", "Bicchieri"],
  ["Torta", "Candeline"],
  ["Buffet", "Fila"],
  ["Karaoke", "Microfono"],
  ["Ballo", "Pista"],
  ["Musica", "Ritmo"],
  ["Chitarra", "Corde"],
  ["Pianoforte", "Tasti"],
  ["Batteria", "Bacchette"],
  ["Violino", "Archetto"],
  ["Orchestra", "Direttore"],
  ["Coro", "Voci"],
  ["Radio", "Antenna"],
  ["Televisione", "Telecomando"],
  ["Giornale", "Inchiostro"],
  ["Rivista", "Copertina"],
  ["Libro", "Polvere"],
  ["Fumetto", "Nuvoletta"],
  ["Diario", "Lucchetto"],
  ["Agenda", "Appunti"],
  ["Calendario", "Data"],
  ["Orologio", "Lancette"],
  ["Sveglia", "Rimando"],
  ["Specchio", "Riflesso"],
  ["Sedia", "Gambe"],
  ["Tavolo", "Tovaglia"],
  ["Divano", "Cuscini"],
  ["Letto", "Lenzuola"],
  ["Armadio", "Grucce"],
  ["Cassetto", "Ordine"],
  ["Finestra", "Tenda"],
  ["Porta", "Chiave"],
  ["Scala", "Corrimano"],
  ["Ascensore", "Pulsanti"],
  ["Balcone", "Panni stesi"],
  ["Terrazza", "Piante"],
  ["Giardino", "Innaffiatoio"],
  ["Orto", "Zappa"],
  ["Aiuola", "Fiori"],
  ["Prato", "Erba"],
  ["Recinto", "Confine"],
  ["Cancello", "Campanello"],
  ["Cortile", "Giochi"],
  ["Soffitta", "Polvere"],
  ["Cantina", "Ragnatele"],
  ["Garage", "Attrezzi"],
  ["Camino", "Legna"],
  ["Cucina", "Fornelli"],
  ["Frigorifero", "Calamite"],
  ["Lavastoviglie", "Detersivo"],
  ["Forno", "Guanti"],
  ["Lavatrice", "Bucato"],
  ["Aspirapolvere", "Rumore"],
  ["Ferro da stiro", "Vapore"],
  ["Scopa", "Manico"],
  ["Secchio", "Straccio"],
  ["Sapone", "Bolle"],
  ["Spazzolino", "Bagno"],
  ["Asciugamano", "Gancio"],
  ["Doccia", "Getto"],
  ["Vasca", "Bolle"],
  ["Rubinetto", "Goccia"],
  ["Bilancia", "Numeri"],
  ["Tostapane", "Fette"],
  ["Bollitore", "Vapore"],
  ["Macchina del caffè", "Capsule"],
  ["Tagliere", "Coltello"],
  ["Pelaverdure", "Carote"],
  ["Colino", "Pasta"],
  ["Spumante", "Brindisi"],
  ["Cavatappi", "Sughero"],
  ["Apriscatole", "Lattina"],
  ["Grattugia", "Formaggio"],
  ["Mortaio", "Pestello"],
  ["Teglia", "Forno"],
  ["Pirofila", "Sformato"],
  ["Tegame", "Saltare"],
  ["Padella", "Soffriggere"],
  ["Coperchio", "Vapore"],
  ["Mestolo", "Brodo"],
  ["Schiumarola", "Frittura"],
  ["Pinza da cucina", "Grigliata"],
  ["Cucchiaio di legno", "Sugo"],
  ["Frullatore", "Frappè"],
  ["Robot da cucina", "Impasto"],
  ["Tritatutto", "Aglio"],
  ["Spremiagrumi", "Arance"],
  ["Ghiacciaia", "Cubetti"],
  ["Thermos", "Caldo"],
  ["Borraccia", "Palestra"],
  ["Tazza", "Manico"],
  ["Bicchiere", "Bordo"],
  ["Caraffa", "Acqua"],
  ["Brocca", "Latte"],
  ["Centrotavola", "Fiori"],
  ["Tovagliolo", "Grembiule"],
  ["Sottopiatto", "Apparecchiatura"],
  ["Candelabro", "Cena"],
  ["Vaso", "Fiori"],
  ["Portaombrelli", "Ingresso"],
  ["Appendiabiti", "Cappotto"],
  ["Scarpiera", "Profumo"],
  ["Cassettiera", "Calzini"],
  ["Comodino", "Lampada"],
  ["Testiera", "Cuscini"],
  ["Copriletto", "Trapunta"],
  ["Tappeto", "Peli"],
  ["Tenda", "Sole"],
  ["Zanzariera", "Finestra"],
  ["Tapparella", "Buco"],
  ["Persiana", "Stecca"],
  ["Grata", "Sicurezza"],
  ["Campanello", "Visita"],
  ["Citofono", "Basso"],
  ["Targa", "Cognome"],
  ["Cassetta della posta", "Rivista"],
  ["Pompa", "Gonfiare"],
  ["Estintore", "Sicurezza"],
  ["Cassetta degli attrezzi", "Martello"],
  ["Scala a pioli", "Soffitta"],
  ["Carriola", "Cantiere"],
  ["Vanga", "Buchi"],
  ["Rastrello", "Foglie"],
  ["Forbici da potatura", "Rose"],
  ["Annaffiatoio", "Piante"],
  ["Vaso da fiori", "Balcone"],
  ["Tubo da giardino", "Acqua"],
  ["Ombrellone", "Spiaggia"],
  ["Sdraio", "Mare"],
  ["Materassino", "Gonfiabile"],
  ["Gavetta", "Campeggio"],
  ["Torcia", "Buio"],
  ["Lampada frontale", "Sentiero"],
  ["Fischietto", "SOS"],
  ["Bussola", "Nord"],
  ["Binocolo", "Uccelli"],
  ["Cannocchiale", "Teatro"],
  ["Lente d'ingrandimento", "Impronte"],
  ["Microscopio", "Cellule"],
  ["Telescopio", "Stelle"],
  ["Planisfero", "Continenti"],
  ["Atlante", "Strade"],
  ["Guida telefonica", "Numeri"],
  ["Dizionario", "Definizioni"],
  ["Enciclopedia", "Volumi"],
  ["Manuale", "Istruzioni"],
  ["Registro", "Voti"],
  ["Quaderno", "Righe"],
  ["Astuccio", "Matite"],
  ["Gomma", "Sbagli"],
  ["Temperamatite", "Punta"],
  ["Penna stilografica", "Inchiostro"],
  ["Evidenziatore", "Giallo"],
  ["Pennarello", "Disegno"],
  ["Matita colorata", "Arcobaleno"],
  ["Pastello", "Gesso"],
  ["Acquerello", "Tavolozza"],
  ["Cavalletto", "Pittore"],
  ["Tela", "Olio"],
  ["Pennello", "Setole"],
  ["Spatola", "Colore"],
  ["Colla vinilica", "Carta"],
  ["Forbici da carta", "Ritagli"],
  ["Cucitrice", "Fogli"],
  ["Graffetta", "Raccoglitore"],
  ["Raccoglitore ad anelli", "Appunti"],
  ["Cartellina", "Documenti"],
  ["Busta da lettera", "Francobollo"],
  ["Cartolina d'auguri", "Pieghevole"],
  ["Nastro adesivo", "Scatola"],
  ["Spago", "Pacchi"],
  ["Corda", "Nodo"],
  ["Catena", "Lucchetto"],
  ["Lucchetto", "Chiave"],
  ["Chiave inglese", "Bulloni"],
  ["Cacciavite", "Viti"],
  ["Trapano", "Muro"],
  ["Martello", "Chiodi"],
  ["Tenaglia", "Pinza"],
  ["Metro a nastro", "Misure"],
  ["Livella", "Bolla"],
  ["Scotch", "Trasparente"],
  ["Vernice", "Pennello"],
  ["Smalto", "Unghie"],
  ["Lucido", "Scarpe"],
  ["Spazzola per capelli", "Nodi"],
  ["Pettine", "Riga"],
  ["Fermaglio", "Capelli"],
  ["Elastico", "Coda"],
  ["Molletta", "Bucato"],
  ["Stendibiancheria", "Panni"],
  ["Cesta", "Bucato"],
  ["Detersivo per piatti", "Sgrassare"],
  ["Ammorbidente", "Profumo"],
  ["Candeggina", "Macchie"],
  ["Sgrassatore", "Cucina"],
  ["Spugna", "Schiuma"],
  ["Panno in microfibra", "Polvere"],
  ["Scopino", "Water"],
  ["Deodorante per ambienti", "Spray"],
  ["Profumatore", "Auto"],
  ["Candela profumata", "Rilassante"],
  ["Incenso", "Fumo"],
  ["Diffusore", "Oli essenziali"],
  ["Cuscino", "Sonno"],
  ["Plaid", "Divano"],
  ["Tappetino", "Yoga"],
  ["Palla da ginnastica", "Equilibrio"],
  ["Elastico da palestra", "Resistenza"],
  ["Manubrio", "Pesi"],
  ["Kettlebell", "Swing"],
  ["Tappetino da corsa", "Casa"],
  ["Cyclette", "Pedali"],
  ["Ellittica", "Braccia"],
  ["Rullo per massaggi", "Muscoli"],
  ["Fascia elastica", "Riabilitazione"],
  ["Cerotto", "Ginocchio"],
  ["Termometro", "Febbre"],
  ["Sfigmomanometro", "Pressione"],
  ["Pillola", "Acqua"],
  ["Sciroppo", "Cucchiaio"],
  ["Bustina", "Tisana"],
  ["Bicchiere dosatore", "Medicinale"],
  ["Mascherina", "Virus"],
  ["Guanti monouso", "Igiene"],
  ["Gel igienizzante", "Mani"],
  ["Crema idratante", "Viso"],
  ["Dentifricio", "Pulizia"],
  ["Collutorio", "Alito"],
  ["Rasoio", "Barba"],
  ["Schiuma da barba", "Pennello"],
  ["Dopobarba", "Profumo"],
  ["Cotton fioc", "Orecchie"],
  ["Pinzetta", "Sopracciglia"],
  ["Lima", "Unghie"],
  ["Tagliaunghie", "Igiene"],
  ["Ombretto", "Palpebra"],
  ["Mascara", "Ciglia"],
  ["Rossetto", "Bacio"],
  ["Cipria", "Opacizzare"],
  ["Fondotinta", "Uniformare"],
  ["Fard", "Guance"],
  ["Matita per occhi", "Sguardo"],
  ["Profumo", "Polso"],
  ["Deodorante", "Ascelle"],
  ["Talismano", "Fortuna"],
  ["Portafortuna", "Corno"],
  ["Quadrifoglio", "Fortuna"],
  ["Ferro di cavallo", "Appeso"],
  ["Girasole", "Semi"],
  ["Papavero", "Rosso"],
  ["Margherita", "Petali"],
  ["Rosa", "Spine"],
  ["Tulipano", "Olanda"],
  ["Orchidea", "Rara"],
  ["Cactus", "Spine"],
  ["Bonsai", "Giappone"],
  ["Bambù", "Panda"],
  ["Edera", "Muro"],
  ["Quercia", "Ghianda"],
  ["Pino", "Pigne"],
  ["Abete", "Natale"],
  ["Palma", "Tropicale"],
  ["Olivo", "Olio"],
  ["Vite", "Uva"],
  ["Limone", "Acido"],
  ["Arancia", "Spremuta"],
  ["Mela", "Croccante"],
  ["Pera", "Forma"],
  ["Banana", "Gialla"],
  ["Ciliegia", "Rosso"],
  ["Fragola", "Puntini"],
  ["Lampone", "Bosco"],
  ["Mirtillo", "Torta"],
  ["Pesca", "Peluria"],
  ["Albicocca", "Giallo"],
  ["Prugna", "Digestione"],
  ["Fico", "D'India"],
  ["Kiwi", "Peloso"],
  ["Ananas", "Tropicale"],
  ["Cocco", "Palma"],
  ["Melograno", "Grana"],
  ["Anguria", "Estate"],
  ["Melone", "Dolce"],
  ["Zucca", "Halloween"],
  ["Cetriolo", "Fresco"],
  ["Pomodoro", "Rosso"],
  ["Peperone", "Rosso"],
  ["Melanzana", "Viola"],
  ["Zucchina", "Verde"],
  ["Carciofo", "Foglie"],
  ["Broccolo", "Alberello"],
  ["Cavolfiore", "Bianco"],
  ["Spinacio", "Popeye"],
  ["Rucola", "Piccante"],
  ["Radicchio", "Amaro"],
  ["Finocchio", "Anice"],
  ["Porro", "Bianco"],
  ["Sedano", "Coste"],
  ["Asparago", "Piselli"],
  ["Fagiolino", "Verde"],
  ["Patata", "Frittura"],
  ["Cipolla", "Lacrime"],
  ["Aglio", "Alito"],
  ["Prezzemolo", "Trito"],
  ["Basilico", "Pesto"],
  ["Origano", "Pizza"],
  ["Rosmarino", "Agnello"],
  ["Salvia", "Burro"],
  ["Timo", "Provenza"],
  ["Zafferano", "Riso"],
  ["Curcuma", "Giallo"],
  ["Cannella", "Dolci"],
  ["Vaniglia", "Baccello"],
  ["Noce moscata", "Grattugiata"],
  ["Pepe nero", "Macinato"],
  ["Sale marino", "Cristalli"],
  ["Zucchero", "Dolce"],
  ["Miele", "Api"],
  ["Marmellata", "Fette"],
  ["Nutella", "Pane"],
  ["Burro", "Tartina"],
  ["Formaggio", "Grana"],
  ["Yogurt", "Colazione"],
  ["Uovo", "Guscio"],
  ["Bacon", "Colazione"],
  ["Prosciutto", "Crudo"],
  ["Salame", "Fette"],
  ["Mortadella", "Bologna"],
  ["Salsiccia", "Grigliata"],
  ["Wurstel", "Patatine"],
  ["Hamburger", "Panino"],
  ["Hot dog", "Senape"],
  ["Kebab", "Salsa"],
  ["Piadina", "Romagna"],
  ["Focaccia", "Liguria"],
  ["Croissant", "Francia"],
  ["Brioche", "Granita"],
  ["Ciambella", "Zucchero"],
  ["Muffin", "Mirtilli"],
  ["Brownie", "Cioccolato"],
  ["Tiramisù", "Savoiardi"],
  ["Cannolo", "Sicilia"],
  ["Pasticciotto", "Lecce"],
  ["Sfogliatella", "Napoli"],
  ["Babà", "Rum"],
  ["Panettone", "Milanese"],
  ["Colomba", "Pasqua"],
  ["Torta", "Compleanno"],
  ["Crostata", "Marmellata"],
  ["Biscotto", "Tè"],
  ["Cioccolatino", "Scatola"],
  ["Gelato", "Cono"],
  ["Sorbetto", "Limone"],
  ["Granita", "Sicilia"],
  ["Frappè", "Panna"],
  ["Smoothie", "Frutta"],
  ["Spremuta", "Arancia"],
  ["Caffè", "Tazzina"],
  ["Cappuccino", "Schiuma"],
  ["Espresso", "Macchina"],
  ["Americano", "Acqua"],
  ["Macchiato", "Goccia"],
  ["Latte macchiato", "Strati"],
  ["Tè", "Bustina"],
  ["Tisana", "Rilassante"],
  ["Camomilla", "Notte"],
  ["Infuso", "Erbe"],
  ["Birra", "Spina"],
  ["Vino", "Calice"],
  ["Prosecco", "Bollicine"],
  ["Champagne", "Francia"],
  ["Aperol", "Spritz"],
  ["Campari", "Bitter"],
  ["Negroni", "Arancio"],
  ["Mojito", "Menta"],
  ["Margarita", "Sale"],
  ["Caipirinha", "Lime"],
  ["Sangria", "Frutta"],
  ["Bloody Mary", "Sedano"],
  ["Whisky", "Torbato"],
  ["Rum", "Caraibi"],
  ["Vodka", "Ghiaccio"],
  ["Gin", "Tonic"],
  ["Tequila", "Limone"],
  ["Amaro", "Digestivo"],
  ["Limoncello", "Positano"],
  ["Grappa", "Vinaccia"],
  ["Sambuca", "Mosca"],
  ["Amaretto", "Mandorle"],
  ["Baileys", "Crema"],
  ["Coca-Cola", "Rosso"],
  ["Pepsi", "Blu"],
  ["Fanta", "Arancio"],
  ["Sprite", "Limone"],
  ["Acqua tonica", "Gin"],
  ["Aranciata", "Bolle"],
  ["Gazzosa", "Bollicine"],
  ["Cappello", "Ombra e riparo"],
  ["Cravatta", "Sotto il colletto"],
  ["Fontana", "Piazza del paese"],
  ["Lenzuolo", "Ora del sonno"],
  ["Moneta", "Resto del bar"],
  ["Ponte", "Sponda opposta"],
  ["Portafoglio", "Cuoio tascabile"],
  ["Quadro", "Chiodo alla parete"],
];
