export const FILM: [string, string][] = [
  ["Titanic", "Naufragio romantico"],
  ["Il Padrino", "Famiglia siciliana"],
  ["Matrix", "Realtà digitale"],
  ["Jurassic Park", "Isola preistorica"],
  ["Lo Squalo", "Nota bassa"],
  ["Shrek", "Palude verde"],
  ["Il Re Leone", "Savana"],
  ["Harry Potter", "Collegio magico"],
  ["Il Signore degli Anelli", "Cammino gioiello"],
  ["Ritorno al Futuro", "Auto veloce"],
  ["Rocky", "Scalinata"],
  ["La Vita è Bella", "Gioco tragico"],
  ["Frozen", "Ghiaccio cantato"],
  ["Avatar", "Blu alieno"],
  ["Star Wars", "Spade luminose"],
  ["Batman", "Notte mascherata"],
  ["Il Gladiatore", "Arena"],
  ["Forrest Gump", "Panchina corsa"],
  ["Pulp Fiction", "Valigetta"],
  ["Inception", "Sogni annidati"],
];
