export const FILM: [string, string][] = [
  ["Titanic", "Classico"],
  ["Il Padrino", "Classico"],
  ["Matrix", "Fantascienza"],
  ["Jurassic Park", "Avventura"],
  ["Lo Squalo", "Tensione"],
  ["Shrek", "Animazione"],
  ["Il Re Leone", "Animazione"],
  ["Harry Potter", "Saga"],
  ["Il Signore degli Anelli", "Saga"],
  ["Ritorno al Futuro", "Fantascienza"],
  ["Rocky", "Sport"],
  ["La Vita è Bella", "Italiano"],
  ["Frozen", "Animazione"],
  ["Avatar", "Fantascienza"],
  ["Star Wars", "Saga"],
  ["Batman", "Supereroi"],
  ["Il Gladiatore", "Storico"],
  ["Forrest Gump", "Classico"],
  ["Pulp Fiction", "Culto"],
  ["Inception", "Mente"],
];
