export const FILM: [string, string][] = [
  ["Titanic", "Ghiaccio"],
  ["Il Padrino", "Rispetto"],
  ["Star Wars", "Forza"],
  ["Pulp Fiction", "Orologio"],
  ["La Vita è Bella", "Gioco"],
  ["Lo Squalo", "Paura"],
  ["Ritorno al Futuro", "Tempo"],
  ["Matrix", "Scelta"],
  ["Forrest Gump", "Scatola"],
  ["Il Gladiatore", "Polvere"],
  ["Avatar", "Natura"],
  ["Psycho", "Albergo"],
  ["E.T.", "Casa"],
  ["Jurassic Park", "DNA"],
  ["Il Re Leone", "Ciclo"],
  ["Grease", "Pettine"],
  ["Shining", "Labirinto"],
  ["Rocky", "Sudore"],
  ["Harry Potter", "Cicatrice"],
  ["Il Signore degli Anelli", "Viaggio"],
  ["Amarcord", "Ricordo"],
  ["La Dolce Vita", "Fontana"],
  ["Alien", "Spazio"],
  ["Braveheart", "Libertà"],
  ["Toy Story", "Bambino"],
  ["Inception", "Trottola"],
  ["Interstellar", "Orologio"],
  ["Il Cavaliere Oscuro", "Caos"],
  ["Fight Club", "Regola"],
  ["Seven", "Peccato"],
  ["Arancia Meccanica", "Latte"],
  ["Taxi Driver", "Specchio"],
  ["Apocalypse Now", "Elicottero"],
  ["Scarface", "Montagna"],
  ["Blade Runner", "Pioggia"],
  ["Il Silenzio degli Innocenti", "Maschera"],
  ["Schindler's List", "Cappotto"],
  ["Full Metal Jacket", "Elmetto"],
  ["The Truman Show", "Barca"],
  ["Ghost", "Tornio"],
  ["Pretty Woman", "Collana"],
  ["Dirty Dancing", "Angolo"],
  ["Top Gun", "Occhiali"],
  ["Rambo", "Fascia"],
  ["Terminator", "Metallo"],
  ["Indiana Jones", "Frusta"],
  ["Die Hard", "Grattacielo"],
  ["Speed", "Autobus"],
  ["Men in Black", "Memoria"],
  ["Scream", "Telefono"],
  ["L'Esorcista", "Letto"],
  ["Nightmare", "Incubo"],
  ["Halloween", "Maschera"],
  ["Venerdì 13", "Lago"],
  ["Saw", "Enigma"],
  ["The Ring", "Pozzo"],
  ["Shrek", "Palude"],
  ["Frozen", "Ghiaccio"],
  ["Madagascar", "Zoo"],
  ["Up", "Palloncini"],
  ["Nemo", "Barriera"],
  ["Monsters & Co.", "Porta"],
  ["Ratatouille", "Cucina"],
  ["Wall-E", "Spazzatura"],
  ["Cars", "Pista"],
  ["Gli Incredibili", "Famiglia"],
  ["La La Land", "Stelle"],
  ["Bohemian Rhapsody", "Palco"],
  ["Joker", "Trucco"],
  ["Parasite", "Seminterrato"],
  ["Django Unchained", "Sangue"],
  ["Kill Bill", "Spada"],
  ["Bastardi senza gloria", "Cinema"],
  ["The Hateful Eight", "Neve"],
  ["C'era una volta a... Hollywood", "Ranch"],
  ["Gran Torino", "Garage"],
  ["Million Dollar Baby", "Sgabello"],
  ["Mystic River", "Fiume"],
  ["American Beauty", "Petali"],
  ["The Departed", "Talpa"],
  ["Goodfellas", "Cucina"],
  ["Casino", "Luci"],
  ["The Wolf of Wall Street", "Yacht"],
  ["Snatch", "Diamante"],
  ["Trainspotting", "Gabinetto"],
  ["Requiem for a Dream", "Pupilla"],
  ["Black Swan", "Piume"],
  ["Whiplash", "Batteria"],
  ["Birdman", "Teatro"],
  ["The Revenant", "Orso"],
  ["Mad Max: Fury Road", "Sabbia"],
  ["Gravity", "Vuoto"],
  ["1917", "Trincea"],
  ["Dunkirk", "Spiaggia"],
  ["Oppenheimer", "Esplosione"],
  ["Barbie", "Rosa"],
  ["Dune", "Vermi"],
  ["Tenet", "Inversione"],
  ["Roma", "Mare"],
  ["La Grande Bellezza", "Terrazza"],
  ["Il Postino", "Bicicletta"],
  ["Cinema Paradiso", "Bacio"],
  ["Mediterraneo", "Isola"],
  ["La Meglio Gioventù", "Storia"],
  ["Gomorra", "Vele"],
  ["Romanzo Criminale", "Banda"],
  ["Suburra", "Pioggia"],
  ["Lo chiamavano Jeeg Robot", "Budino"],
  ["Dogman", "Gabbia"],
  ["Martin Eden", "Libri"],
  ["Il Traditore", "Aula"],
  ["L'Immortale", "Motoscafo"],
  ["Freaks Out", "Circo"],
  ["Rapito", "Chiesa"],
  ["Comandante", "Sommergibile"],
  ["Adagio", "Fumo"],
  ["C'è ancora domani", "Cortile"],
  ["Io Capitano", "Deserto"],
  ["Perfetti Sconosciuti", "Cena"],
  ["The Whale", "Divano"],
  ["Everything Everywhere All at Once", "Sasso"],
  ["Nomadland", "Furgone"],
  ["Green Book", "Mappa"],
  ["The Shape of Water", "Uovo"],
  ["Moonlight", "Spiaggia"],
  ["Spotlight", "Giornale"],
  ["12 anni schiavo", "Cotone"],
  ["Argo", "Aereo"],
  ["The Artist", "Silenzio"],
  ["Il discorso del re", "Microfono"],
  ["The Hurt Locker", "Cavo"],
  ["Slumdog Millionaire", "Quiz"],
  ["Non è un paese per vecchi", "Moneta"],
  ["Crash", "Incrocio"],
  ["A Beautiful Mind", "Lavagna"],
  ["Shakespeare in Love", "Penna"],
  ["Unforgiven", "Pioggia"],
  ["Dances with Wolves", "Lupo"],
  ["Driving Miss Daisy", "Auto"],
  ["Rain Man", "Carte"],
  ["The Last Emperor", "Mura"],
  ["Platoon", "Giungla"],
  ["Out of Africa", "Aereo"],
  ["Amadeus", "Parrucca"],
  ["Terms of Endearment", "Ospedale"],
  ["Gandhi", "Sale"],
  ["Chariots of Fire", "Spiaggia"],
  ["Ordinary People", "Tavola"],
  ["Kramer vs. Kramer", "Toast"],
  ["The Deer Hunter", "Roulette"],
  ["Annie Hall", "Cravatta"],
  ["One Flew Over the Cuckoo's Nest", "Cuscino"],
  ["The Sting", "Naso"],
  ["Cabaret", "Sedia"],
  ["The French Connection", "Treno"],
  ["Patton", "Bandiera"],
  ["Midnight Cowboy", "Marciapiede"],
  ["Oliver!", "Zuppa"],
  ["In the Heat of the Night", "Stazione"],
  ["A Man for All Seasons", "Fiume"],
  ["The Sound of Music", "Montagna"],
  ["My Fair Lady", "Ippodromo"],
  ["Tom Jones", "Cena"],
  ["Lawrence of Arabia", "Sabbia"],
  ["West Side Story", "Scale"],
  ["The Apartment", "Scolapasta"],
  ["Ben-Hur", "Auriga"],
  ["Gigi", "Parco"],
  ["The Bridge on the River Kwai", "Ponte"],
  ["Around the World in 80 Days", "Mongolfiera"],
  ["Marty", "Macelleria"],
  ["On the Waterfront", "Porto"],
  ["From Here to Eternity", "Onde"],
  ["The Greatest Show on Earth", "Treno"],
  ["An American in Paris", "Pittura"],
  ["All About Eve", "Premio"],
  ["All the King's Men", "Comizio"],
  ["Hamlet", "Teschio"],
  ["Gentleman's Agreement", "Ufficio"],
  ["The Best Years of Our Lives", "Aeroporto"],
  ["The Lost Weekend", "Bottiglia"],
  ["Going My Way", "Chiesa"],
  ["Mamma ho perso l'aereo", "Trappola"],
  ["Il Grinch", "Natale"],
  ["Mrs. Doubtfire", "Parrucca"],
  ["Sister Act", "Convento"],
  ["Una notte da leoni", "Tigre"],
  ["Zoolander", "Sguardo"],
  ["Ace Ventura", "Animale"],
  ["The Mask", "Faccia"],
  ["Austin Powers", "Spia"],
  ["Scary Movie", "Maschera"],
  ["American Pie", "Torta"],
  ["Borat", "Costume"],
  ["Ghostbusters", "Zaino"],
  ["I Goonies", "Mappa"],
  ["Gremlins", "Acqua"],
  ["Edward mani di forbice", "Ghiaccio"],
  ["Beetlejuice", "Strisce"],
  ["Il quinto elemento", "Pietra"]
];
