export const GEOGRAFIA: [string, string][] = [
  ["Italia", "Nazione europea"],
  ["Francia", "Nazione europea"],
  ["Germania", "Nazione europea"],
  ["Spagna", "Nazione europea"],
  ["Giappone", "Nazione asiatica"],
  ["Brasile", "Nazione sudamericana"],
  ["Stati Uniti", "Nazione nordamericana"],
  ["Cina", "Nazione asiatica"],
  ["India", "Nazione asiatica"],
  ["Egitto", "Nazione africana"],
  ["Russia", "Nazione euroasiatica"],
  ["Regno Unito", "Nazione europea"],
  ["Australia", "Nazione oceanica"],
  ["Canada", "Nazione nordamericana"],
  ["Messico", "Nazione nordamericana"],
  ["Grecia", "Nazione europea"],
  ["Turchia", "Nazione euroasiatica"],
  ["Olanda", "Nazione europea"],
  ["Svizzera", "Nazione europea"],
  ["Austria", "Nazione europea"],
  ["Portogallo", "Nazione europea"],
  ["Svezia", "Nazione europea"],
  ["Norvegia", "Nazione europea"],
  ["Danimarca", "Nazione europea"],
  ["Irlanda", "Nazione europea"],
  ["Belgio", "Nazione europea"],
  ["Polonia", "Nazione europea"],
  ["Ungheria", "Nazione europea"],
  ["Repubblica Ceca", "Nazione europea"],
  ["Romania", "Nazione europea"],
  ["Argentina", "Nazione sudamericana"],
  ["Cile", "Nazione sudamericana"],
  ["Perù", "Nazione sudamericana"],
  ["Colombia", "Nazione sudamericana"],
  ["Sudafrica", "Nazione africana"],
  ["Marocco", "Nazione africana"],
  ["Tunisia", "Nazione africana"],
  ["Kenya", "Nazione africana"],
  ["Thailandia", "Nazione asiatica"],
  ["Vietnam", "Nazione asiatica"],
  ["Corea del Sud", "Nazione asiatica"],
  ["Indonesia", "Nazione asiatica"],
  ["Nuova Zelanda", "Nazione oceanica"],
  ["Islanda", "Nazione europea"],
  ["Cuba", "Nazione caraibica"],
  ["Giamaica", "Nazione caraibica"],
  ["Madagascar", "Nazione africana"],
  ["Israele", "Nazione mediorientale"],
  ["Arabia Saudita", "Nazione mediorientale"],
  ["Emirati Arabi", "Nazione mediorientale"],
  ["Roma", "Città capitale"],
  ["Parigi", "Città capitale"],
  ["Londra", "Città capitale"],
  ["Berlino", "Città capitale"],
  ["Madrid", "Città capitale"],
  ["Lisbona", "Città capitale"],
  ["Atene", "Città capitale"],
  ["Vienna", "Città capitale"],
  ["Praga", "Città capitale"],
  ["Varsavia", "Città capitale"],
  ["Budapest", "Città capitale"],
  ["Amsterdam", "Città capitale"],
  ["Bruxelles", "Città capitale"],
  ["Stoccolma", "Città capitale"],
  ["Oslo", "Città capitale"],
  ["Copenaghen", "Città capitale"],
  ["Helsinki", "Città capitale"],
  ["Dublino", "Città capitale"],
  ["Mosca", "Città capitale"],
  ["Tokyo", "Città capitale"],
  ["Pechino", "Città capitale"],
  ["Seul", "Città capitale"],
  ["Bangkok", "Città capitale"],
  ["Nuova Delhi", "Città capitale"],
  ["Giacarta", "Città capitale"],
  ["Sidney", "Città oceanica"],
  ["Il Cairo", "Città capitale"],
  ["Nairobi", "Città capitale"],
  ["Città del Capo", "Metropoli africana"],
  ["New York", "Città americana"],
  ["Washington", "Città capitale"],
  ["Los Angeles", "Città americana"],
  ["Chicago", "Città americana"],
  ["Miami", "Città americana"],
  ["San Francisco", "Città americana"],
  ["Toronto", "Città canadese"],
  ["Città del Messico", "Capitale latinoamericana"],
  ["Rio de Janeiro", "Città sudamericana"],
  ["Buenos Aires", "Città capitale"],
  ["Lima", "Città capitale"],
  ["Bogotà", "Città capitale"],
  ["Santiago", "Città capitale"],
  ["Gerusalemme", "Città mediorientale"],
  ["Dubai", "Città mediorientale"],
  ["Singapore", "Città-stato asiatica"],
  ["Hong Kong", "Città asiatica"],
  ["Milano", "Città italiana"],
  ["Venezia", "Città italiana"],
  ["Firenze", "Città italiana"],
  ["Napoli", "Città italiana"],
  ["Torino", "Città italiana"],
  ["Genova", "Città italiana"],
  ["Palermo", "Città italiana"],
  ["Bari", "Città italiana"],
  ["Bologna", "Città italiana"],
  ["Verona", "Città italiana"],
  ["Pisa", "Città italiana"],
  ["Siena", "Città italiana"],
  ["Catania", "Città italiana"],
  ["Messina", "Città italiana"],
  ["Trieste", "Città italiana"],
  ["Padova", "Città italiana"],
  ["Brescia", "Città italiana"],
  ["Parma", "Città italiana"],
  ["Modena", "Città italiana"],
  ["Reggio Calabria", "Città italiana"],
  ["Cagliari", "Città italiana"],
  ["Perugia", "Città italiana"],
  ["Trento", "Città italiana"],
  ["Bolzano", "Città italiana"],
  ["Potenza", "Città italiana"],
  ["Ancona", "Città italiana"],
  ["L'Aquila", "Città italiana"],
  ["Campobasso", "Città italiana"],
  ["Catanzaro", "Città italiana"],
  ["Po", "Fiume italiano"],
  ["Tevere", "Fiume italiano"],
  ["Arno", "Fiume italiano"],
  ["Adige", "Fiume italiano"],
  ["Ticino", "Fiume italiano"],
  ["Nilo", "Fiume africano"],
  ["Rio delle Amazzoni", "Fiume sudamericano"],
  ["Mississippi", "Fiume americano"],
  ["Gange", "Fiume asiatico"],
  ["Danubio", "Fiume europeo"],
  ["Reno", "Fiume europeo"],
  ["Tamigi", "Fiume europeo"],
  ["Senna", "Fiume europeo"],
  ["Volga", "Fiume europeo"],
  ["Mekong", "Fiume asiatico"],
  ["Everest", "Monte asiatico"],
  ["K2", "Monte asiatico"],
  ["Monte Bianco", "Cima alpina"],
  ["Cervino", "Monte alpino"],
  ["Gran Sasso", "Monte appenninico"],
  ["Etna", "Monte vulcanico"],
  ["Vesuvio", "Monte vulcanico"],
  ["Kilimangiaro", "Monte africano"],
  ["Fuji", "Monte giapponese"],
  ["Ande", "Catena montuosa"],
  ["Alpi", "Catena montuosa"],
  ["Appennini", "Catena montuosa"],
  ["Himalaya", "Catena montuosa"],
  ["Pirenei", "Catena montuosa"],
  ["Urali", "Catena montuosa"],
  ["Sicilia", "Isola italiana"],
  ["Sardegna", "Isola italiana"],
  ["Corsica", "Isola francese"],
  ["Elba", "Isola italiana"],
  ["Capri", "Isola italiana"],
  ["Ischia", "Isola italiana"],
  ["Pantelleria", "Isola italiana"],
  ["Lampedusa", "Isola italiana"],
  ["Madagascar", "Isola africana"],
  ["Groenlandia", "Isola artica"],
  ["Australia", "Deserto oceanico"],
  ["Nuova Guinea", "Isola oceanica"],
  ["Borneo", "Isola asiatica"],
  ["Sumatra", "Isola asiatica"],
  ["Giava", "Isola asiatica"],
  ["Taiwan", "Isola asiatica"],
  ["Sri Lanka", "Isola asiatica"],
  ["Cipro", "Isola mediterranea"],
  ["Malta", "Isola mediterranea"],
  ["Creta", "Isola greca"],
  ["Rodi", "Isola greca"],
  ["Santorini", "Isola greca"],
  ["Mykonos", "Isola greca"],
  ["Ibiza", "Isola spagnola"],
  ["Maiorca", "Isola spagnola"],
  ["Canarie", "Arcipelago spagnolo"],
  ["Azzorre", "Arcipelago portoghese"],
  ["Hawaii", "Arcipelago americano"],
  ["Galapagos", "Arcipelago sudamericano"],
  ["Maldive", "Arcipelago asiatico"],
  ["Seychelles", "Arcipelago africano"],
  ["Mauritius", "Isola africana"],
  ["Bahamas", "Arcipelago caraibico"],
  ["Bermuda", "Isole atlantiche"],
  ["Tahiti", "Isola oceanica"],
  ["Mar Mediterraneo", "Mare europeo"],
  ["Oceano Atlantico", "Grande massa d'acqua"],
  ["Oceano Pacifico", "Grande massa d'acqua"],
  ["Oceano Indiano", "Grande massa d'acqua"],
  ["Mar Rosso", "Mare mediorientale"],
  ["Mar Morto", "Mare mediorientale"],
  ["Mar Nero", "Mare europeo"],
  ["Mar Baltico", "Mare europeo"],
  ["Deserto del Sahara", "Distesa arida africana"],
  ["Deserto del Gobi", "Distesa arida asiatica"],
];
