export const GEOGRAFIA: [string, string][] = [
  ["Italia", "Stivale"],
  ["Francia", "Baguette"],
  ["Germania", "Birra"],
  ["Spagna", "Toro"],
  ["Giappone", "Sushi"],
  ["Brasile", "Samba"],
  ["Stati Uniti", "Statua"],
  ["Cina", "Dragone"],
  ["India", "Spezie"],
  ["Egitto", "Piramide"],
  ["Russia", "Matrioska"],
  ["Regno Unito", "Corona"],
  ["Australia", "Canguro"],
  ["Canada", "Acero"],
  ["Messico", "Sombrero"],
  ["Grecia", "Tempio"],
  ["Turchia", "T\u00e8"],
  ["Olanda", "Mulino"],
  ["Svizzera", "Cioccolato"],
  ["Austria", "Valzer"],
  ["Portogallo", "Fado"],
  ["Svezia", "Mobili"],
  ["Norvegia", "Fiordi"],
  ["Danimarca", "Sirenetta"],
  ["Irlanda", "Trifoglio"],
  ["Belgio", "Patatine"],
  ["Polonia", "Piazza"],
  ["Ungheria", "Paprika"],
  ["Repubblica Ceca", "Cristallo"],
  ["Romania", "Castello"],
  ["Argentina", "Tango"],
  ["Cile", "Ande"],
  ["Per\u00f9", "Lama"],
  ["Colombia", "Caff\u00e8"],
  ["Sudafrica", "Diamanti"],
  ["Marocco", "Deserto"],
  ["Tunisia", "Mosaico"],
  ["Kenya", "Safari"],
  ["Thailandia", "Massaggio"],
  ["Vietnam", "Risaia"],
  ["Corea del Sud", "Tecnologia"],
  ["Indonesia", "Isole"],
  ["Nuova Zelanda", "Rugby"],
  ["Islanda", "Ghiaccio"],
  ["Cuba", "Sigaro"],
  ["Giamaica", "Reggae"],
  ["Madagascar", "Lemure"],
  ["Israele", "Muro"],
  ["Arabia Saudita", "Petrolio"],
  ["Emirati Arabi", "Grattacielo"],
  ["Roma", "Lupa"],
  ["Parigi", "Luce"],
  ["Londra", "Nebbia"],
  ["Berlino", "Muro"],
  ["Madrid", "Movida"],
  ["Lisbona", "Tram"],
  ["Atene", "Democrazia"],
  ["Vienna", "Opera"],
  ["Praga", "Ponte"],
  ["Varsavia", "Sirena"],
  ["Budapest", "Terme"],
  ["Amsterdam", "Canale"],
  ["Bruxelles", "Atomo"],
  ["Stoccolma", "Nobel"],
  ["Oslo", "Urlo"],
  ["Copenaghen", "Bicicletta"],
  ["Helsinki", "Sauna"],
  ["Dublino", "Boccale"],
  ["Mosca", "Piazza"],
  ["Tokyo", "Incrocio"],
  ["Pechino", "Citt\u00e0"],
  ["Seul", "Pop"],
  ["Bangkok", "Mercato"],
  ["Nuova Delhi", "Caos"],
  ["Giacarta", "Traffico"],
  ["Sidney", "Vela"],
  ["Il Cairo", "Nilo"],
  ["Nairobi", "Parco"],
  ["Citt\u00e0 del Capo", "Tavola"],
  ["New York", "Mela"],
  ["Washington", "Casa"],
  ["Los Angeles", "Cinema"],
  ["Chicago", "Vento"],
  ["Miami", "Spiaggia"],
  ["San Francisco", "Ponte"],
  ["Toronto", "Torre"],
  ["Citt\u00e0 del Messico", "Metropoli"],
  ["Rio de Janeiro", "Cristo"],
  ["Buenos Aires", "Balcone"],
  ["Lima", "Oceano"],
  ["Bogot\u00e0", "Montagna"],
  ["Santiago", "Vino"],
  ["Gerusalemme", "Religione"],
  ["Dubai", "Lusso"],
  ["Singapore", "Leone"],
  ["Hong Kong", "Porto"],
  ["Milano", "Duomo"],
  ["Venezia", "Gondola"],
  ["Firenze", "Culla"],
  ["Napoli", "Vesuvio"],
  ["Torino", "Mole"],
  ["Genova", "Lanterna"],
  ["Palermo", "Arancia"],
  ["Bari", "Levante"],
  ["Bologna", "Torre"],
  ["Verona", "Balcone"],
  ["Pisa", "Pendenza"],
  ["Siena", "Piazza"],
  ["Catania", "Lava"],
  ["Messina", "Stretto"],
  ["Trieste", "Vento"],
  ["Padova", "Santo"],
  ["Brescia", "Leona"],
  ["Parma", "Prosciutto"],
  ["Modena", "Aceto"],
  ["Reggio Calabria", "Bronzi"],
  ["Cagliari", "Fenicottero"],
  ["Perugia", "Bacio"],
  ["Trento", "Monti"],
  ["Bolzano", "Mele"],
  ["Potenza", "Scale"],
  ["Ancona", "Gomito"],
  ["L'Aquila", "Gran Sasso"],
  ["Campobasso", "Castello"],
  ["Catanzaro", "Ponte"],
  ["Po", "Pianura"],
  ["Tevere", "Storia"],
  ["Arno", "Ponte"],
  ["Adige", "Valle"],
  ["Ticino", "Parco"],
  ["Nilo", "Eternit\u00e0"],
  ["Rio delle Amazzoni", "Polmone"],
  ["Mississippi", "Jazz"],
  ["Gange", "Sacro"],
  ["Danubio", "Blu"],
  ["Reno", "Castelli"],
  ["Tamigi", "Ruota"],
  ["Senna", "Bateau"],
  ["Volga", "Steppa"],
  ["Mekong", "Delta"],
  ["Everest", "Tetto"],
  ["K2", "Sfida"],
  ["Monte Bianco", "Traforo"],
  ["Cervino", "Piramide"],
  ["Gran Sasso", "Corno"],
  ["Etna", "Fumo"],
  ["Vesuvio", "Cratere"],
  ["Kilimangiaro", "Neve"],
  ["Fuji", "Cono"],
  ["Ande", "Condor"],
  ["Alpi", "Sci"],
  ["Appennini", "Dorso"],
  ["Himalaya", "Silenzio"],
  ["Pirenei", "Confine"],
  ["Urali", "Divisione"],
  ["Sicilia", "Trinacria"],
  ["Sardegna", "Nuraghe"],
  ["Corsica", "Napoleone"],
  ["Elba", "Esilio"],
  ["Capri", "Faraglioni"],
  ["Ischia", "Fango"],
  ["Pantelleria", "Vento"],
  ["Lampedusa", "Porta"],
  ["Madagascar", "Baobab"],
  ["Groenlandia", "Bianco"],
  ["Australia", "Outback"],
  ["Nuova Guinea", "Trib\u00f9"],
  ["Borneo", "Giungla"],
  ["Sumatra", "Tigre"],
  ["Giava", "Vulcano"],
  ["Taiwan", "Lanterne"],
  ["Sri Lanka", "Cannella"],
  ["Cipro", "Afrodite"],
  ["Malta", "Cavalieri"],
  ["Creta", "Labirinto"],
  ["Rodi", "Colosso"],
  ["Santorini", "Tramonto"],
  ["Mykonos", "Mulini"],
  ["Ibiza", "Notte"],
  ["Maiorca", "Grotte"],
  ["Canarie", "Primavera"],
  ["Azzorre", "Anticiclone"],
  ["Hawaii", "Onde"],
  ["Galapagos", "Tartaruga"],
  ["Maldive", "Atollo"],
  ["Seychelles", "Palme"],
  ["Mauritius", "Dodo"],
  ["Bahamas", "Corallo"],
  ["Bermuda", "Triangolo"],
  ["Tahiti", "Perle"],
  ["Mar Mediterraneo", "Culla"],
  ["Oceano Atlantico", "Rotta"],
  ["Oceano Pacifico", "Abisso"],
  ["Oceano Indiano", "Spezie"],
  ["Mar Rosso", "Barriera"],
  ["Mar Morto", "Sale"],
  ["Mar Nero", "Crimea"],
  ["Mar Baltico", "Ambra"],
  ["Deserto del Sahara", "Duna"],
  ["Deserto del Gobi", "Scheletro"],
];
