export const GEOGRAFIA: [string, string][] = [
  ["Venezia", "Italia"],
  ["Roma", "Italia"],
  ["Napoli", "Italia"],
  ["Sicilia", "Italia"],
  ["Alpi", "Altezza"],
  ["Etna", "Natura"],
  ["Sahara", "Caldo"],
  ["Amazzonia", "Natura"],
  ["Everest", "Altezza"],
  ["Nilo", "Acqua"],
  ["Giappone", "Lontano"],
  ["Islanda", "Nord"],
  ["Australia", "Lontano"],
  ["Parigi", "Europa"],
  ["New York", "Grande città"],
  ["Deserto", "Ambiente"],
  ["Oceano", "Acqua"],
  ["Equatore", "Linea"],
  ["Groenlandia", "Nord"],
  ["Mappa", "Oggetto"],
];
