export const IDEE: [string, string][] = [
  ["Democrazia", "Urna"],
  ["Libertà", "Catene spezzate"],
  ["Uguaglianza", "Bilancia"],
  ["Rivoluzione", "Barricate"],
  ["Capitalismo", "Profitto"],
  ["Comunismo", "Falce"],
  ["Anarchia", "Nessun capo"],
  ["Femminismo", "Parità"],
  ["Ambientalismo", "Pianeta"],
  ["Nazionalismo", "Confini"],
  ["Populismo", "Piazza urlante"],
  ["Sciopero", "Braccia ferme"],
  ["Costituzione", "Carta fondativa"],
  ["Referendum", "Sì o no"],
  ["Propaganda", "Manifesti"],
  ["Censura", "Nero sopra"],
  ["Tasse", "Prelievo"],
  ["Welfare", "Rete sociale"],
  ["Corruzione", "Busta"],
  ["Utopia", "Sogno impossibile"],
];
