export const IDEE: [string, string][] = [
  ["Democrazia", "Urna"],
  ["Referendum", "Quesito"],
  ["Parlamento", "Aula"],
  ["Campagna elettorale", "Manifesto"],
  ["Sciopero", "Braccia"],
  ["Tasse", "Fisco"],
  ["Governo", "Palazzo"],
  ["Elezioni", "Seggio"],
  ["Senato", "Palazzo Madama"],
  ["Camera dei Deputati", "Montecitorio"],
  ["Quirinale", "Colle"],
  ["Scheda", "Matita"],
  ["Voto", "Preferenza"],
  ["Partito", "Simbolo"],
  ["Coalizione", "Alleanza"],
  ["Opposizione", "Minoranza"],
  ["Maggioranza", "Numeri"],
  ["Decreto", "Legge"],
  ["Costituzione", "Carta"],
  ["Libertà", "Catene"],
  ["Uguaglianza", "Bilancia"],
  ["Fratellanza", "Abbraccio"],
  ["Destra", "Fiamma"],
  ["Sinistra", "Pugno"],
  ["Centro", "Equilibrio"],
  ["Radicalismo", "Digiuno"],
  ["Socialismo", "Sole"],
  ["Comunismo", "Falce"],
  ["Capitalismo", "Borsa"],
  ["Liberalismo", "Mercato"],
  ["Anarchia", "Caos"],
  ["Monarchia", "Corona"],
  ["Repubblica", "Stella"],
  ["Stato", "Confini"],
  ["Nazione", "Bandiera"],
  ["Europa", "Stelle"],
  ["ONU", "Caschi blu"],
  ["NATO", "Patto"],
  ["Sindacato", "Tessera"],
  ["Pensioni", "Contributi"],
  ["Lavoro", "Primo Maggio"],
  ["Salute", "Ospedale"],
  ["Istruzione", "Scuola"],
  ["Ambiente", "Verde"],
  ["Pace", "Colomba"],
  ["Guerra", "Trincea"],
  ["Diplomazia", "Ambasciata"],
  ["Vertice", "G7"],
  ["Comizio", "Piazza"],
  ["Tribuna", "Televisione"],
  ["Sondaggio", "Percentuale"],
  ["Sondaggio all'uscita", "Proiezioni"],
  ["Sbarramento", "Soglia"],
  ["Quorum", "Metà"],
  ["Candidato", "Lista"],
  ["Leader", "Capo"],
  ["Portavoce", "Comunicato"],
  ["Ministro", "Portafoglio"],
  ["Sottosegretario", "Nomina"],
  ["Sindaco", "Fascia"],
  ["Assessore", "Giunta"],
  ["Consigliere", "Aula"],
  ["Comune", "Municipio"],
  ["Regione", "Statuto"],
  ["Provincia", "Ente"],
  ["Prefetto", "Palazzo"],
  ["Questore", "Ordine"],
  ["Polizia", "Sirena"],
  ["Esercito", "Mimetica"],
  ["Debito pubblico", "Spread"],
  ["PIL", "Crescita"],
  ["Inflazione", "Prezzi"],
  ["BCE", "Euro"],
  ["Borsa", "Indice"],
  ["Banca", "Interessi"],
  ["Privatizzazione", "Vendita"],
  ["Welfare", "Assistenza, sistema pubblico"],
  ["Bonus", "Stato, agevolazione economica"],
  ["Reddito", "Sussidio, soglia ISEE"],
  ["ISEE", "Dichiarazione"],
  ["Riforma", "Cambiamento"],
  ["Taglio", "Forbici"],
  ["Spesa pubblica", "Costi"],
  ["Corruzione", "Mazzetta"],
  ["Casta", "Privilegio"],
  ["Immunità", "Scudo"],
  ["Giustizia", "Toga"],
  ["Magistratura", "Procura"],
  ["Processo", "Tribunale"],
  ["Reato", "Codice"],
  ["Sovranità", "Popolo"],
  ["Cittadino", "Passaporto"],
  ["Visto", "Frontiera"],
  ["Immigrazione", "Sbarco"],
  ["Asilo", "Protezione"],
  ["Diritti", "Umani"],
  ["Doveri", "Civico"],
  ["Obbligo", "Legge"],
  ["Divieto", "Cartello"],
  ["Norma", "Regola"],
  ["Regolamento", "Articolo"],
  ["Direttiva", "Bruxelles"],
  ["Trattato", "Firma"],
  ["Patto", "Accordo"],
  ["Tensione", "Crisi"],
  ["Caduta", "Fiducia"],
  ["Rimpasto", "Poltrone"],
  ["Consultazioni", "Incarico"],
  ["Giuramento", "Mano"],
  ["Discorso", "Messaggio"],
  ["Capodanno", "Televisione"],
  ["Inno", "Musica"],
  ["Emblema", "Scudo"],
  ["Chigi", "Palazzo, sede del premier"],
  ["Viminale", "Interno"],
  ["Farnesina", "Estero"],
  ["Difesa", "Armi"],
  ["Economia", "Soldi"],
  ["Infrastrutture", "Cantieri"],
  ["Trasporti", "Treno"],
  ["Agricoltura", "Terra"],
  ["Cultura", "Museo"],
  ["Turismo", "Viaggi"],
  ["Famiglia", "Figli"],
  ["Pari opportunità", "Genere"],
  ["Federalismo", "Decentramento"],
  ["Autonomia", "Differenziata"],
  ["Centralismo", "Capitale"],
  ["Burocrazia", "Timbro"],
  ["Bollo", "Marca"],
  ["Pratica", "Faldone"],
  ["Sportello", "Coda"],
  ["Anagrafe", "Residenza"],
  ["Voto di scambio", "Favore"],
  ["Broglio", "Urna"],
  ["Astensionismo", "Assenza"],
  ["Affluenza", "Dati"],
  ["Scrutinio", "Conteggio"],
  ["Ballottaggio", "Secondo turno"],
  ["Proporzionale", "Resti"],
  ["Maggioritario", "Collegio"],
  ["Uninominale", "Sfida"],
  ["Listino", "Bloccato"],
  ["Circoscrizione", "Zona"],
  ["Volantino", "Cassetta"],
  ["Spilla", "Giacca"],
  ["Slogan", "Rima"],
  ["Megafono", "Voce"],
  ["Palco", "Comizio"],
  ["Transenna", "Fila"],
  ["Scorta", "Auto"],
  ["Auto blu", "Lampeggiante"],
  ["Protocollo", "Cerimoniale"],
  ["Etichetta", "Bon ton"],
  ["Ricevimento", "Cena"],
  ["Viaggio di stato", "Aereo"],
  ["Valigetta", "Codice"],
  ["Segreto", "Intelligence"],
  ["Spionaggio", "Agente"],
  ["Sicurezza", "Telecamera"],
  ["Caos", "Disordine"],
  ["Rivoluzione", "Piazza"],
  ["Colpo di stato", "Tank"],
  ["Dittatura", "Pugno"],
  ["Tirannia", "Catene"],
  ["Oligarchia", "Pochi"],
  ["Tecnocrazia", "Esperti"],
  ["Populismo", "Popolo"],
  ["Sovranismo", "Muro"],
  ["Globalizzazione", "Mondo"],
  ["Protezionismo", "Dazio"],
  ["Dogana", "Confine"],
  ["Sorveglianza", "Drone"],
  ["Privacy", "Dati"],
  ["Algoritmo", "Web"],
  ["Propaganda", "Manifesto"],
  ["Notizia falsa", "Bufala"],
  ["Troll", "Commento"],
  ["Social network", "Like"],
  ["Streaming", "Diretta"],
  ["Podcast", "Cuffie"],
  ["Talk show", "Poltrona"],
  ["Giornale", "Edicola"],
  ["Stampa", "Rotativa"],
  ["Opinione", "Pubblica"],
  ["Censura", "Bavaglio"],
  ["Redazione", "Articolo"],
  ["Titolo", "Prima pagina"],
  ["Scoop", "Esclusiva"],
  ["Notizia", "Flash"],
  ["Gola profonda", "Fonte"],
  ["Embargo", "Blocco"],
  ["Manifestazione", "Corteo"],
  ["Bandiera", "Asta"],
  ["Manganello", "Ordine"],
  ["Gas lacrimogeno", "Fumo"],
  ["Barricata", "Strada"],
  ["Protesta", "Urlo"],
  ["Rivolta", "Fuoco"],
  ["Pace fiscale", "Condono"],
];
