export const IDEE: [string, string][] = [
  ["Democrazia", "Società"],
  ["Libertà", "Valore"],
  ["Uguaglianza", "Valore"],
  ["Rivoluzione", "Cambiamento"],
  ["Capitalismo", "Sistema"],
  ["Comunismo", "Sistema"],
  ["Anarchia", "Sistema"],
  ["Femminismo", "Movimento"],
  ["Ambientalismo", "Movimento"],
  ["Nazionalismo", "Movimento"],
  ["Populismo", "Politica"],
  ["Sciopero", "Lavoro"],
  ["Costituzione", "Regole"],
  ["Referendum", "Scelta"],
  ["Propaganda", "Comunicazione"],
  ["Censura", "Controllo"],
  ["Tasse", "Soldi"],
  ["Welfare", "Società"],
  ["Corruzione", "Scandalo"],
  ["Utopia", "Sogno"],
];
