export const MEDICINA: [string, string][] = [
  ["Cuore", "Battito"],
  ["Polmoni", "Soffio"],
  ["Cervello", "Scintilla"],
  ["Ossa", "Sostegno"],
  ["Sangue", "Flusso"],
  ["Fegato", "Filtro"],
  ["Stomaco", "Acido"],
  ["Pelle", "Superficie"],
  ["Muscoli", "Tensione"],
  ["Scheletro", "Impalcatura"],
  ["Vene", "Percorso"],
  ["Arterie", "Pressione"],
  ["Reni", "Scarto"],
  ["Occhi", "Orizzonte"],
  ["Orecchie", "Ascolto"],
  ["Denti", "Morsicata"],
  ["Lingua", "Assaggio"],
  ["Mani", "Contatto"],
  ["Piedi", "Passo"],
  ["Colonna vertebrale", "Asse"],
  ["Cranio", "Guscio"],
  ["Costole", "Gabbia"],
  ["Ginocchio", "Snodo"],
  ["Gomito", "Punta"],
  ["Spalla", "Peso"],
  ["Intestino", "Labirinto"],
  ["Pancreas", "Zucchero"],
  ["Vescica", "Pieno"],
  ["Tiroide", "Farfalla"],
  ["Milza", "Riserva"],
  ["Ghiandole", "Messaggio"],
  ["Nervi", "Elettricità"],
  ["Midollo", "Centro"],
  ["Cellule", "Mattoncini"],
  ["DNA", "Eredità"],
  ["Virus", "Invasore"],
  ["Batteri", "Invisibile"],
  ["Febbre", "Calore"],
  ["Tosse", "Eco"],
  ["Raffreddore", "Fazzoletto"],
  ["Influenza", "Stagione"],
  ["Allergia", "Polline"],
  ["Asma", "Mancanza"],
  ["Diabete", "Dolcezza"],
  ["Ipertensione", "Alta"],
  ["Gastrite", "Bruciore"],
  ["Frattura", "Rumore"],
  ["Distorsione", "Movimento"],
  ["Livido", "Colore"],
  ["Cicatrice", "Ricordo"],
  ["Infezione", "Allarme"],
  ["Infiammazione", "Arrossamento"],
  ["Dolore", "Lamento"],
  ["Nausea", "Onda"],
  ["Vertigini", "Girotondo"],
  ["Svenimento", "Buio"],
  ["Coma", "Sospensione"],
  ["Insonnia", "Veglia"],
  ["Stress", "Accumulo"],
  ["Ansia", "Batticuore"],
  ["Depressione", "Grigio"],
  ["Amnesia", "Vuoto"],
  ["Allucinazione", "Fata Morgana"],
  ["Fobia", "Terrore"],
  ["Chirurgia", "Intervento"],
  ["Medicina", "Facoltà universitaria"],
  ["Farmacia", "Croce"],
  ["Ricetta", "Farmacia, foglio del medico"],
  ["Pillola", "Confetto"],
  ["Sciroppo", "Cucchiaio"],
  ["Pomata", "Crema"],
  ["Iniezione", "Puntura"],
  ["Vaccino", "Difesa"],
  ["Antibiotico", "Resistenza"],
  ["Aspirina", "Bianca"],
  ["Anestesia", "Oblio"],
  ["Benda", "Avvolgimento"],
  ["Cerotto", "Striscia"],
  ["Termometro", "Colonna"],
  ["Stetoscopio", "Freddo"],
  ["Bisturi", "Precisione"],
  ["Siringa", "Plastica"],
  ["Guanti", "Lattice"],
  ["Mascherina", "Filtro"],
  ["Camice", "Bianco"],
  ["Ospedale", "Corridoio"],
  ["Ambulanza", "Sirena"],
  ["Pronto Soccorso", "Codice"],
  ["Reparto", "Sezione"],
  ["Corsia", "Passaggio"],
  ["Sala operatoria", "Scialitica"],
  ["Terapia intensiva", "Monitor"],
  ["Ambulatorio", "Appuntamento"],
  ["Analisi del sangue", "Provette"],
  ["Radiografia", "Negativo"],
  ["Ecografia", "Gel"],
  ["Risonanza", "Tunnel"],
  ["TAC", "Cerchio"],
  ["Elettrocardiogramma", "Onda"],
  ["Pressione", "Bracciale"],
  ["Disinfettante", "Odore"],
  ["Alcol", "Pungente"],
  ["Acqua ossigenata", "Schiuma"],
  ["Tachipirina", "Sollievo"],
  ["Insulina", "Penna"],
  ["Vitamine", "Frutta"],
  ["Integratori", "Forza"],
  ["Cortisone", "Gonfiore"],
  ["Sedativo", "Calma"],
  ["Anestetico", "Sonno"],
  ["Flebo", "Gocciolamento"],
  ["Trasfusione", "Sacca"],
  ["Donazione", "Gesto"],
  ["Trapianto", "Nuova vita"],
  ["Donatore", "Anonimo"],
  ["Paziente", "Attesa"],
  ["Medico", "Laurea"],
  ["Infermiere", "Assistenza"],
  ["Chirurgo", "Mani"],
  ["Anestesista", "Veglia"],
  ["Pediatra", "Bambini"],
  ["Ginecologo", "Nascita"],
  ["Cardiologo", "Ritmo"],
  ["Dermatologo", "Eruzione"],
  ["Oculista", "Lenti"],
  ["Dentista", "Poltrona"],
  ["Ortopedico", "Ossa"],
  ["Neurologo", "Pensiero"],
  ["Psichiatra", "Mente"],
  ["Psicologo", "Parola"],
  ["Fisioterapista", "Esercizio"],
  ["Ostetrica", "Aiuto"],
  ["Radiologo", "Immagine"],
  ["Farmacista", "Scatole"],
  ["Veterinario", "Zampe"],
  ["Ricercatore", "Scoperta"],
  ["Scienziato", "Metodo"],
  ["Malattia", "Sintomo"],
  ["Guarigione", "Sorriso"],
  ["Salute", "Bene"],
  ["Prevenzione", "Futuro"],
  ["Dieta", "Cibo"],
  ["Sport", "Movimento"],
  ["Sonno", "Riposo"],
  ["Igiene", "Pulizia"],
  ["Sapone", "Schiuma"],
  ["Spazzolino", "Setole"],
  ["Occhiali", "Montatura"],
  ["Sedia a rotelle", "Ruote"],
  ["Stampelle", "Appoggio"],
  ["Gesso", "Firma"],
  ["Barella", "Ruote"],
  ["Lettino", "Visita"],
  ["Sala d'attesa", "Riviste"],
  ["Ricovero", "Notte"],
  ["Dimissioni", "Uscita"],
  ["Cartella clinica", "Dati"],
  ["Consenso", "Firma"],
  ["Privacy", "Riservatezza"],
  ["Assicurazione", "Polizza"],
  ["Mutua", "Tessera"],
  ["Ticket", "Pagamento"],
  ["Appuntamento", "Orario"],
  ["Visita", "Controllo"],
  ["Diagnosi", "Risultato"],
  ["Prognosi", "Tempo"],
  ["Terapia", "Percorso"],
  ["Cura", "Percorso di guarigione"],
  ["Effetto collaterale", "Rischio"],
  ["Sovradosaggio", "Pericolo"],
  ["Intolleranza", "Reazione"],
  ["Shock", "Improvviso"],
  ["Emorragia", "Rosso"],
  ["Ferita", "Taglio"],
  ["Ustione", "Calore"],
  ["Puntura", "Insetto"],
  ["Morso", "Segno"],
  ["Trauma", "Colpo"],
  ["Ictus", "Minuti"],
  ["Infarto", "Petto"],
  ["Tumore", "Massa"],
  ["Cancro", "Lotta"],
  ["Chemioterapia", "Ciclo"],
  ["Radioterapia", "Raggi"],
  ["Dialisi", "Filtro"],
  ["Rianimazione", "Ritorno"],
  ["Defibrillatore", "Scossa"],
  ["Massaggio cardiaco", "Spinta"],
  ["Primo soccorso", "Valigetta"],
  ["Placenta", "Nido"],
  ["Pupilla", "Serratura"],
  ["Adrenalina", "Corsa"],
  ["Sinapsi", "Scambio"],
  ["Globuli bianchi", "Soldati"],
  ["Plasma", "Fluido"],
  ["Piastrine", "Tappo"],
  ["Cartilagine", "Gomma"],
  ["Tendine", "Corda"],
  ["Legamento", "Ginocchio"],
  ["Menisco", "Cuscinetto"]
];
