export const MEDICINA: [string, string][] = [
  ["Cuore", "Battito"],
  ["Febbre", "Calore addosso"],
  ["Siringa", "Sguardo altrove"],
  ["Ospedale", "Corridoi lunghi"],
  ["Ambulanza", "Sirena"],
  ["Dentista", "Trapano"],
  ["Cerotto", "Ginocchio sbucciato"],
  ["Gesso", "Firme sopra"],
  ["Radiografia", "Ombra bianca"],
  ["Vaccino", "Difesa"],
  ["Camice", "Bianco autorevole"],
  ["Sala d'attesa", "Riviste vecchie"],
  ["Pillola", "Bicchiere d'acqua"],
  ["Sangue", "Svenimento"],
  ["Chirurgo", "Mani ferme"],
  ["Allergia", "Primavera nemica"],
  ["Insonnia", "Soffitto"],
  ["Termometro", "Ascella"],
  ["Ansia", "Nodo"],
  ["Ricetta", "Grafia illeggibile"],
];
