export const MEDICINA: [string, string][] = [
  ["Cuore", "Corpo"],
  ["Febbre", "Malessere"],
  ["Siringa", "Oggetto"],
  ["Ospedale", "Luogo"],
  ["Ambulanza", "Emergenza"],
  ["Dentista", "Visita"],
  ["Cerotto", "Piccolo danno"],
  ["Gesso", "Incidente"],
  ["Radiografia", "Esame"],
  ["Vaccino", "Prevenzione"],
  ["Camice", "Divisa"],
  ["Sala d'attesa", "Attesa"],
  ["Pillola", "Cura"],
  ["Sangue", "Corpo"],
  ["Chirurgo", "Mestiere"],
  ["Allergia", "Fastidio"],
  ["Insonnia", "Notte"],
  ["Termometro", "Misura"],
  ["Ansia", "Testa"],
  ["Ricetta", "Foglio"],
];
