export const MEME: [string, string][] = [
  ["Gattino", "Internet"],
  ["Facepalm", "Reazione"],
  ["Troll", "Persona"],
  ["Hashtag", "Simbolo"],
  ["Emoji", "Messaggi"],
  ["Sticker", "Messaggi"],
  ["Video virale", "Internet"],
  ["Challenge", "Moda"],
  ["Influencer", "Persona"],
  ["Commento tossico", "Internet"],
  ["Screenshot", "Telefono"],
  ["Reaction", "Video"],
  ["Balletto", "Moda"],
  ["Cringe", "Sensazione"],
  ["Boomer", "Etichetta"],
  ["Spam", "Fastidio"],
  ["Filtro", "Immagine"],
  ["Like", "Approvazione"],
  ["Storia", "Social"],
  ["Fake", "Verità"],
];
