export const MEME: [string, string][] = [
  ["Rickroll", "Anni Ottanta"],
  ["Distracted Boyfriend", "Sguardo"],
  ["Doge", "Wow"],
  ["Grumpy Cat", "Espressione"],
  ["Nyan Cat", "Arcobaleno"],
  ["Pepe the Frog", "Verde"],
  ["Trollface", "Sorriso"],
  ["Harambe", "Zoo"],
  ["Ok Boomer", "Generazione"],
  ["Sto cazzo", "Tavolo"],
  ["Chad", "Mento"],
  ["Wojak", "Tristezza"],
  ["Karen", "Manager"],
  ["This is fine", "Incendio"],
  ["Woman yelling at cat", "Tavola"],
  ["Salt Bae", "Sale"],
  ["Ice Bucket Challenge", "Beneficenza"],
  ["Planking", "Rigidità"],
  ["Gangnam Style", "Cavallo"],
  ["Baby Shark", "Ritornello"],
  ["Sadge", "Twitch"],
  ["Pog", "Reazione"],
  ["Kappa", "Faccina"],
  ["Among Us", "Impostore"],
  ["Sussy", "Sospetto"],
  ["Amogus", "Fandom"],
  ["Skibidi Toilet", "YouTube"],
  ["Rizz", "Fascino"],
  ["Cringe", "Imbarazzo"],
  ["Based", "Approvazione"],
  ["No cap", "Sincerità"],
  ["Bussy", "Slang"],
  ["Delulu", "Fantasia"],
  ["Gaslighting", "Manipolazione"],
  ["Simp", "Devozione"],
  ["Stan", "Fandom"],
  ["Ghosting", "Silenzio"],
  ["Flex", "Ostentazione"],
  ["Vibe check", "Atmosfera"],
  ["FOMO", "Ansia"],
  ["YOLO", "Impulso"],
  ["Lit", "Entusiasmo"],
  ["Savage", "Audacia"],
  ["Slay", "Successo"],
  ["Glow up", "Trasformazione"],
  ["Mood", "Stato d'animo"],
  ["Tea", "Pettegolezzo"],
  ["Shade", "Sarcasmo"],
  ["Receipts", "Prove"],
  ["Clout", "Popolarità"],
  ["Troll", "Provocazione"],
  ["Hater", "Critica"],
  ["Fanboy", "Passione"],
  ["Shitpost", "Ironia"],
  ["Copypasta", "Testo"],
  ["Reaction image", "Screenshot"],
  ["Reaction video", "Commento"],
  ["Cringe compilation", "Video"],
  ["Fail compilation", "Incidenti"],
  ["Vine", "Sei secondi"],
  ["TikTok dance", "Coreografia"],
  ["Renegade", "Coreografia"],
  ["Woah dance", "Passo"],
  ["Floss dance", "Braccia"],
  ["Griddy", "Passo"],
  ["Ohio", "Meme geografico"],
  ["Rizzler", "Personaggio"],
  ["Gyat", "Esclamazione"],
  ["Fanum tax", "Cibo"],
  ["Skibidi", "Suono"],
  ["Sigma", "Personalità"],
  ["Alpha", "Gerarchia"],
  ["NPC", "Videogioco"],
  ["Main character energy", "Protagonismo"],
  ["It's giving", "Espressione"],
  ["Understood the assignment", "Approvazione"],
  ["Slay queen", "Complimento"],
  ["Bestie", "Amicizia"],
  ["Sksksk", "Suono"],
  ["VSCO girl", "Estetica"],
  ["E-girl", "Estetica"],
  ["E-boy", "Estetica"],
  ["Soft launch", "Relazione"],
  ["Hard launch", "Relazione"],
  ["Situationship", "Relazione"],
  ["Talking stage", "Relazione"],
  ["Ick", "Repulsione"],
  ["Red flag", "Avvertimento"],
  ["Green flag", "Rassicurazione"],
  ["Beige flag", "Neutralità"],
  ["Touch grass", "Consiglio"],
  ["Chronically online", "Abitudine"],
  ["Terminally online", "Abitudine"],
  ["Extremely online", "Abitudine"],
  ["Ratio", "Commento"],
  ["L + ratio", "Sconfitta"],
  ["W rizz", "Successo"],
  ["L take", "Opinione"],
  ["Hot take", "Opinione"],
  ["Unpopular opinion", "Opinione"],
  ["Cancel culture", "Boicottaggio"],
  ["Doxxing", "Privacy"],
  ["Catfish", "Inganno"],
  ["Sock puppet", "Falso profilo"],
  ["Bot farm", "Automazione"],
  ["Algoritmo", "Consigli"],
  ["Per te (FYP)", "TikTok"],
  ["Hashtag", "Simbolo"],
  ["Trending topic", "Popolarità"],
  ["Viral video", "Diffusione"],
  ["Screenshot virale", "Condivisione"],
  ["Storia Instagram", "Effimero"],
  ["Reel", "Formato breve"],
  ["Story boomerang", "Loop"],
  ["Filtro Snapchat", "Fotocamera"],
  ["Filtro cane", "Orecchie"],
  ["Beauty filter", "Ritocco"],
  ["Selfie", "Autoscatto"],
  ["Selfie stick", "Asta"],
  ["Duckface", "Labbra"],
  ["Photobomb", "Sorpresa"],
  ["Meme template", "Formato"],
  ["Caption", "Didascalia"],
  ["Emoji", "Simbolo"],
  ["Faccina piangente", "Emozione"],
  ["Skull emoji", "Risata"],
  ["GIF", "Animazione"],
  ["Sticker WhatsApp", "Chat"],
  ["Meme di gatti", "Animale"],
  ["Meme di cani", "Animale"],
  ["Loss meme", "Formato"],
  ["Galaxy brain", "Ironia"],
  ["Big brain", "Ironia"],
  ["Smooth brain", "Ironia"],
  ["IQ meme", "Intelligenza"],
  ["4chan", "Forum"],
  ["Reddit", "Forum"],
  ["Upvote", "Consenso"],
  ["Downvote", "Dissenso"],
  ["Karma Reddit", "Punteggio"],
  ["Subreddit", "Comunità"],
  ["AMA", "Domande"],
  ["TIL", "Curiosità"],
  ["ELI5", "Spiegazione"],
  ["Meme war", "Competizione"],
  ["Deep fried meme", "Filtro"],
  ["Surreal meme", "Assurdo"],
  ["Wholesome meme", "Tenerezza"],
  ["Dank meme", "Umorismo"],
  ["Normie", "Mainstream"],
  ["Weeb", "Passione"],
  ["Otaku", "Passione"],
  ["Cosplay", "Costume"],
  ["Waifu", "Personaggio"],
  ["Husbando", "Personaggio"],
  ["Anime opening", "Sigla"],
  ["Fan edit", "Montaggio"],
  ["Edit TikTok", "Montaggio"],
  ["Thirst trap", "Fotografia"],
  ["Clickbait", "Titolo"],
  ["Titolo acchiappaclick", "Curiosità"],
  ["Prank virale", "Scherzo"],
  ["Challenge virale", "Sfida"],
  ["Cinnamon challenge", "Sfida"],
  ["Mannequin challenge", "Immobilità"],
  ["Bottle flip", "Lancio"],
  ["Fidget spinner", "Oggetto"],
  ["Pokemon Go", "Cattura"],
  ["Flappy Bird", "Difficoltà"],
  ["Candy Crush", "Dipendenza"],
  ["Fortnite dance", "Ballo"],
  ["Minecraft creeper", "Esplosione"],
  ["Roblox oof", "Suono"],
  ["GTA meme", "Videogioco"],
  ["Speedrun", "Velocità"],
  ["Rage quit", "Frustrazione"],
  ["Git gud", "Consiglio"],
  ["Noob", "Principiante"],
  ["Pro gamer move", "Ironia"],
  ["Twitch chat", "Interazione"],
  ["Emote Twitch", "Reazione"],
  ["Streamer", "Diretta"],
  ["Sub train", "Abbonamenti"],
  ["Donation goal", "Beneficenza"],
  ["Let's play", "Video"],
  ["Unboxing", "Scatola"],
  ["Haul video", "Shopping"],
  ["ASMR", "Sussurro"],
  ["Mukbang", "Cibo"],
  ["Vlog", "Diario video"],
  ["Prank call", "Telefonata"],
  ["Podcast virale", "Audio"],
  ["Meme musicale", "Suono"],
  ["Sound virale TikTok", "Audio"],
  ["Remix meme", "Musica"],
  ["Vine boom", "Effetto sonoro"],
  ["Bruh sound", "Effetto sonoro"],
  ["Sad violin", "Effetto sonoro"],
  ["Airhorn meme", "Effetto sonoro"],
  ["Meme politico", "Satira"],
  ["Fake news", "Disinformazione"],
  ["Deepfake", "Manipolazione"],
  ["Bot Twitter", "Automazione"],
  ["Blue check", "Verifica"],
  ["Ratio Twitter", "Commenti"],
  ["Subtweet", "Allusione"],
  ["Screenshot vergogna", "Chat"],
  ["Group chat", "Conversazione"],
  ["Reazione a catena", "Condivisione"],
  ["Influencer", "Sponsorizzazione"],
  ["Brand deal", "Contratto"],
  ["Sponsorizzazione", "Prodotto"],
  ["Unfollow di massa", "Reazione"],
  ["Shadowban", "Visibilità"],
  ["Verifica blu", "Status"],
  ["App di dating", "Match"],
  ["Swipe", "Gesto"],
  ["Match", "Cuore"],
  ["Ghosting digitale", "Silenzio"],
];
