export const MEME: [string, string][] = [
  ["Gattino", "Tenerezza virale"],
  ["Facepalm", "Imbarazzo"],
  ["Troll", "Provocazione"],
  ["Hashtag", "Cancelletto"],
  ["Emoji", "Faccina"],
  ["Sticker", "Chat"],
  ["Video virale", "Milioni di occhi"],
  ["Challenge", "Sfida imitata"],
  ["Influencer", "Vetrina digitale"],
  ["Commento tossico", "Veleno"],
  ["Screenshot", "Prova"],
  ["Reaction", "Faccia esagerata"],
  ["Balletto", "Passi copiati"],
  ["Cringe", "Disagio"],
  ["Boomer", "Generazione lontana"],
  ["Spam", "Ripetizione molesta"],
  ["Filtro", "Volto ritoccato"],
  ["Like", "Pollice"],
  ["Storia", "Ventiquattr'ore"],
  ["Fake", "Finto credibile"],
];
