export const MITOLOGIA: [string, string][] = [
  ["Zeus", "Antichità"],
  ["Ade", "Antichità"],
  ["Medusa", "Creatura"],
  ["Minotauro", "Creatura"],
  ["Ciclope", "Creatura"],
  ["Sirena", "Mare"],
  ["Cerbero", "Creatura"],
  ["Fenice", "Leggenda"],
  ["Icaro", "Racconto"],
  ["Achille", "Eroe"],
  ["Ulisse", "Eroe"],
  ["Cavallo di Troia", "Racconto"],
  ["Pandora", "Racconto"],
  ["Olimpo", "Luogo"],
  ["Titano", "Antichità"],
  ["Drago", "Creatura"],
  ["Unicorno", "Fantasia"],
  ["Prometeo", "Racconto"],
  ["Narciso", "Racconto"],
  ["Fato", "Destino"],
];
