export const MITOLOGIA: [string, string][] = [
  ["Zeus", "Divinità fulmine"],
  ["Ade", "Divinità sotterranea"],
  ["Medusa", "Sguardo pietrificante"],
  ["Minotauro", "Labirinto"],
  ["Ciclope", "Occhio solo"],
  ["Sirena", "Canto ingannevole"],
  ["Cerbero", "Guardiano tricipite"],
  ["Fenice", "Rinascita"],
  ["Icaro", "Volo imprudente"],
  ["Achille", "Punto debole"],
  ["Ulisse", "Ritorno lunghissimo"],
  ["Cavallo di Troia", "Inganno legno"],
  ["Pandora", "Vaso proibito"],
  ["Olimpo", "Vetta divina"],
  ["Titano", "Forza antica"],
  ["Drago", "Fiamma leggendaria"],
  ["Unicorno", "Purezza favolosa"],
  ["Prometeo", "Fuoco rubato"],
  ["Narciso", "Riflesso"],
  ["Fato", "Filo tagliato"],
];
