export const MITOLOGIA: [string, string][] = [
  ["Zeus", "Vetta bianca"],
  ["Poseidone", "Sale profondo"],
  ["Ade", "Ombra silenziosa"],
  ["Atena", "Civetta notturna"],
  ["Afrodite", "Schiuma bianca"],
  ["Ares", "Ferro rosso"],
  ["Apollo", "Luce d'oro"],
  ["Artemide", "Bosco d'argento"],
  ["Efesto", "Scintilla calda"],
  ["Ermes", "Passo veloce"],
  ["Dioniso", "Uva matura"],
  ["Era", "Piuma di pavone"],
  ["Demetra", "Grano secco"],
  ["Medusa", "Pietra fredda"],
  ["Minotauro", "Labirinto buio"],
  ["Pegaso", "Volo bianco"],
  ["Idra", "Mille teste"],
  ["Cerbero", "Tre respiri"],
  ["Achille", "Tallone fragile"],
  ["Ettore", "Mura di Troia"],
  ["Paride", "Mela d'oro"],
  ["Elena", "Guerra lunga"],
  ["Odisseo", "Viaggio infinito"],
  ["Penelope", "Tela disfatta"],
  ["Telemaco", "Attesa lunga"],
  ["Circe", "Porco rosa"],
  ["Polifemo", "Occhio solo"],
  ["Sirene", "Canto dolce"],
  ["Scilla", "Scoglio aguzzo"],
  ["Cariddi", "Vortice d'acqua"],
  ["Prometeo", "Fuoco rubato"],
  ["Pandora", "Vaso chiuso"],
  ["Ercole", "Dodici fatiche"],
  ["Atlante", "Peso del mondo"],
  ["Sisifo", "Sasso pesante"],
  ["Tantalo", "Sete eterna"],
  ["Icaro", "Ali di cera"],
  ["Dedalo", "Fuga in alto"],
  ["Narciso", "Specchio d'acqua"],
  ["Eco", "Voce riflessa"],
  ["Orfeo", "Lira dolce"],
  ["Euridice", "Sguardo fatale"],
  ["Perseo", "Testa tagliata"],
  ["Giasone", "Vello d'oro"],
  ["Argonauti", "Nave veloce"],
  ["Medea", "Pozione magica"],
  ["Teseo", "Filo di lana"],
  ["Arianna", "Abbandono"],
  ["Edipo", "Enigma risolto"],
  ["Antigone", "Legge morale"],
  ["Enea", "Fuga da Troia"],
  ["Romolo", "Lupa grigia"],
  ["Remo", "Solco fatale"],
  ["Giano", "Due facce"],
  ["Quirino", "Popolo armato"],
  ["Saturno", "Tempo mangiatore"],
  ["Giove", "Fulmine caduto"],
  ["Giunone", "Fedeltà"],
  ["Nettuno", "Tridente lungo"],
  ["Plutone", "Ricchezza sotterranea"],
  ["Minerva", "Saggezza armata"],
  ["Diana", "Luna calante"],
  ["Marte", "Sangue versato"],
  ["Venere", "Bellezza nuda"],
  ["Vulcano", "Incudine"],
  ["Mercurio", "Ali ai piedi"],
  ["Vesta", "Fuoco perenne"],
  ["Bacco", "Vino rosso"],
  ["Cupido", "Freccia d'amore"],
  ["Psiche", "Anima leggera"],
  ["Thor", "Martello pesante"],
  ["Odino", "Corvo nero"],
  ["Loki", "Inganno sottile"],
  ["Freya", "Lacrime d'oro"],
  ["Baldur", "Vischio verde"],
  ["Heimdall", "Corno forte"],
  ["Tyr", "Mano persa"],
  ["Hel", "Regno freddo"],
  ["Fenrir", "Lupo gigante"],
  ["Jormungandr", "Serpente del mondo"],
  ["Valkyrie", "Ali di cuoio"],
  ["Valhalla", "Banchetto eterno"],
  ["Asgard", "Ponte arcobaleno"],
  ["Midgard", "Terra di mezzo"],
  ["Yggdrasill", "Albero cosmico"],
  ["Ragnarok", "Fine di tutto"],
  ["Mjolnir", "Tuono sordo"],
  ["Gungnir", "Lancia dritta"],
  ["Sleipnir", "Otto zampe"],
  ["Fafnir", "Drago avaro"],
  ["Sigfrido", "Sangue di drago"],
  ["Brunilde", "Fuoco circolare"],
  ["Anubi", "Chacal nero"],
  ["Osiride", "Mummia verde"],
  ["Iside", "Ali spiegate"],
  ["Horus", "Falco alto"],
  ["Seth", "Deserto rosso"],
  ["Ra", "Sole cocente"],
  ["Thot", "Ibis bianco"],
  ["Bastet", "Gatto agile"],
  ["Sobek", "Coccodrillo"],
  ["Sfinge", "Enigma di pietra"],
  ["Fenice", "Cenere calda"],
  ["Grifone", "Leone alato"],
  ["Centauro", "Zoccoli e mani"],
  ["Satiro", "Flauto di canna"],
  ["Ninfe", "Acqua chiara"],
  ["Muse", "Ispirazione"],
  ["Parche", "Filo tagliato"],
  ["Moire", "Destino oscuro"],
  ["Erinni", "Vendetta"],
  ["Gorgoni", "Sguardo di pietra"],
  ["Arpie", "Vento rapido"],
  ["Chimera", "Fiamma viva"],
  ["Pegaso", "Piume bianche"],
  ["Bellerofonte", "Caduta dal cielo"],
  ["Cadmo", "Denti di drago"],
  ["Europa", "Toro bianco"],
  ["Danae", "Pioggia d'oro"],
  ["Leda", "Cigno regale"],
  ["Ganimede", "Coppa piena"],
  ["Adone", "Fiore rosso"],
  ["Pigmalione", "Statua viva"],
  ["Galatea", "Marmo bianco"],
  ["Mida", "Tutto d'oro"],
  ["Pandora", "Speranza rimasta"],
  ["Deucalione", "Pietre lanciate"],
  ["Pirra", "Madre terra"],
  ["Aracne", "Tela sottile"],
  ["Niobe", "Pianto eterno"],
  ["Atteone", "Cervo in fuga"],
  ["Fetonte", "Carro di fuoco"],
  ["Ippolito", "Cavalli imbizzarriti"],
  ["Fedra", "Lettera falsa"],
  ["Teseo", "Vela nera"],
  ["Egeo", "Mare blu"],
  ["Cassandra", "Profezia inascoltata"],
  ["Laocoonte", "Serpenti marini"],
  ["Priamo", "Re piangente"],
  ["Ecuba", "Dolore antico"],
  ["Andromaca", "Addio sulle mura"],
  ["Astianatte", "Caduta fatale"],
  ["Aiace", "Scudo grande"],
  ["Patroclo", "Armatura prestata"],
  ["Diomede", "Coraggio"],
  ["Nestore", "Saggio consiglio"],
  ["Agamennone", "Capo supremo"],
  ["Clitemnestra", "Scure affilata"],
  ["Oreste", "Rimorso"],
  ["Elettra", "Lutto"],
  ["Egisto", "Tradimento"],
  ["Ifigenia", "Sacrificio"],
  ["Calipso", "Isola lontana"],
  ["Nausicaa", "Palla sulla spiaggia"],
  ["Alcinoo", "Ospitalità"],
  ["Itaca", "Scoglio arido"],
  ["Polifemo", "Formaggio di pecora"],
  ["Eolo", "Otre di venti"],
  ["Lestrigoni", "Giganti"],
  ["Lotofagi", "Fiore dell'oblio"],
  ["Mentore", "Guida"],
  ["Argo", "Cane fedele"],
  ["Circe", "Bacchetta"],
  ["Tiresia", "Cecità"],
  ["Stige", "Fiume d'odio"],
  ["Acheronte", "Dolore"],
  ["Flegetonte", "Fuoco liquido"],
  ["Cocito", "Lamento"],
  ["Lethe", "Dimenticanza"],
  ["Caronte", "Moneta in bocca"],
  ["Campi Elisi", "Prato verde"],
  ["Tartaro", "Abisso profondo"],
  ["Erebo", "Tenebra"],
  ["Nyx", "Notte stellata"],
  ["Emera", "Giorno chiaro"],
  ["Etere", "Aria pura"],
  ["Gaia", "Terra fertile"],
  ["Urano", "Cielo stellato"],
  ["Cronos", "Falce affilata"],
  ["Rea", "Pietra fasciata"],
  ["Titani", "Forza antica"],
  ["Giganti", "Montagne mosse"],
  ["Ciclopi", "Forgia cupa"],
  ["Ecatonchiri", "Cento braccia"],
  ["Tifone", "Mostro alato"],
  ["Echidna", "Madre di mostri"],
  ["Ladone", "Drago del giardino"],
  ["Esperidi", "Tramonto"],
  ["Atlante", "Pilastro del mondo"],
  ["Elios", "Carro solare"],
  ["Selene", "Carro lunare"],
  ["Eos", "Dita di rosa"],
  ["Borea", "Vento freddo"],
  ["Zefiro", "Vento dolce"],
  ["Noto", "Vento umido"],
  ["Euro", "Vento secco"],
  ["Iride", "Arco colorato"],
  ["Eris", "Discordia"],
  ["Nike", "Ali di vittoria"],
  ["Bia", "Forza bruta"],
];
