export const MODA: [string, string][] = [
  ["Gucci", "Morsetto"],
  ["Prada", "Triangolo"],
  ["Armani", "Aquila"],
  ["Versace", "Medusa"],
  ["Valentino", "Rosso"],
  ["Dolce & Gabbana", "Sicilia"],
  ["Fendi", "Pelliccia"],
  ["Missoni", "Zig-zag"],
  ["Moschino", "Cuore"],
  ["Salvatore Ferragamo", "Scarpa"],
  ["Louis Vuitton", "Monogramma"],
  ["Chanel", "Numero"],
  ["Dior", "Fiocco"],
  ["Herm\u00e8s", "Arancio"],
  ["Saint Laurent", "Smoking"],
  ["Givenchy", "Audrey"],
  ["Balenciaga", "Volume"],
  ["Celine", "Parigi"],
  ["Chlo\u00e9", "Boh\u00e9mien"],
  ["Lanvin", "Blu"],
  ["Burberry", "Quadri"],
  ["Vivienne Westwood", "Punk"],
  ["Alexander McQueen", "Teschio"],
  ["Stella McCartney", "Bio"],
  ["Victoria Beckham", "Minimal"],
  ["Ralph Lauren", "Cavallo"],
  ["Calvin Klein", "Intimo"],
  ["Tommy Hilfiger", "Bandiera"],
  ["Michael Kors", "Jetset"],
  ["Tom Ford", "Occhiali"],
  ["Marc Jacobs", "Grunge"],
  ["Oscar de la Renta", "Gala"],
  ["Carolina Herrera", "Camicia"],
  ["Vera Wang", "Sposa"],
  ["Diane von Furstenberg", "Wrap"],
  ["Nike", "Baffo"],
  ["Adidas", "Strisce"],
  ["Puma", "Salto"],
  ["Reebok", "Palestra"],
  ["New Balance", "Lettera"],
  ["Converse", "Stella"],
  ["Vans", "Tavola"],
  ["Dr. Martens", "Cucitura"],
  ["Timberland", "Scarponcino"],
  ["Levi's", "Etichetta"],
  ["Diesel", "Jeans"],
  ["Benetton", "Colori"],
  ["Zara", "Veloce"],
  ["H&M", "Collaborazione"],
  ["Uniqlo", "Base"],
  ["Rolex", "Corona"],
  ["Omega", "Luna"],
  ["Cartier", "Pantera"],
  ["Bulgari", "Serpente"],
  ["Tiffany", "Azzurro"],
  ["Patek Philippe", "Eredit\u00e0"],
  ["Audemars Piguet", "Ottagono"],
  ["Swatch", "Plastica"],
  ["Ray-Ban", "Goccia"],
  ["Oakley", "Sport"],
  ["Persol", "Freccia"],
  ["Camicia", "Colletto"],
  ["Pantaloni", "Piega"],
  ["Jeans", "Rivetto"],
  ["Gonna", "Orlo"],
  ["Vestito", "Occasione"],
  ["Giacca", "Revers"],
  ["Cappotto", "Bottoni"],
  ["Maglione", "Lana"],
  ["Cardigan", "Bottoni"],
  ["T-shirt", "Cotone"],
  ["Canotta", "Spalline"],
  ["Felpa", "Cappuccio"],
  ["Leggings", "Elastico"],
  ["Shorts", "Estate"],
  ["Cravatta", "Nodo"],
  ["Papillon", "Farfalla"],
  ["Cintura", "Fibbia"],
  ["Sciarpa", "Nodo"],
  ["Guanti", "Dita"],
  ["Cappello", "Tesa"],
  ["Berretto", "Lana"],
  ["Borsa", "Manico"],
  ["Zaino", "Spalle"],
  ["Portafoglio", "Tasca"],
  ["Scarpe", "Suola"],
  ["Stivali", "Tacco"],
  ["Sandali", "Piede"],
  ["Sneakers", "Lacci"],
  ["Mocassini", "Nappine"],
  ["Ballerine", "Danza"],
  ["Tacchi a spillo", "Altezza"],
  ["Zeppe", "Sughero"],
  ["Pantofole", "Casa"],
  ["Calze", "Filo"],
  ["Collant", "Denari"],
  ["Intimo", "Pizzo"],
  ["Reggiseno", "Coppa"],
  ["Mutande", "Elastico"],
  ["Pigiama", "Notte"],
  ["Accappatoio", "Bagno"],
  ["Costume da bagno", "Sabbia"],
  ["Bikini", "Sole"],
  ["Pareo", "Spiaggia"],
  ["Smoking", "Gala"],
  ["Frac", "Coda"],
  ["Tailleur", "Ufficio"],
  ["Trench", "Pioggia"],
  ["Parka", "Freddo"],
  ["Bomber", "Volo"],
  ["Chiodo", "Pelle"],
  ["Blazer", "Bottoni"],
  ["Salopette", "Bretelle"],
  ["Tuta", "Sport"],
  ["Kimono", "Seta"],
  ["Sfilata", "Musica"],
  ["Passerella", "Passo"],
  ["Modella", "Flash"],
  ["Stilista", "Matita"],
  ["Sarto", "Ago"],
  ["Couture", "Mano"],
  ["Pret-a-porter", "Serie"],
  ["Vogue", "Copertina"],
  ["Fashion Week", "Calendario"],
  ["Streetwear", "Strada"],
  ["Vintage", "Tempo"],
  ["Outlet", "Sconto"],
  ["Lusso", "Sogno"],
  ["Tessuto", "Trama"],
  ["Seta", "Morbido"],
  ["Velluto", "Riflesso"],
  ["Lino", "Fresco"],
  ["Pelle", "Odore"],
  ["Cachemire", "Calore"],
  ["Denim", "Blu"],
  ["Pizzo", "Trasparenza"],
  ["Tulle", "Volume"],
  ["Satin", "Lucido"],
  ["Lurex", "Luccichio"],
  ["Pailettes", "Luce"],
  ["Ricamo", "Filo"],
  ["Stampa", "Disegno"],
  ["Pattern", "Ripetizione"],
  ["Texture", "Tatto"],
  ["Drappo", "Caduta"],
  ["Silhouette", "Profilo"],
  ["Taglio", "Forbici"],
  ["Cucitura", "Macchina"],
  ["Fodera", "Interno"],
  ["Tasche", "Contenuto"],
  ["Maniche", "Braccio"],
  ["Polsini", "Bottone"],
  ["Scollo", "V"],
  ["Zip", "Denti"],
  ["Velcro", "Strappo"],
  ["Bottoni", "Asole"],
  ["Spilla", "Punta"],
  ["Gemelli", "Polso"],
  ["Orologio", "Lancette"],
  ["Anello", "Dito"],
  ["Collana", "Collo"],
  ["Orecchini", "Lobo"],
  ["Braccialetto", "Polso"],
  ["Occhiali da sole", "Lente"],
  ["Ombrello", "Pioggia"],
  ["Profumo", "Scia"],
  ["Rossetto", "Labbra"],
  ["Smalto", "Unghie"],
  ["Trucco", "Pennello"],
  ["Acconciatura", "Pettine"],
  ["Parrucca", "Testa"],
  ["Maschera", "Volto"],
  ["Piercing", "Buco"],
  ["Tatuaggio", "Inchiostro"],
  ["Manicure", "Mani"],
  ["Pedicure", "Piedi"],
  ["Estetica", "Specchio"],
  ["Salone", "Poltrona"],
  ["Boutique", "Vetrina"],
  ["Showroom", "Esposizione"],
  ["Manichino", "Vetrina"],
  ["Gruccia", "Armadio"],
  ["Specchio", "Riflesso"],
  ["Camerino", "Tenda"],
  ["Cartellino", "Prezzo"],
  ["Sconto", "Percentuale"],
  ["Saldi", "Folla"],
  ["Trend", "Onda"],
  ["Influencer", "Social"],
  ["Icona", "Tempo"],
  ["Museo della moda", "Storia"],
  ["Atelier", "Creazione"],
  ["Sottoveste", "Scivolo"],
  ["Giarrettiera", "Gamba"],
  ["Corsetto", "Vita"],
  ["Ventaglio", "Aria"],
  ["Bastone", "Passeggio"],
  ["Cappelliera", "Viaggio"],
  ["Baule", "Custodia"],
  ["Valigia", "Ruote"],
  ["Necessaire", "Viaggio"],
  ["Beauty case", "Trucchi"],
  ["Pochette", "Mano"],
  ["Clutch", "Scatto"],
  ["Marsupio", "Vita"],
  ["Tote bag", "Spesa"],
  ["Shopping bag", "Carta"],
  ["Sneakers a stivaletto", "Caviglia"],
  ["Espadrillas", "Corda"],
  ["Infradito", "Gomma"],
  ["Sabot", "Tallone"],
  ["Mules", "Punta"],
  ["Derby", "Stringhe"],
  ["Oxford", "Formale"],
  ["Brogue", "Buchi"],
  ["Loafer", "Comodo"],
  ["Anfibi", "Lacci"],
  ["Cuissardes", "Ginocchio"],
  ["Decollet\u00e9", "Scollo"],
  ["Mary Jane", "Cinturino"],
];
