export const MODA: [string, string][] = [
  ["Passerella", "Evento"],
  ["Tacchi", "Scarpe"],
  ["Jeans", "Abbigliamento"],
  ["Cravatta", "Abbigliamento"],
  ["Camerino", "Negozio"],
  ["Saldi", "Negozio"],
  ["Profumo", "Sensi"],
  ["Rossetto", "Trucco"],
  ["Cappotto", "Inverno"],
  ["Sneakers", "Scarpe"],
  ["Borsa", "Accessorio"],
  ["Occhiali da sole", "Accessorio"],
  ["Stilista", "Mestiere"],
  ["Modella", "Mestiere"],
  ["Vintage", "Stile"],
  ["Sfilata", "Evento"],
  ["Cartellino", "Negozio"],
  ["Pelliccia", "Polemica"],
  ["Tatuaggio", "Corpo"],
  ["Manichino", "Negozio"],
];
