export const MODA: [string, string][] = [
  ["Passerella", "Passo studiato"],
  ["Tacchi", "Altezza dolorosa"],
  ["Jeans", "Rivetti"],
  ["Cravatta", "Nodo formale"],
  ["Camerino", "Tenda"],
  ["Saldi", "Folla gennaio"],
  ["Profumo", "Scia"],
  ["Rossetto", "Labbra"],
  ["Cappotto", "Freddo elegante"],
  ["Sneakers", "Lacci urbani"],
  ["Borsa", "Status a tracolla"],
  ["Occhiali da sole", "Lenti scure"],
  ["Stilista", "Matita creativa"],
  ["Modella", "Flash"],
  ["Vintage", "Tempo tornato"],
  ["Sfilata", "Prima fila"],
  ["Cartellino", "Prezzo"],
  ["Pelliccia", "Polemica calda"],
  ["Tatuaggio", "Inchiostro"],
  ["Manichino", "Vetrina immobile"],
];
