export const MUSICA: [string, string][] = [
  ["Sanremo", "Festival canzone"],
  ["Beatles", "Band inglese"],
  ["Mozart", "Compositore parrucca"],
  ["Vivaldi", "Compositore stagioni"],
  ["Chitarra", "Strumento a corde"],
  ["Pianoforte", "Strumento a tasti"],
  ["Batteria", "Strumento a percussione"],
  ["Violino", "Strumento archetto"],
  ["Tromba", "Strumento a fiato ottone"],
  ["Flauto", "Strumento a fiato legno"],
  ["Rock", "Genere musicale chitarra"],
  ["Jazz", "Genere musicale improvvisato"],
  ["Reggae", "Genere musicale giamaicano"],
  ["Blues", "Genere musicale malinconico"],
  ["Pop", "Genere musicale mainstream"],
  ["Rap", "Genere musicale parlato"],
  ["Metal", "Genere musicale pesante"],
  ["Punk", "Genere musicale ribelle"],
  ["Techno", "Genere musicale elettronico"],
  ["Opera", "Spettacolo lirico"],
  ["Karaoke", "Gioco canto"],
  ["Coldplay", "Band britannica"],
  ["Adele", "Cantante britannica"],
  ["Madonna", "Cantante regina pop"],
  ["Beyoncé", "Cantante americana"],
  ["Elvis", "Cantante rock'n'roll"],
  ["Freddie Mercury", "Cantante baffi"],
  ["David Bowie", "Cantante camaleontico"],
  ["Bob Dylan", "Cantautore folk"],
  ["Bob Marley", "Cantante reggae"],
  ["Michael Jackson", "Cantante re del pop"],
  ["Eminem", "Rapper americano"],
  ["Rihanna", "Cantante barbadiana"],
  ["Whitney Houston", "Cantante soul"],
  ["Amy Winehouse", "Cantante soul inglese"],
  ["Prince", "Cantante enigmatico"],
  ["Elton John", "Cantante pianista"],
  ["Ligabue", "Cantautore rock italiano"],
  ["Vasco Rossi", "Cantautore rock italiano"],
  ["Laura Pausini", "Cantante italiana"],
  ["Eros Ramazzotti", "Cantante italiano"],
  ["Jovanotti", "Cantante italiano"],
  ["Zucchero", "Cantante blues italiano"],
  ["Gianna Nannini", "Cantante rock italiana"],
  ["Renato Zero", "Cantante teatrale italiano"],
  ["Fabrizio De André", "Cantautore genovese"],
  ["Lucio Battisti", "Cantautore italiano"],
  ["Lucio Dalla", "Cantautore bolognese"],
  ["Mina", "Cantante italiana leggendaria"],
  ["Adriano Celentano", "Cantante e attore italiano"],
  ["Rino Gaetano", "Cantautore italiano"],
  ["Franco Battiato", "Cantautore filosofico"],
  ["Pino Daniele", "Cantautore napoletano"],
  ["Claudio Baglioni", "Cantautore romano"],
  ["Tiziano Ferro", "Cantante italiano"],
  ["Marco Mengoni", "Cantante italiano"],
  ["Elodie", "Cantante italiana"],
  ["Fedez", "Rapper italiano"],
  ["Achille Lauro", "Cantante eccentrico italiano"],
  ["Måneskin", "Band rock italiana"],
  ["Mahmood", "Cantante italiano"],
  ["Blanco", "Cantautore italiano"],
  ["Ultimo", "Cantautore romano"],
  ["Emma Marrone", "Cantante salentina"],
  ["Alessandra Amoroso", "Cantante salentina"],
  ["Nek", "Cantautore italiano"],
  ["Biagio Antonacci", "Cantautore milanese"],
  ["Gigi D'Alessio", "Cantautore napoletano"],
  ["Al Bano", "Cantante pugliese"],
  ["Romina Power", "Cantante americana italianizzata"],
  ["Toto Cutugno", "Cantautore italiano"],
  ["Umberto Tozzi", "Cantautore torinese"],
  ["Raffaella Carrà", "Showgirl e cantante"],
  ["Festival di Sanremo", "Kermesse canora italiana"],
  ["Eurovision", "Competizione canora europea"],
  ["Woodstock", "Festival rock storico"],
  ["Coachella", "Festival musicale americano"],
  ["Concertone", "Evento musicale gratuito"],
  ["Tour", "Serie di concerti"],
  ["Backstage", "Area dietro le quinte"],
  ["Palco", "Struttura per esibirsi"],
  ["Platea", "Area spettatori seduti"],
  ["Bis", "Ripetizione a fine concerto"],
  ["Fischietto", "Strumento a fiato semplice"],
  ["Microfono", "Attrezzo per cantare"],
  ["Amplificatore", "Dispositivo per il suono"],
  ["Mixer", "Console audio"],
  ["Cuffie", "Accessorio per ascoltare"],
  ["Cassa", "Diffusore audio"],
  ["Spartito", "Foglio con le note"],
  ["Metronomo", "Dispositivo per il tempo"],
  ["Accordo", "Insieme di note"],
  ["Melodia", "Sequenza di note"],
  ["Ritmo", "Cadenza musicale"],
  ["Testo", "Parole di una canzone"],
  ["Ritornello", "Parte ripetuta della canzone"],
  ["Strofa", "Sezione di una canzone"],
  ["Cover", "Rifacimento di un brano"],
  ["Remix", "Versione rielaborata di un brano"],
  ["Singolo", "Brano pubblicato da solo"],
  ["Album", "Raccolta di canzoni"],
  ["Vinile", "Disco musicale in analogico"],
  ["CD", "Disco musicale digitale"],
  ["MP3", "File audio compresso"],
  ["Streaming", "Ascolto musica online"],
  ["Playlist", "Lista di brani"],
  ["Podcast", "Programma audio a puntate"],
  ["Radio", "Mezzo di diffusione musicale"],
  ["DJ", "Selezionatore di musica"],
  ["Producer", "Creatore di basi musicali"],
  ["Cantautore", "Musicista che scrive e canta"],
  ["Solista", "Musicista senza gruppo"],
  ["Band", "Gruppo musicale"],
  ["Orchestra", "Grande gruppo classico"],
  ["Coro", "Gruppo di voci"],
  ["Direttore d'orchestra", "Guida musicale con bacchetta"],
  ["Fisarmonica", "Strumento a mantice"],
  ["Arpa", "Strumento a corde grande"],
  ["Sax", "Strumento a fiato jazz"],
  ["Contrabbasso", "Strumento a corde grave"],
  ["Ukulele", "Piccola chitarra hawaiana"],
  ["Mandolino", "Strumento a corde napoletano"],
  ["Cornamusa", "Strumento a sacca scozzese"],
  ["Xilofono", "Strumento a percussione di legno"],
  ["Triangolo", "Piccolo strumento metallico"],
  ["Tamburello", "Strumento a percussione zingaro"],
  ["Grancassa", "Grande tamburo"],
  ["Rullante", "Tamburo della batteria"],
  ["Piatti", "Elemento metallico della batteria"],
  ["Corista", "Cantante di supporto"],
  ["Fan club", "Gruppo di ammiratori organizzato"],
  ["Fandom", "Comunità di appassionati"],
  ["Autografo", "Firma di una celebrità"],
  ["Merchandising", "Prodotti a tema artista"],
  ["Biglietto", "Titolo d'accesso al concerto"],
  ["Prevendita", "Acquisto anticipato biglietti"],
  ["Sold out", "Tutti i posti esauriti"],
  ["Mosh pit", "Area concerto molto fisica"],
  ["Crowd surfing", "Passare sopra il pubblico"],
  ["Encore", "Richiesta di bis"],
  ["Sound check", "Prova tecnica pre-concerto"],
  ["Roadie", "Assistente tecnico tour"],
  ["Tour manager", "Organizzatore del tour"],
  ["Etichetta discografica", "Azienda musicale"],
  ["Talent show", "Programma tv di ricerca talenti"],
  ["The Voice", "Talent show cantanti"],
  ["X Factor", "Talent show musicale"],
  ["Amici", "Talent scuola italiano"],
  ["Provino", "Audizione musicale"],
  ["Casting", "Selezione per uno show"],
  ["Hit", "Canzone di grande successo"],
  ["Tormentone", "Canzone dell'estate"],
  ["Colonna sonora", "Musica di un film"],
  ["Sigla", "Musica introduttiva di un programma"],
  ["Inno", "Canzone celebrativa"],
  ["Ninna nanna", "Canzone per bambini"],
  ["Serenata", "Canzone d'amore sotto la finestra"],
  ["Filastrocca", "Canzoncina per bambini"],
  ["Canto gregoriano", "Musica religiosa medievale"],
  ["Musica classica", "Genere musicale colto"],
  ["Musica lirica", "Genere musicale cantato teatrale"],
  ["Musica leggera", "Genere musicale italiano radiofonico"],
  ["Musica elettronica", "Genere musicale digitale"],
  ["Musica folk", "Genere musicale popolare"],
  ["Musica country", "Genere musicale americano rurale"],
  ["Musica latina", "Genere musicale caraibico"],
  ["Salsa", "Ballo latino energico"],
  ["Tango", "Ballo argentino passionale"],
  ["Flamenco", "Ballo spagnolo con nacchere"],
  ["Bachata", "Ballo dominicano romantico"],
  ["Reggaeton", "Genere musicale urbano latino"],
  ["Cumbia", "Genere musicale colombiano"],
  ["Bossa nova", "Genere musicale brasiliano rilassato"],
  ["Samba", "Ballo brasiliano di carnevale"],
  ["Disco music", "Genere musicale da discoteca anni 70"],
  ["Funk", "Genere musicale con basso marcato"],
  ["Soul", "Genere musicale afroamericano"],
  ["Gospel", "Genere musicale religioso"],
  ["Hip hop", "Genere musicale urbano"],
  ["Trap", "Genere musicale urbano moderno"],
  ["Drill", "Genere musicale urbano aggressivo"],
  ["Indie", "Genere musicale indipendente"],
  ["Grunge", "Genere musicale anni Novanta"],
  ["Hard rock", "Genere musicale rock potente"],
  ["Prog rock", "Genere musicale rock complesso"],
  ["New wave", "Genere musicale anni 80"],
  ["Ska", "Genere musicale giamaicano ritmato"],
  ["Emo", "Genere musicale emotivo"],
  ["Dubstep", "Genere musicale elettronico basso"],
  ["House", "Genere musicale da club"],
  ["Trance", "Genere musicale elettronico ipnotico"],
  ["Ambient", "Genere musicale atmosferico"],
  ["Lo-fi", "Genere musicale rilassante da studio"],
  ["Sinfonia", "Composizione orchestrale grande"],
  ["Concerto per pianoforte", "Composizione solista con orchestra"],
  ["Quartetto d'archi", "Formazione di quattro musicisti classici"],
  ["Duetto", "Canzone a due voci"],
  ["Assolo", "Sezione musicale di un solo musicista"],
  ["Improvvisazione", "Musica creata sul momento"],
  ["Jam session", "Sessione musicale spontanea"],
  ["Prova generale", "Ultima prova prima del debutto"],
  ["Debutto", "Prima esibizione pubblica"],
  ["Addio alle scene", "Ultimo concerto di carriera"],
  ["Reunion", "Ritorno insieme di un gruppo"],
  ["Cover band", "Gruppo che suona brani altrui"],
  ["Tribute band", "Gruppo dedicato a un artista"],
  ["Musicista di strada", "Artista che suona all'aperto"],
  ["Buskers", "Musicisti di strada"],
  ["Cantante", "Ruolo musicale con voce"],
  ["Paroliere", "Autore di testi musicali"],
  ["Compositore", "Autore di musica"],
  ["Arrangiatore", "Chi organizza gli strumenti di un brano"],
  ["Turnista", "Musicista di sessione"],
  ["Diva", "Cantante di grande fama"],
  ["Idolo", "Artista molto amato"],
  ["Groupie", "Fan accanito di un artista"],
  ["Stonato", "Chi canta fuori tono"],
  ["Playback", "Canto simulato senza voce reale"],
  ["Voce", "Strumento naturale del cantante"],
  ["Falsetto", "Tecnica vocale acuta"],
  ["Vibrato", "Tecnica di oscillazione vocale"],
];
