export const MUSICA: [string, string][] = [
  ["Chitarra", "Strumento"],
  ["Pianoforte", "Strumento"],
  ["Batteria", "Strumento"],
  ["Karaoke", "Serata"],
  ["Sanremo", "Televisione"],
  ["Concerto", "Evento"],
  ["Cuffie", "Oggetto"],
  ["Vinile", "Nostalgia"],
  ["Ritornello", "Canzone"],
  ["Coro", "Gruppo"],
  ["Rap", "Genere"],
  ["Rock", "Genere"],
  ["Opera", "Teatro"],
  ["Dj", "Mestiere"],
  ["Playlist", "Ascolto"],
  ["Basso", "Strumento"],
  ["Violino", "Strumento"],
  ["Tromba", "Strumento"],
  ["Stonatura", "Errore"],
  ["Autotune", "Tecnologia"],
];
