export const MUSICA: [string, string][] = [
  ["Chitarra", "Sei corde"],
  ["Pianoforte", "Bianco e nero"],
  ["Batteria", "Vicini arrabbiati"],
  ["Karaoke", "Coraggio stonato"],
  ["Sanremo", "Febbraio televisivo"],
  ["Concerto", "Accendini alzati"],
  ["Cuffie", "Mondo isolato"],
  ["Vinile", "Fruscio"],
  ["Ritornello", "Testa incastrata"],
  ["Coro", "Voci insieme"],
  ["Rap", "Rime veloci"],
  ["Rock", "Distorsione"],
  ["Opera", "Loggione"],
  ["Dj", "Consolle"],
  ["Playlist", "Ordine personale"],
  ["Basso", "Vibrazione bassa"],
  ["Violino", "Archetto"],
  ["Tromba", "Ottone"],
  ["Stonatura", "Orecchie ferite"],
  ["Autotune", "Voce corretta"],
];
