export const POLITICI: [string, string][] = [
  ["Giorgia Meloni", "Garbatella"],
  ["Silvio Berlusconi", "Arcore"],
  ["Donald Trump", "Muro"],
  ["Vladimir Putin", "Cremlino"],
  ["Matteo Renzi", "Rottamatore"],
  ["Barack Obama", "Speranza"],
  ["Mario Draghi", "Whatever"],
  ["Matteo Salvini", "Citofono"],
  ["Giuseppe Conte", "Pochette"],
  ["Enrico Letta", "Parigi"],
  ["Romano Prodi", "Mortadella"],
  ["Giulio Andreotti", "Gobba"],
  ["Bettino Craxi", "Hammamet"],
  ["Aldo Moro", "Renault"],
  ["Sandro Pertini", "Pipa"],
  ["Sergio Mattarella", "Dignità"],
  ["Giorgio Napolitano", "Re"],
  ["Francesco Cossiga", "Picconatore"],
  ["Angela Merkel", "Giacca"],
  ["Emmanuel Macron", "Piramide"],
  ["Joe Biden", "Gaffe"],
  ["Hillary Clinton", "Marito"],
  ["George W. Bush", "Torri"],
  ["John F. Kennedy", "Dallas"],
  ["Margaret Thatcher", "Ferro"],
  ["Tony Blair", "Iraq"],
  ["Winston Churchill", "Sigaro"],
  ["Mahatma Gandhi", "Sale"],
  ["Nelson Mandela", "Cella"],
  ["Fidel Castro", "Barba"],
  ["Che Guevara", "Maglietta"],
  ["Mikhail Gorbaciov", "Macchia"],
  ["Ronald Reagan", "Attore"],
  ["Jacques Chirac", "Borsa"],
  ["Nicolas Sarkozy", "Modella"],
  ["Boris Johnson", "Parrucca"],
  ["Luigi Di Maio", "Bibitaro"],
  ["Beppe Grillo", "Vaffa"],
  ["Gianfranco Fini", "Montecarlo"],
  ["Umberto Bossi", "Canottiera"],
  ["Pier Luigi Bersani", "Smacchiatore"],
  ["Massimo D’Alema", "Barca"],
  ["Emma Bonino", "Radicale"],
  ["Marco Pannella", "Sciopero"],
  ["Elly Schlein", "Armocromia"],
  ["Carlo Calenda", "Twitter"],
  ["Nicola Fratoianni", "Sinistra"],
  ["Matteo Piantedosi", "Carico"],
  ["Antonio Tajani", "Erede"],
  ["Guido Crosetto", "Gigante"],
  ["Francesco Lollobrigida", "Cognato"],
  ["Daniela Santanchè", "Twiga"],
  ["Gennaro Sangiuliano", "Libri"],
  ["Matteo Messina Denaro", "Latitante"],
  ["Giovanni Falcone", "Capaci"],
  ["Paolo Borsellino", "Agenda"],
  ["Oscar Luigi Scalfaro", "Io non ci sto"],
  ["Carlo Azeglio Ciampi", "Moneta"],
  ["Giovanni Spadolini", "Storia"],
  ["Ciriaco De Mita", "Avellino"],
  ["Enrico Berlinguer", "Mani"],
  ["Palmiro Togliatti", "Migliore"],
  ["Alcide De Gasperi", "Ricostruzione"],
  ["Benito Mussolini", "Balcone"],
  ["Adolf Hitler", "Bunker"],
  ["Joseph Stalin", "Baffi"],
  ["Franklin D. Roosevelt", "Sedia"],
  ["Abraham Lincoln", "Cilindro"],
  ["George Washington", "Ciliegio"],
  ["Napoleone Bonaparte", "Mano"],
  ["Giulio Cesare", "Idi"],
  ["Augusto", "Impero"],
  ["Carlo Magno", "Corona"],
  ["Luigi XIV", "Sole"],
  ["Elisabetta II", "Cappellino"],
  ["Diana Spencer", "Tunnel"],
  ["Justin Trudeau", "Calzini"],
  ["Jair Bolsonaro", "Foresta"],
  ["Lula", "Sindacato"],
  ["Xi Jinping", "Miele"],
  ["Kim Jong-un", "Missile"],
  ["Bashar al-Assad", "Damasco"],
  ["Muammar Gheddafi", "Tenda"],
  ["Yasser Arafat", "Kefiah"],
  ["Ariel Sharon", "Muro"],
  ["Benjamin Netanyahu", "Bunker"],
  ["Volodymyr Zelensky", "Mimetica"],
  ["Viktor Orban", "Confine"],
  ["Theresa May", "Danza"],
  ["David Cameron", "Porcellino"],
  ["Jacinda Ardern", "Isola"],
  ["Greta Thunberg", "Venerdì"],
  ["Sanna Marin", "Festa"],
  ["Alexandria Ocasio-Cortez", "Green"],
  ["Bernie Sanders", "Guanti"],
  ["Kamala Harris", "Riso"],
  ["Michelle Obama", "Avvocato"],
  ["Melania Trump", "Passerella"],
  ["Brigitte Macron", "Scuola"],
  ["Carla Bruni", "Chitarra"],
  ["Valery Giscard d’Estaing", "Fisarmonica"],
  ["François Mitterrand", "Piramide"],
  ["François Hollande", "Motorino"],
  ["Pedro Sanchez", "Bello"],
  ["Mariano Rajoy", "Barba"],
  ["Jose Luis Zapatero", "Ritiro"],
  ["Silvio Pellico", "Prigioni"],
  ["Giuseppe Garibaldi", "Mille"],
  ["Camillo Benso di Cavour", "Occhialini"],
  ["Giuseppe Mazzini", "Giovine"],
  ["Vittorio Emanuele II", "Baffoni"],
  ["Umberto I", "Pane"],
  ["Vittorio Emanuele III", "Sciabola"],
  ["Enrico De Nicola", "Toga"],
  ["Luigi Einaudi", "Piemonte"],
  ["Antonio Segni", "Riforma"],
  ["Giuseppe Saragat", "Socialista"],
  ["Giovanni Leone", "Corna"],
  ["Ignazio La Russa", "Busti"],
  ["Lorenzo Fontana", "Famiglia"],
  ["Roberto Fico", "Autobus"],
  ["Laura Boldrini", "Web"],
  ["Piero Grasso", "Pizzo"],
  ["Renato Schifani", "Sicilia"],
  ["Marcello Pera", "Radici"],
  ["Franco Marini", "Lupo"],
  ["Fausto Bertinotti", "Cachemire"],
  ["Luciano Violante", "Giudice"],
  ["Irene Pivetti", "Padania"],
  ["Giorgio Almirante", "Fiammella"],
  ["Gianroberto Casaleggio", "Blog"],
  ["Davide Casaleggio", "Rousseau"],
  ["Alessandro Di Battista", "Zaino"],
  ["Roberto Speranza", "Mascherina"],
  ["Domenico Arcuri", "Primula"],
  ["Francesco Paolo Figliuolo", "Divisa"],
  ["Luca Zaia", "Dogado"],
  ["Stefano Bonaccini", "Occhiali"],
  ["Vincenzo De Luca", "Lanciafiamme"],
  ["Michele Emiliano", "Puglia"],
  ["Nello Musumeci", "Protezione"],
  ["Attilio Fontana", "Mascherina"],
  ["Giovanni Toti", "Liguria"],
  ["Maurizio Lupi", "Passione"],
  ["Gabriele D’Annunzio", "Fiume"],
  ["Filippo Tommaso Marinetti", "Futuro"],
  ["Giacomo Matteotti", "Discorso"],
  ["Antonio Gramsci", "Quaderni"],
  ["Nilde Iotti", "Donna"],
  ["Tina Anselmi", "P2"],
  ["Rosy Bindi", "Sanità"],
  ["Michela Vittoria Brambilla", "Animali"],
  ["Paola Taverna", "Urlo"],
  ["Nunzia De Girolamo", "Ballando"],
  ["Alessandra Mussolini", "Nonno"],
  ["Elisabetta Casellati", "Aereo"],
  ["Marta Cartabia", "Riforma"],
  ["Luciana Lamorgese", "Tecnica"],
  ["Paola De Micheli", "Ponti"],
  ["Teresa Bellanova", "Braccianti"],
  ["Elena Bonetti", "Assegno"],
  ["Fabiana Dadone", "Gaming"],
  ["Vittorio Sgarbi", "Capra"],
  ["Claudio Lotito", "Senatore"],
  ["Adriano Galliani", "Cravatta"],
  ["Claudio Martelli", "Nuovo"],
  ["Gianni Letta", "Ombra"],
  ["Fedele Confalonieri", "Pianoforte"],
  ["Marina Berlusconi", "Figlia"],
  ["Pier Silvio Berlusconi", "Palestra"],
  ["Barbara Berlusconi", "Stadio"],
  ["Gian Marco Chiocci", "Direttore"],
  ["Galeazzo Ciano", "Diari"],
  ["Italo Balbo", "Volo"],
  ["Giovanni Giolitti", "Età"],
  ["Francesco Crispi", "Sicilia"],
  ["Agostino Depretis", "Trasformismo"],
  ["Urbano Rattazzi", "Connubio"],
  ["Massimo d’Azeglio", "Fatti"],
  ["Lamberto Dini", "Tecnico"],
  ["Giuliano Amato", "Dottor Sottile"],
  ["Carlo Cottarelli", "Forbici"],
  ["Giancarlo Giorgetti", "Bocconi"],
  ["Elisabetta Belloni", "Servizi"],
  ["Franco Frattini", "Sci"],
  ["Renato Brunetta", "Tornelli"],
  ["Roberto Maroni", "Bobo"],
  ["Angelino Alfano", "Interni"],
  ["Maurizio Gasparri", "Twitter"],
  ["Daniela Santanchè", "Pitonessa"],
  ["Ignazio La Russa", "Faccetta"],
  ["Roberto Calderoli", "Porcellum"],
  ["Piero Fassino", "Profezia"],
  ["Dario Franceschini", "Cultura"],
  ["Andrea Orlando", "Spezia"],
  ["Paola De Micheli", "Piacenza"],
  ["Lorenzo Guerini", "Lodi"],
  ["Stefano Patuanelli", "Trieste"],
  ["Federico D’Incà", "Belluno"],
  ["Nunzia De Girolamo", "Benevento"],
];
