// Suggerimenti: ruolo/ambito generico, mai dettagli che identificano la persona.
export const POLITICI: [string, string][] = [
  ["Giorgia Meloni", "Politica italiana"],
  ["Silvio Berlusconi", "Politico italiano"],
  ["Donald Trump", "Politico americano"],
  ["Vladimir Putin", "Politico russo"],
  ["Matteo Renzi", "Politico italiano"],
  ["Barack Obama", "Politico americano"],
  ["Mario Draghi", "Politico economista"],
  ["Matteo Salvini", "Politico italiano"],
  ["Giuseppe Conte", "Politico italiano"],
  ["Enrico Letta", "Politico italiano"],
  ["Romano Prodi", "Politico italiano"],
  ["Giulio Andreotti", "Politico democristiano"],
  ["Bettino Craxi", "Politico socialista"],
  ["Aldo Moro", "Politico anni Settanta"],
  ["Sandro Pertini", "Politico del Quirinale"],
  ["Sergio Mattarella", "Politico del Quirinale"],
  ["Giorgio Napolitano", "Politico del Quirinale"],
  ["Francesco Cossiga", "Politico del Quirinale"],
  ["Angela Merkel", "Politica tedesca"],
  ["Emmanuel Macron", "Politico francese"],
  ["Joe Biden", "Politico americano"],
  ["John F. Kennedy", "Politico americano"],
  ["Margaret Thatcher", "Politica britannica"],
  ["Tony Blair", "Politico britannico"],
  ["Winston Churchill", "Politico britannico"],
  ["Mahatma Gandhi", "Leader indiano"],
  ["Nelson Mandela", "Leader africano"],
  ["Fidel Castro", "Leader caraibico"],
  ["Che Guevara", "Rivoluzionario sudamericano"],
  ["Mikhail Gorbaciov", "Politico sovietico"],
  ["Ronald Reagan", "Politico americano"],
  ["Nicolas Sarkozy", "Politico francese"],
  ["Boris Johnson", "Politico britannico"],
  ["Luigi Di Maio", "Politico italiano"],
  ["Beppe Grillo", "Fondatore di un partito"],
  ["Gianfranco Fini", "Politico italiano"],
  ["Umberto Bossi", "Politico del Nord"],
  ["Pier Luigi Bersani", "Politico di sinistra"],
  ["Massimo D’Alema", "Politico di sinistra"],
  ["Emma Bonino", "Politica radicale"],
  ["Marco Pannella", "Politico radicale"],
  ["Elly Schlein", "Politica di sinistra"],
  ["Carlo Calenda", "Politico centrista"],
  ["Antonio Tajani", "Politico italiano"],
  ["Guido Crosetto", "Politico di governo"],
  ["Daniela Santanchè", "Politica di governo"],
  ["Giovanni Falcone", "Magistrato italiano"],
  ["Paolo Borsellino", "Magistrato italiano"],
  ["Carlo Azeglio Ciampi", "Politico del Quirinale"],
  ["Enrico Berlinguer", "Politico comunista"],
  ["Palmiro Togliatti", "Politico comunista"],
  ["Alcide De Gasperi", "Politico del dopoguerra"],
  ["Benito Mussolini", "Dittatore europeo"],
  ["Adolf Hitler", "Dittatore europeo"],
  ["Joseph Stalin", "Dittatore sovietico"],
  ["Abraham Lincoln", "Politico americano"],
  ["George Washington", "Politico americano"],
  ["Napoleone Bonaparte", "Condottiero europeo"],
  ["Giulio Cesare", "Politico dell’antichità"],
  ["Carlo Magno", "Sovrano medievale"],
  ["Luigi XIV", "Sovrano francese"],
  ["Elisabetta II", "Sovrana britannica"],
  ["Diana Spencer", "Nobile britannica"],
  ["Xi Jinping", "Politico asiatico"],
  ["Kim Jong-un", "Dittatore asiatico"],
  ["Muammar Gheddafi", "Dittatore africano"],
  ["Yasser Arafat", "Leader mediorientale"],
  ["Benjamin Netanyahu", "Politico mediorientale"],
  ["Volodymyr Zelensky", "Politico dell’Est"],
  ["Viktor Orban", "Politico dell’Est"],
  ["Theresa May", "Politica britannica"],
  ["Greta Thunberg", "Attivista giovane"],
  ["Giuseppe Garibaldi", "Condottiero italiano"],
  ["Camillo Benso di Cavour", "Politico ottocentesco"],
  ["Giuseppe Mazzini", "Patriota italiano"],
  ["Vittorio Emanuele II", "Sovrano italiano"],
  ["Ignazio La Russa", "Politico di destra"],
  ["Roberto Fico", "Politico italiano"],
  ["Laura Boldrini", "Politica di sinistra"],
  ["Giorgio Almirante", "Politico di destra"],
  ["Roberto Speranza", "Politico di governo"],
  ["Luca Zaia", "Politico regionale"],
  ["Stefano Bonaccini", "Politico regionale"],
  ["Vincenzo De Luca", "Politico regionale"],
  ["Michele Emiliano", "Politico regionale"],
  ["Antonio Gramsci", "Pensatore politico"],
  ["Nilde Iotti", "Politica italiana"],
  ["Tina Anselmi", "Politica italiana"],
  ["Alessandra Mussolini", "Politica italiana"],
  ["Vittorio Sgarbi", "Personaggio polemico"],
  ["Giuliano Amato", "Politico italiano"],
  ["Giancarlo Giorgetti", "Politico di governo"],
  ["Roberto Maroni", "Politico del Nord"],
  ["Roberto Calderoli", "Politico del Nord"],
  ["Piero Fassino", "Politico di sinistra"],
  ["Dario Franceschini", "Politico italiano"],
  ["Giovanni Giolitti", "Politico ottocentesco"],
  ["Francesco Crispi", "Politico ottocentesco"],
  ["Lamberto Dini", "Politico tecnico"],
  ["Carlo Cottarelli", "Economista italiano"],
  ["Gabriele D’Annunzio", "Poeta italiano"],
  ["Giacomo Matteotti", "Politico italiano"],
];
