export const POLITICI: [string, string][] = [
  ["Giorgia Meloni", "Politica"],
  ["Silvio Berlusconi", "Politica"],
  ["Matteo Salvini", "Politica"],
  ["Giuseppe Conte", "Politica"],
  ["Sergio Mattarella", "Istituzioni"],
  ["Mario Draghi", "Istituzioni"],
  ["Matteo Renzi", "Politica"],
  ["Elly Schlein", "Politica"],
  ["Beppe Grillo", "Politica"],
  ["Donald Trump", "Estero"],
  ["Barack Obama", "Estero"],
  ["Vladimir Putin", "Estero"],
  ["Angela Merkel", "Estero"],
  ["Emmanuel Macron", "Estero"],
  ["Volodymyr Zelensky", "Estero"],
  ["Winston Churchill", "Passato"],
  ["Nelson Mandela", "Passato"],
  ["Giuseppe Garibaldi", "Passato"],
  ["Sandro Pertini", "Passato"],
  ["Aldo Moro", "Passato"],
];
