export const SCUOLA: [string, string][] = [
  ["Interrogazione", "Sudore freddo"],
  ["Bidello", "Corridoi"],
  ["Ricreazione", "Dieci minuti"],
  ["Pagella", "Giudizio a casa"],
  ["Lavagna", "Polvere"],
  ["Compito in classe", "Silenzio teso"],
  ["Copiare", "Occhio di lato"],
  ["Gita", "Pullman"],
  ["Zaino", "Peso"],
  ["Campanella", "Liberazione"],
  ["Maturità", "Estate temuta"],
  ["Preside", "Ufficio temuto"],
  ["Banco", "Scritte"],
  ["Ripetizioni", "Pomeriggio perso"],
  ["Diario", "Scarabocchi"],
  ["Verifica a sorpresa", "Panico"],
  ["Curriculum", "Prima impressione"],
  ["Colloquio", "Cravatta"],
  ["Stipendio", "Fine mese"],
  ["Ferie", "Conto alla rovescia"],
];
