export const SCUOLA: [string, string][] = [
  ["Interrogazione", "Prova"],
  ["Bidello", "Persona"],
  ["Ricreazione", "Pausa"],
  ["Pagella", "Giudizio"],
  ["Lavagna", "Oggetto"],
  ["Compito in classe", "Prova"],
  ["Copiare", "Furbizia"],
  ["Gita", "Uscita"],
  ["Zaino", "Oggetto"],
  ["Campanella", "Momento"],
  ["Maturità", "Traguardo"],
  ["Preside", "Persona"],
  ["Banco", "Oggetto"],
  ["Ripetizioni", "Pomeriggio"],
  ["Diario", "Oggetto"],
  ["Verifica a sorpresa", "Imprevisto"],
  ["Curriculum", "Lavoro"],
  ["Colloquio", "Lavoro"],
  ["Stipendio", "Lavoro"],
  ["Ferie", "Pausa"],
];
