export const SCUOLA: [string, string][] = [
  ["Interrogazione", "Sudore"],
  ["Compito in classe", "Silenzio"],
  ["Ricreazione", "Campanella"],
  ["Bocciatura", "Vergogna"],
  ["Promozione", "Sollievo"],
  ["Diploma", "Cornice"],
  ["Laurea", "Corona"],
  ["Tesi di laurea", "Notte"],
  ["Colloquio di lavoro", "Stretta"],
  ["Curriculum", "Font"],
  ["Lettera di motivazione", "Firma"],
  ["Stipendio", "Busta"],
  ["Straordinario", "Sbadiglio"],
  ["Ferie", "Valigia"],
  ["Malattia", "Certificato"],
  ["Contratto", "Clausola"],
  ["Licenziamento", "Scatolone"],
  ["Dimissioni", "Porta"],
  ["Promozione lavorativa", "Brindisi"],
  ["Riunione", "Calendario"],
  ["Call di lavoro", "Microfono"],
  ["Smart working", "Pantofole"],
  ["Pausa caffè", "Distributore"],
  ["Mensa aziendale", "Vassoio"],
  ["Ufficio open space", "Cuffie"],
  ["Capo", "Ombra"],
  ["Collega", "Scrivania"],
  ["Stagista", "Scatola"],
  ["Segretaria", "Agenda"],
  ["Contabile", "Scontrino"],
  ["Avvocato", "Toga"],
  ["Medico", "Camice"],
  ["Infermiere", "Turno"],
  ["Insegnante", "Gessetto"],
  ["Professore", "Cattedra"],
  ["Maestra", "Grembiule"],
  ["Preside", "Ufficio"],
  ["Bidello", "Chiave"],
  ["Studente", "Zaino"],
  ["Universitario", "Aula"],
  ["Dottorando", "Biblioteca"],
  ["Apprendista", "Cassetta"],
  ["Idraulico", "Chiave inglese"],
  ["Elettricista", "Cavo"],
  ["Muratore", "Casco"],
  ["Falegname", "Segatura"],
  ["Meccanico", "Olio"],
  ["Cuoco", "Grembiule"],
  ["Cameriere", "Vassoio"],
  ["Barista", "Tazzina"],
  ["Pasticciere", "Farina"],
  ["Panettiere", "Alba"],
  ["Contadino", "Stivale"],
  ["Pescatore", "Rete"],
  ["Pastore", "Bastone"],
  ["Sarto", "Ago"],
  ["Parrucchiere", "Forbici"],
  ["Estetista", "Specchio"],
  ["Postino", "Bicicletta"],
  ["Vigile urbano", "Fischietto"],
  ["Poliziotto", "Divisa"],
  ["Pompiere", "Elmetto"],
  ["Soldato", "Zaino"],
  ["Pilota", "Nuvola"],
  ["Assistente di volo", "Carrello"],
  ["Autista", "Volante"],
  ["Tassista", "Radio"],
  ["Giornalista", "Taccuino"],
  ["Fotografo", "Obiettivo"],
  ["Scrittore", "Penna"],
  ["Architetto", "Righello"],
  ["Ingegnere", "Elmetto"],
  ["Programmatore", "Tastiera"],
  ["Grafico", "Mouse"],
  ["Traduttore", "Dizionario"],
  ["Bibliotecario", "Scaffale"],
  ["Farmacista", "Bancone"],
  ["Veterinario", "Guinzaglio"],
  ["Notaio", "Sigillo"],
  ["Commercialista", "Fattura"],
  ["Banchiere", "Cassaforte"],
  ["Assicuratore", "Polizza"],
  ["Agente immobiliare", "Chiave"],
  ["Venditore", "Sorriso"],
  ["Cassiere", "Scontrino"],
  ["Magazziniere", "Scatola"],
  ["Corriere", "Pacco"],
  ["Elettricista scolastico", "Interruttore"],
  ["Custode", "Ronda"],
  ["Direttore", "Poltrona"],
  ["Amministratore delegato", "Grattacielo"],
  ["Socio", "Quota"],
  ["Imprenditore", "Rischio"],
  ["Freelance", "Fattura"],
  ["Partita IVA", "Codice"],
  ["Concorso pubblico", "Graduatoria"],
  ["Assunzione", "Firma"],
  ["Turnover", "Porta girevole"],
  ["Formazione aziendale", "Slide"],
  ["Corso di aggiornamento", "Attestato"],
  ["Team building", "Corda"],
  ["Brainstorming", "Post-it"],
  ["Deadline", "Orologio"],
  ["Progetto", "Scadenza"],
  ["Budget", "Foglio"],
  ["Bilancio", "Numero"],
  ["Fattura", "Timbro"],
  ["Ricevuta", "Scontrino"],
  ["Preventivo", "Cifra"],
  ["Ordine del giorno", "Elenco"],
  ["Verbale", "Firma"],
  ["Presentazione", "Proiettore"],
  ["Slide", "Cursore"],
  ["Powerpoint", "Animazione"],
  ["Excel", "Cella"],
  ["Email di lavoro", "Firma"],
  ["Spam aziendale", "Cestino"],
  ["Password", "Post-it"],
  ["Badge", "Tornello"],
  ["Cartellino", "Timbro"],
  ["Timbratura", "Orologio"],
  ["Straordinari non pagati", "Sospiro"],
  ["Sindacato", "Bandiera"],
  ["Sciopero", "Cartello"],
  ["Manifestazione", "Megafono"],
  ["Pensione", "Orologio"],
  ["TFR", "Busta"],
  ["Cassa integrazione", "Silenzio"],
  ["Disoccupazione", "Fila"],
  ["Centro per l'impiego", "Modulo"],
  ["Colloquio conoscitivo", "Camicia"],
  ["Selezione del personale", "Elenco"],
  ["Test attitudinale", "Cronometro"],
  ["Prova pratica", "Sudore"],
  ["Periodo di prova", "Ansia"],
  ["Contratto a tempo determinato", "Scadenza"],
  ["Contratto a tempo indeterminato", "Sollievo"],
  ["Apprendistato", "Manuale"],
  ["Mentore", "Consiglio"],
  ["Feedback", "Nota"],
  ["Valutazione delle performance", "Grafico"],
  ["Aumento di stipendio", "Sorriso"],
  ["Bonus", "Busta"],
  ["Tredicesima", "Regalo"],
  ["Ferie estive", "Valigia"],
  ["Congedo parentale", "Culla"],
  ["Maternità", "Pancione"],
  ["Paternità", "Culla"],
  ["Pausa pranzo", "Panino"],
  ["Aula magna", "Microfono"],
  ["Lezione frontale", "Lavagna"],
  ["Compito a casa", "Diario"],
  ["Verifica", "Penna rossa"],
  ["Voto", "Registro"],
  ["Pagella", "Busta"],
  ["Registro elettronico", "Password"],
  ["Gita scolastica", "Pullman"],
  ["Ricreazione lunga", "Cortile"],
  ["Gessetto", "Polvere"],
  ["Lavagna", "Cancellino"],
  ["Diario scolastico", "Adesivo"],
  ["Astuccio", "Cerniera"],
  ["Zaino scolastico", "Peso"],
  ["Quaderno", "Riga"],
  ["Matita", "Punta"],
  ["Penna", "Inchiostro"],
  ["Gomma", "Briciola"],
  ["Righello", "Bordo"],
  ["Compasso", "Punta"],
  ["Squadra", "Angolo"],
  ["Colla stick", "Odore"],
  ["Temperino", "Trucioli"],
  ["Evidenziatore", "Colore"],
  ["Libro di testo", "Copertina"],
  ["Vocabolario", "Peso"],
  ["Atlante", "Confine"],
  ["Mappa geografica", "Colore"],
  ["Globo terrestre", "Rotazione"],
  ["Microscopio", "Lente"],
  ["Provetta", "Etichetta"],
  ["Laboratorio scientifico", "Camice"],
  ["Palestra scolastica", "Fischietto"],
  ["Educazione fisica", "Tuta"],
  ["Ricreazione in cortile", "Pallone"],
  ["Mensa scolastica", "Vassoio"],
  ["Scuolabus", "Fermata"],
  ["Campanella", "Suono"],
  ["Esame di maturità", "Ansia"],
  ["Tesina", "Rilegatura"],
  ["Commissione d'esame", "Tavolo"],
  ["Orale", "Domanda"],
  ["Scritto", "Penna"],
  ["Debito formativo", "Recupero"],
  ["Recupero estivo", "Caldo"],
  ["Sospensione", "Sedia"],
  ["Nota disciplinare", "Firma"],
  ["Circolare scolastica", "Bacheca"],
  ["Assemblea di classe", "Sedie"],
  ["Consiglio di classe", "Verbale"],
  ["Colloquio con i genitori", "Sedia"],
  ["Rappresentante di classe", "Elezione"],
  ["Supplente", "Registro"],
  ["Preside severo", "Silenzio"],
  ["Bidello gentile", "Chiave"],
  ["Aula informatica", "Tastiera"],
  ["Biblioteca scolastica", "Silenzio"],
  ["Materia preferita", "Sorriso"],
  ["Matematica", "Formula"],
  ["Italiano", "Tema"],
  ["Storia dell'arte", "Diapositiva"],
  ["Filosofia", "Domanda"],
  ["Chimica", "Provetta"],
  ["Fisica", "Formula"],
  ["Biologia", "Cellula"],
  ["Geografia", "Mappa"],
  ["Latino", "Declinazione"],
  ["Inglese", "Grammatica"],
  ["Educazione civica", "Regola"],
  ["Musica scolastica", "Flauto"],
  ["Disegno tecnico", "Riga"],
  ["Religione", "Aula"],
  ["Scienze motorie", "Fischietto"],
];
