export const SERIE_TV: [string, string][] = [
  ["Gomorra", "Italiana"],
  ["Breaking Bad", "Culto"],
  ["Il Trono di Spade", "Fantasy"],
  ["Stranger Things", "Nostalgia"],
  ["La Casa di Carta", "Successo"],
  ["Friends", "Nostalgia"],
  ["The Office", "Comica"],
  ["Lost", "Mistero"],
  ["Dr. House", "Personaggio"],
  ["Squid Game", "Successo"],
  ["Mare Fuori", "Italiana"],
  ["Il Commissario Montalbano", "Italiana"],
  ["Black Mirror", "Inquietudine"],
  ["The Walking Dead", "Paura"],
  ["Suits", "Lavoro"],
  ["Netflix", "Piattaforma"],
  ["Binge watching", "Abitudine"],
  ["Spoiler", "Fastidio"],
  ["Sigla", "Inizio"],
  ["Finale di stagione", "Attesa"],
];
