export const SERIE_TV: [string, string][] = [
  ["Breaking Bad", "Trasformazione"],
  ["Game of Thrones", "Ambizione"],
  ["Friends", "Complicità"],
  ["The Office", "Imbarazzo"],
  ["Stranger Things", "Nostalgia"],
  ["The Crown", "Formalità"],
  ["Peaky Blinders", "Freddezza"],
  ["Narcos", "Ambizione"],
  ["Dark", "Confusione"],
  ["La casa di carta", "Astuzia"],
  ["Sherlock", "Deduzione"],
  ["Suits", "Ambizione"],
  ["How I Met Your Mother", "Attesa"],
  ["The Big Bang Theory", "Imbarazzo"],
  ["Grey's Anatomy", "Emozione"],
  ["Lost", "Mistero"],
  ["Prison Break", "Tensione"],
  ["Dexter", "Doppiezza"],
  ["House of Cards", "Ambizione"],
  ["The Walking Dead", "Sopravvivenza"],
  ["Vikings", "Onore"],
  ["Downton Abbey", "Etichetta"],
  ["Sherlock Holmes", "Intuito"],
  ["Sex and the City", "Amicizia"],
  ["Gossip Girl", "Pettegolezzo"],
  ["Pretty Little Liars", "Sospetto"],
  ["Riverdale", "Segreto"],
  ["13 Reasons Why", "Silenzio"],
  ["Elite", "Ambizione"],
  ["Skam Italia", "Adolescenza"],
  ["Mare Fuori", "Redenzione"],
  ["Gomorra", "Potere"],
  ["Suburra", "Ombra"],
  ["Romanzo Criminale", "Nostalgia"],
  ["Il Commissario Montalbano", "Abitudine"],
  ["Don Matteo", "Fede"],
  ["Un posto al sole", "Continuità"],
  ["Che Dio ci aiuti", "Speranza"],
  ["Rocco Schiavone", "Cinismo"],
  ["L'Amica Geniale", "Amicizia"],
  ["Doc Nelle tue mani", "Memoria"],
  ["Blanca", "Percezione"],
  ["Il Paradiso delle Signore", "Eleganza"],
  ["Vita in Diretta", "Attualità"],
  ["Chi l'ha visto", "Sospetto"],
  ["Le Iene", "Provocazione"],
  ["Report", "Inchiesta"],
  ["Porta a Porta", "Dibattito"],
  ["Ballando con le Stelle", "Applauso"],
  ["Amici", "Sacrificio"],
  ["Uomini e Donne", "Corteggiamento"],
  ["C'è posta per te", "Commozione"],
  ["Tale e Quale Show", "Imitazione"],
  ["Il Cantante Mascherato", "Sorpresa"],
  ["Grande Fratello", "Convivenza"],
  ["Grande Fratello Vip", "Gossip"],
  ["Isola dei Famosi", "Fame"],
  ["Temptation Island", "Gelosia"],
  ["MasterChef Italia", "Pressione"],
  ["Bake Off Italia", "Precisione"],
  ["Cucine da Incubo", "Tensione"],
  ["4 Ristoranti", "Rivalità"],
  ["Ciao Darwin", "Ironia"],
  ["Striscia la Notizia", "Satira"],
  ["Zelig", "Risata"],
  ["Sanremo", "Emozione"],
  ["X Factor", "Talento"],
  ["The Voice of Italy", "Sorpresa"],
  ["Italia's Got Talent", "Stupore"],
  ["Pechino Express", "Fatica"],
  ["Ballando sotto le stelle", "Coreografia"],
  ["Report Rai", "Verità"],
  ["Quarto Grado", "Tensione"],
  ["Chi", "Curiosità"],
  ["Verissimo", "Confessione"],
  ["Domenica In", "Tradizione"],
  ["Che Tempo Che Fa", "Attualità"],
  ["Propaganda Live", "Ironia"],
  ["Le Iene Show", "Denuncia"],
  ["Un Medico in Famiglia", "Affetto"],
  ["I Cesaroni", "Caos"],
  ["Boris", "Sarcasmo"],
  ["1992", "Corruzione"],
  ["1993", "Ambizione"],
  ["Zerocalcare - Strappare lungo i bordi", "Ansia"],
  ["Curon", "Mistero"],
  ["Baby", "Ribellione"],
  ["Summertime", "Estate"],
  ["Diavoli", "Potere"],
  ["Petra", "Intuito"],
  ["Il Processo", "Dubbio"],
  ["La Porta Rossa", "Mistero"],
  ["Nero a Metà", "Ombra"],
  ["I Bastardi di Pizzofalcone", "Riscatto"],
  ["Nudes", "Vergogna"],
  ["Scomparsa", "Angoscia"],
  ["Che Dio ci aiuti 7", "Fede"],
  ["Doc - Nelle tue mani 2", "Memoria"],
  ["Studio Battaglia", "Determinazione"],
  ["Vincenzo Malinconico", "Ironia"],
  ["Sopravvissuti", "Trauma"],
  ["Fedeltà", "Tradimento"],
  ["Il Re", "Potere"],
  ["Cinque Minuti", "Silenzio"],
  ["Speravo de morì prima", "Nostalgia"],
  ["The Good Doctor", "Empatia"],
  ["This Is Us", "Commozione"],
  ["Modern Family", "Ironia"],
  ["Two and a Half Men", "Comicità"],
  ["Scrubs", "Assurdità"],
  ["ER", "Adrenalina"],
  ["House M.D.", "Diagnosi"],
  ["The Blacklist", "Enigma"],
  ["Homeland", "Paranoia"],
  ["24", "Urgenza"],
  ["Fargo", "Assurdità"],
  ["True Detective", "Ossessione"],
  ["Better Call Saul", "Ambizione"],
  ["Ozark", "Compromesso"],
  ["Mindhunter", "Analisi"],
  ["The Sopranos", "Doppia vita"],
  ["Boardwalk Empire", "Ambizione"],
  ["The Wire", "Sistema"],
  ["Mad Men", "Fumo"],
  ["The Handmaid's Tale", "Oppressione"],
  ["Orange Is the New Black", "Convivenza"],
  ["Black Mirror", "Inquietudine"],
  ["Westworld", "Identità"],
  ["The Mandalorian", "Solitudine"],
  ["The Witcher", "Destino"],
  ["Bridgerton", "Etichetta"],
  ["Outlander", "Nostalgia"],
  ["Vikings Valhalla", "Onore"],
  ["The Last of Us", "Sopravvivenza"],
  ["Chernobyl", "Silenzio"],
  ["Band of Brothers", "Fratellanza"],
  ["Euphoria", "Vertigine"],
  ["Sex Education", "Imbarazzo"],
  ["You", "Ossessione"],
  ["Money Heist", "Astuzia"],
  ["Dark Desire", "Tentazione"],
  ["Elite Squad", "Tensione"],
  ["Squid Game", "Disperazione"],
  ["Kingdom", "Contagio"],
  ["Vincenzo", "Astuzia"],
  ["Crash Landing on You", "Destino"],
  ["Goblin", "Malinconia"],
  ["Descendants of the Sun", "Sacrificio"],
  ["It's Okay to Not Be Okay", "Guarigione"],
  ["Hotel del Luna", "Eternità"],
  ["Reply 1988", "Nostalgia"],
  ["Itaewon Class", "Riscatto"],
  ["Alice in Borderland", "Sopravvivenza"],
  ["Terrace House", "Osservazione"],
  ["Terrace House Italia", "Curiosità"],
  ["Love Island Italia", "Gelosia"],
  ["Ex on the Beach Italia", "Imbarazzo"],
  ["Il Collegio", "Disciplina"],
  ["Naked Attraction Italia", "Imbarazzo"],
  ["Selling Sunset", "Ambizione"],
  ["Below Deck", "Convivenza"],
  ["The Kardashians", "Eccesso"],
  ["Queer Eye", "Trasformazione"],
  ["RuPaul's Drag Race", "Espressione"],
  ["The Voice Kids", "Innocenza"],
  ["Junior Bake Off", "Innocenza"],
  ["Amici Celebrities", "Sfida"],
  ["Il Collegio Vip", "Ironia"],
  ["Battiti Live", "Estate"],
  ["Wind Music Awards", "Applauso"],
  ["Festivalbar", "Nostalgia"],
  ["Karaoke", "Imbarazzo"],
  ["Lo Show dei Record", "Stupore"],
  ["Colorado", "Assurdità"],
  ["Made in Sud", "Risata"],
  ["Comedy Central", "Ironia"],
  ["Splendida Cornice", "Approfondimento"],
  ["Otto e Mezzo", "Dibattito"],
  ["Piazzapulita", "Confronto"],
  ["DiMartedì", "Polemica"],
  ["Non è l'Arena", "Provocazione"],
  ["Le Storie", "Emozione"],
  ["Presa Diretta", "Inchiesta"],
  ["Petrolio", "Approfondimento"],
  ["Filorosso", "Cronaca"],
  ["Storie Italiane", "Quotidianità"],
  ["La Vita in Diretta Estate", "Leggerezza"],
  ["Detto Fatto", "Praticità"],
  ["La Prova del Cuoco", "Tradizione"],
  ["È sempre mezzogiorno", "Convivialità"],
  ["Linea Verde", "Tranquillità"],
  ["Geo", "Curiosità"],
  ["SuperQuark", "Meraviglia"],
  ["Alberto Angela - Ulisse", "Fascino"],
  ["Voyager", "Enigma"],
  ["Mistero", "Suspense"],
  ["Freedom - Oltre il Confine", "Libertà"],
  ["Quinta Colonna", "Polemica"],
  ["Fuori dal Coro", "Provocazione"],
  ["Dritto e Rovescio", "Confronto"],
  ["Zona Bianca", "Attualità"],
  ["Tg satira", "Ironia"],
  ["Realiti", "Sperimentazione"],
  ["Belve", "Provocazione"],
  ["Splendida Vita", "Riflessione"],
  ["Stasera Tutto è Possibile", "Assurdità"],
  ["Password", "Competizione"],
  ["L'Eredità", "Suspense"],
  ["Reazione a Catena", "Alleanza"],
  ["Avanti un Altro", "Assurdità"],
  ["Caduta Libera", "Velocità"],
  ["Chi vuol essere milionario", "Ansia"],
];
