export const SERIE_TV: [string, string][] = [
  ["Breaking Bad", "Serie tv insegnante chimica"],
  ["Game of Thrones", "Serie tv fantasy troni"],
  ["Friends", "Sitcom gruppo di amici"],
  ["The Office", "Sitcom ufficio americano"],
  ["Stranger Things", "Serie tv mistero anni 80"],
  ["The Crown", "Serie tv monarchia inglese"],
  ["Peaky Blinders", "Serie tv gangster inglesi"],
  ["Narcos", "Serie tv narcotraffico colombiano"],
  ["Dark", "Serie tv fantascienza tedesca"],
  ["La casa di carta", "Serie tv rapina spagnola"],
  ["Sherlock", "Serie tv detective inglese"],
  ["Suits", "Serie tv avvocati newyorkesi"],
  ["How I Met Your Mother", "Sitcom racconto amoroso"],
  ["The Big Bang Theory", "Sitcom scienziati nerd"],
  ["Grey's Anatomy", "Serie tv medica ospedale"],
  ["Lost", "Serie tv naufraghi isola"],
  ["Prison Break", "Serie tv fuga di prigione"],
  ["Dexter", "Serie tv serial killer analista"],
  ["House of Cards", "Serie tv politica americana"],
  ["The Walking Dead", "Serie tv zombie apocalisse"],
  ["Vikings", "Serie tv guerrieri norreni"],
  ["Downton Abbey", "Serie tv aristocrazia inglese"],
  ["Sherlock Holmes", "Serie tv detective londinese"],
  ["Sex and the City", "Serie tv amiche newyorkesi"],
  ["Gossip Girl", "Serie tv liceali newyorkesi"],
  ["Pretty Little Liars", "Serie tv mistero adolescenziale"],
  ["Riverdale", "Serie tv teen drama misterioso"],
  ["13 Reasons Why", "Serie tv drammatico adolescenziale"],
  ["Elite", "Serie tv liceo spagnolo"],
  ["Skam Italia", "Serie tv adolescenti italiana"],
  ["Mare Fuori", "Serie tv carcere minorile napoletano"],
  ["Gomorra", "Serie tv camorra napoletana"],
  ["Suburra", "Serie tv crime romano"],
  ["Romanzo Criminale", "Serie tv banda romana anni 70"],
  ["Il Commissario Montalbano", "Serie tv poliziesco siciliano"],
  ["Don Matteo", "Serie tv prete investigatore"],
  ["Un posto al sole", "Soap opera napoletana"],
  ["Che Dio ci aiuti", "Serie tv suora"],
  ["Rocco Schiavone", "Serie tv poliziesco valdostano"],
  ["L'Amica Geniale", "Serie tv amicizia napoletana"],
  ["Doc Nelle tue mani", "Serie tv medico amnesia"],
  ["Blanca", "Serie tv poliziesco protagonista non vedente"],
  ["Il Paradiso delle Signore", "Soap opera grande magazzino"],
  ["Vita in Diretta", "Programma tv attualità pomeridiano"],
  ["Chi l'ha visto", "Programma tv persone scomparse"],
  ["Le Iene", "Programma tv inchieste satiriche"],
  ["Report", "Programma tv giornalismo inchiesta"],
  ["Porta a Porta", "Programma tv talk politico"],
  ["Ballando con le Stelle", "Talent show ballo tv"],
  ["Amici", "Talent show scuola artisti"],
  ["Uomini e Donne", "Programma tv incontri sentimentali"],
  ["C'è posta per te", "Programma tv riconciliazioni"],
  ["Tale e Quale Show", "Programma tv di imitazioni"],
  ["Il Cantante Mascherato", "Talent show maschere musicali"],
  ["Grande Fratello", "Reality show casa condivisa"],
  ["Grande Fratello Vip", "Reality show vip in casa"],
  ["Isola dei Famosi", "Reality show naufraghi vip"],
  ["Temptation Island", "Reality show coppie in crisi"],
  ["MasterChef Italia", "Talent show cucina"],
  ["Bake Off Italia", "Talent show pasticceria"],
  ["Cucine da Incubo", "Programma tv ristoranti in crisi"],
  ["4 Ristoranti", "Programma tv di cucina"],
  ["Ciao Darwin", "Programma tv scherzoso sfide"],
  ["Striscia la Notizia", "Programma tv satirico serale"],
  ["Zelig", "Programma tv comici cabaret"],
  ["Sanremo", "Programma tv festival canzone"],
  ["X Factor", "Talent show musicale"],
  ["The Voice of Italy", "Talent show cantanti voce"],
  ["Italia's Got Talent", "Programma tv di talenti"],
  ["Pechino Express", "Reality show viaggio avventuroso"],
  ["Ballando sotto le stelle", "Programma tv ballo spinoff"],
  ["Report Rai", "Programma tv giornalismo Rai"],
  ["Quarto Grado", "Programma tv casi di cronaca"],
  ["Chi", "Rivista tv gossip vip"],
  ["Verissimo", "Programma tv interviste vip"],
  ["Domenica In", "Programma tv intrattenimento domenicale"],
  ["Che Tempo Che Fa", "Talk show attualità"],
  ["Propaganda Live", "Programma tv satirico politico"],
  ["Le Iene Show", "Programma tv inchieste satiriche"],
  ["Un Medico in Famiglia", "Serie tv familiare italiana"],
  ["I Cesaroni", "Serie tv famiglia romana"],
  ["Boris", "Serie tv dietro le quinte tv"],
  ["1992", "Serie tv politica corruzione"],
  ["1993", "Serie tv politica seconda repubblica"],
  ["Zerocalcare - Strappare lungo i bordi", "Serie animata autobiografica italiana"],
  ["Curon", "Serie tv mistero italiano lago"],
  ["Baby", "Serie tv adolescenti romani"],
  ["Summertime", "Serie tv estivo romantico"],
  ["Diavoli", "Serie tv thriller bancario"],
  ["Petra", "Serie tv poliziesco investigatrice"],
  ["Il Processo", "Serie tv legale italiano"],
  ["La Porta Rossa", "Serie tv poliziesco soprannaturale"],
  ["Nero a Metà", "Serie tv poliziesco napoletano"],
  ["I Bastardi di Pizzofalcone", "Serie tv poliziesco squadra"],
  ["Nudes", "Serie tv adolescenti social"],
  ["Scomparsa", "Serie tv mistero sparizione"],
  ["Che Dio ci aiuti 7", "Serie tv suora stagione"],
  ["Doc - Nelle tue mani 2", "Serie tv medico stagione"],
  ["Studio Battaglia", "Serie tv avvocate italiane"],
  ["Vincenzo Malinconico", "Serie tv avvocato comico"],
  ["Sopravvissuti", "Serie tv mistero naufragio"],
  ["Fedeltà", "Serie tv drammatico coppia"],
  ["Il Re", "Serie tv carcere corruzione"],
  ["Cinque Minuti", "Film tv sequestro giornalista"],
  ["Speravo de morì prima", "Serie tv biografica calciatore"],
  ["The Good Doctor", "Serie tv medico autistico"],
  ["This Is Us", "Serie tv drammatico famiglia"],
  ["Modern Family", "Sitcom famiglia allargata"],
  ["Two and a Half Men", "Sitcom fratelli americani"],
  ["Scrubs", "Sitcom ospedaliera"],
  ["ER", "Serie tv medica pronto soccorso"],
  ["House M.D.", "Serie tv medico scorbutico"],
  ["The Blacklist", "Serie tv criminale informatore"],
  ["Homeland", "Serie tv spionaggio terrorismo"],
  ["24", "Serie tv antiterrorismo tempo reale"],
  ["Fargo", "Serie tv crime nevoso"],
  ["True Detective", "Serie tv poliziesco antologico"],
  ["Better Call Saul", "Serie tv avvocato spinoff"],
  ["Ozark", "Serie tv riciclaggio denaro"],
  ["Mindhunter", "Serie tv investigativa"],
  ["The Sopranos", "Serie tv boss mafioso"],
  ["Boardwalk Empire", "Serie tv proibizionismo americano"],
  ["The Wire", "Serie tv poliziesca"],
  ["Mad Men", "Serie tv pubblicitari anni 60"],
  ["The Handmaid's Tale", "Serie tv distopico patriarcale"],
  ["Orange Is the New Black", "Serie tv carcere femminile"],
  ["Black Mirror", "Serie tv antologia tecnologica"],
  ["Westworld", "Serie tv parco robot fantascienza"],
  ["The Mandalorian", "Serie tv fantascienza spaziale spinoff"],
  ["The Witcher", "Serie tv fantasy cacciatore mostri"],
  ["Bridgerton", "Serie tv romantico epoca regency"],
  ["Outlander", "Serie tv viaggio nel tempo scozzese"],
  ["Vikings Valhalla", "Serie tv guerrieri norreni spinoff"],
  ["The Last of Us", "Serie tv fantascienza post pandemia"],
  ["Chernobyl", "Miniserie disastro nucleare"],
  ["Band of Brothers", "Serie tv guerra reduci"],
  ["Euphoria", "Serie tv adolescenti droga"],
  ["Sex Education", "Serie tv liceo educazione sessuale"],
  ["You", "Serie tv thriller stalker"],
  ["Money Heist", "Serie tv rapina spagnola"],
  ["Dark Desire", "Serie tv thriller passionale messicano"],
  ["Elite Squad", "Serie tv poliziesco brasiliano"],
  ["Squid Game", "Serie tv giochi mortali coreano"],
  ["Kingdom", "Serie tv zombie storico coreano"],
  ["Vincenzo", "Serie tv avvocato mafioso coreano"],
  ["Crash Landing on You", "Serie tv romantica orientale"],
  ["Goblin", "Serie tv fantasy immortale coreano"],
  ["Descendants of the Sun", "Serie tv militare romantico coreano"],
  ["It's Okay to Not Be Okay", "Serie tv romantico psichiatrico coreano"],
  ["Hotel del Luna", "Serie tv fantasy orientale"],
  ["Reply 1988", "Serie tv nostalgico quartiere coreano"],
  ["Itaewon Class", "Serie tv riscatto ristorante coreano"],
  ["Alice in Borderland", "Serie tv giochi mortali giapponese"],
  ["Terrace House", "Reality show giapponese convivenza"],
  ["Terrace House Italia", "Reality show italiano convivenza"],
  ["Love Island Italia", "Reality show italiano coppie"],
  ["Ex on the Beach Italia", "Reality show italiano ex fidanzati"],
  ["Il Collegio", "Reality show scuola anni passati"],
  ["Naked Attraction Italia", "Reality show dating nudo"],
  ["Selling Sunset", "Reality show agenti immobiliari"],
  ["Below Deck", "Reality show equipaggio yacht"],
  ["The Kardashians", "Reality show famiglia celebrità"],
  ["Queer Eye", "Reality show trasformazione stile"],
  ["RuPaul's Drag Race", "Programma tv di travestimenti"],
  ["The Voice Kids", "Talent show cantanti bambini"],
  ["Junior Bake Off", "Talent show pasticceria bambini"],
  ["Amici Celebrities", "Talent show vip artisti"],
  ["Il Collegio Vip", "Reality show scuola vip"],
  ["Battiti Live", "Evento tv musicale estivo"],
  ["Wind Music Awards", "Evento tv premiazione musicale"],
  ["Festivalbar", "Evento tv musicale storico"],
  ["Karaoke", "Programma tv gara di canto amatoriale"],
  ["Lo Show dei Record", "Programma tv di imprese"],
  ["Colorado", "Programma tv comico sketch"],
  ["Made in Sud", "Programma tv comico napoletano"],
  ["Comedy Central", "Canale tv comico"],
  ["Splendida Cornice", "Programma tv cultura approfondimento"],
  ["Otto e Mezzo", "Talk show politico serale"],
  ["Piazzapulita", "Talk show politico"],
  ["DiMartedì", "Talk show politico settimanale"],
  ["Non è l'Arena", "Talk show inchiesta politica"],
  ["Le Storie", "Programma tv racconti sociali"],
  ["Presa Diretta", "Programma tv giornalismo inchiesta"],
  ["Petrolio", "Programma tv inchiesta economica"],
  ["Filorosso", "Programma tv attualità politica"],
  ["Storie Italiane", "Programma tv attualità mattutino"],
  ["La Vita in Diretta Estate", "Programma tv attualità estivo"],
  ["Detto Fatto", "Programma tv lifestyle pomeridiano"],
  ["La Prova del Cuoco", "Programma tv cucina storico"],
  ["È sempre mezzogiorno", "Programma tv cucina mattutino"],
  ["Linea Verde", "Programma tv agricoltura natura"],
  ["Geo", "Programma tv documentario natura"],
  ["SuperQuark", "Programma tv scientifico divulgativo"],
  ["Alberto Angela - Ulisse", "Programma tv documentario storico"],
  ["Voyager", "Programma tv misteri e enigmi"],
  ["Mistero", "Programma tv casi paranormali"],
  ["Freedom - Oltre il Confine", "Programma tv misteri esplorazione"],
  ["Quinta Colonna", "Talk show politico serale"],
  ["Fuori dal Coro", "Talk show provocatorio politico"],
  ["Dritto e Rovescio", "Talk show politico serale"],
  ["Zona Bianca", "Talk show attualità politica"],
  ["Tg satira", "Notiziario comico parodia"],
  ["Realiti", "Programma tv sperimentale Rai"],
  ["Belve", "Programma tv interviste pungenti"],
  ["Splendida Vita", "Programma tv attualità sociale"],
  ["Stasera Tutto è Possibile", "Programma tv comico giochi assurdi"],
  ["Password", "Gioco tv parole indovinello"],
  ["L'Eredità", "Quiz show preserale Rai"],
  ["Reazione a Catena", "Quiz show squadre parole"],
  ["Avanti un Altro", "Quiz show comico preserale"],
  ["Caduta Libera", "Quiz show botola risposte"],
  ["Chi vuol essere milionario", "Quiz show vincita finale"],
];
