export const SPORT: [string, string][] = [
  ["Maratona", "Fatica"],
  ["Nuoto", "Acqua"],
  ["Tennis", "Disciplina"],
  ["Basket", "Squadra"],
  ["Pallavolo", "Squadra"],
  ["Sci", "Inverno"],
  ["Ciclismo", "Strada"],
  ["Palestra", "Luogo"],
  ["Yoga", "Calma"],
  ["Boxe", "Scontro"],
  ["Scherma", "Disciplina"],
  ["Olimpiadi", "Evento"],
  ["Medaglia", "Premio"],
  ["Arbitro", "Ruolo"],
  ["Allenatore", "Ruolo"],
  ["Doping", "Scandalo"],
  ["Cronometro", "Misura"],
  ["Podio", "Premio"],
  ["Riscaldamento", "Prima"],
  ["Infortunio", "Stop"],
];
