export const SPORT: [string, string][] = [
  ["Maratona", "Chilometri infiniti"],
  ["Nuoto", "Cloro"],
  ["Tennis", "Racchetta"],
  ["Basket", "Canestro"],
  ["Pallavolo", "Muro"],
  ["Sci", "Neve veloce"],
  ["Ciclismo", "Salita"],
  ["Palestra", "Specchi"],
  ["Yoga", "Respiro"],
  ["Boxe", "Guantoni"],
  ["Scherma", "Stoccata"],
  ["Olimpiadi", "Cinque cerchi"],
  ["Medaglia", "Collo"],
  ["Arbitro", "Fischietto"],
  ["Allenatore", "Urla bordo"],
  ["Doping", "Provetta"],
  ["Cronometro", "Centesimi"],
  ["Podio", "Tre gradini"],
  ["Riscaldamento", "Prima del via"],
  ["Infortunio", "Ghiaccio"],
];
