export const SPORT: [string, string][] = [
  ["Tennis", "Corda"],
  ["Basket", "Tabellone"],
  ["Formula 1", "Casco"],
  ["Nuoto", "Cloro"],
  ["Ciclismo", "Pedale"],
  ["Atletica", "Staffetta"],
  ["Pallavolo", "Muro"],
  ["Boxe", "Ring"],
  ["Sci", "Bastoncini"],
  ["Rugby", "Meta"],
  ["Golf", "Erba"],
  ["Scherma", "Stoccata"],
  ["Judo", "Cintura"],
  ["Pallanuoto", "Calottina"],
  ["Ginnastica Artistica", "Polvere"],
  ["Surf", "Onda"],
  ["Baseball", "Guantone"],
  ["Moto GP", "Cordolo"],
  ["Maratona", "Traguardo"],
  ["Sollevamento Pesi", "Magnesia"],
  ["Canottaggio", "Remo"],
  ["Tiro con l'arco", "Faretra"],
  ["Equitazione", "Ostacolo"],
  ["Vela", "Vento"],
  ["Pattinaggio sul ghiaccio", "Lama"],
  ["Karate", "Grido"],
  ["Taekwondo", "Calcio"],
  ["Triathlon", "Transizione"],
  ["Badminton", "Volano"],
  ["Ping Pong", "Gomma"],
  ["Pallamano", "Colla"],
  ["Football Americano", "Casco"],
  ["Hockey su ghiaccio", "Disco"],
  ["Cricket", "Mazza"],
  ["Arrampicata", "Imbrago"],
  ["Skateboard", "Rampa"],
  ["Parkour", "Muro"],
  ["Yoga", "Tappetino"],
  ["Pilates", "Riformatore"],
  ["CrossFit", "Box"],
  ["Bodybuilding", "Specchio"],
  ["Kickboxing", "Parastinchi"],
  ["Muay Thai", "Gomito"],
  ["MMA", "Gabbia"],
  ["Lotta Greca", "Tuta"],
  ["Scherma Storica", "Acciaio"],
  ["Tiro a volo", "Piattello"],
  ["Tiro a segno", "Mirino"],
  ["Pentathlon", "Cavallo"],
  ["Decathlon", "Fatica"],
  ["Lancio del disco", "Pedana"],
  ["Lancio del giavellotto", "Punta"],
  ["Getto del peso", "Collo"],
  ["Salto in alto", "Asta"],
  ["Salto in lungo", "Sabbia"],
  ["Salto triplo", "Balzo"],
  ["Salto con l'asta", "Materasso"],
  ["100 metri", "Blocchi"],
  ["110 ostacoli", "Barriera"],
  ["Marcia", "Anca"],
  ["Staffetta 4x100", "Testimone"],
  ["Fondo", "Ritmo"],
  ["Mezzofondo", "Campana"],
  ["Cross Country", "Fango"],
  ["Trail Running", "Radici"],
  ["Ultramaratona", "Notte"],
  ["Nuoto sincronizzato", "Nasello"],
  ["Tuffi", "Trampolino"],
  ["Nuoto di fondo", "Boa"],
  ["Pallanuoto", "Boa"],
  ["Ginnastica Ritmica", "Nastro"],
  ["Trampolino elastico", "Molla"],
  ["Ciclismo su pista", "Parquet"],
  ["BMX", "Gobba"],
  ["Mountain Bike", "Sentiero"],
  ["Ciclocross", "Spalla"],
  ["Motocross", "Salto"],
  ["Rally", "Navigatore"],
  ["Endurance", "Notte"],
  ["Karting", "Sedile"],
  ["Drag Racing", "Paracadute"],
  ["Monster Truck", "Ruota"],
  ["Trial", "Equilibrio"],
  ["Speedway", "Traverso"],
  ["Bob", "Spinta"],
  ["Slittino", "Ghiaccio"],
  ["Skeleton", "Pancia"],
  ["Sci di fondo", "Binario"],
  ["Biathlon", "Carabina"],
  ["Salto con gli sci", "Volo"],
  ["Combinata nordica", "Sciolina"],
  ["Curling", "Scopa"],
  ["Sci alpino", "Porta"],
  ["Discesa libera", "Velocità"],
  ["Slalom speciale", "Palo"],
  ["Snowboard", "Attacchi"],
  ["Freestyle", "Acrobazia"],
  ["Short Track", "Sorpasso"],
  ["Pattinaggio di velocità", "Pista"],
  ["Pattinaggio a rotelle", "Asfalto"],
  ["Hockey su pista", "Rotelle"],
  ["Polo", "Mazza"],
  ["Beach Volley", "Sabbia"],
  ["Footvolley", "Spalla"],
  ["Padel", "Vetro"],
  ["Squash", "Parete"],
  ["Racquetball", "Rimbalzo"],
  ["Lacrosse", "Rete"],
  ["Softbol", "Palla"],
  ["Hurling", "Legno"],
  ["Sumo", "Cerchio"],
  ["Kendo", "Bamboo"],
  ["Aikido", "Energia"],
  ["Capoeira", "Musica"],
  ["Wrestling", "Maschera"],
  ["Lucha Libre", "Volo"],
  ["Dardo", "Freccetta"],
  ["Biliardo", "Stecca"],
  ["Bowling", "Birillo"],
  ["Bocce", "Pallino"],
  ["Scacchi", "Orologio"],
  ["Bridge", "Carte"],
  ["Poker", "Fish"],
  ["E-sports", "Mouse"],
  ["Droni", "Visore"],
  ["Volo a vela", "Termica"],
  ["Paracadutismo", "Quota"],
  ["Parapendio", "Vela"],
  ["Deltaplano", "Ala"],
  ["Bungee Jumping", "Elastico"],
  ["Rafting", "Gommone"],
  ["Canyoning", "Corda"],
  ["Speleologia", "Casco"],
  ["Alpinismo", "Piccozza"],
  ["Sci alpinismo", "Pelli"],
  ["Ciaspole", "Galleggiamento"],
  ["Orienteering", "Bussola"],
  ["Nordic Walking", "Bacchette"],
  ["Pesca sportiva", "Amo"],
  ["Tiro con la fionda", "Sasso"],
  ["Braccio di ferro", "Gomito"],
  ["Tamburello", "Cerchio"],
  ["Palla pugno", "Pugno"],
  ["Palla eh!", "Mano"],
  ["Calcio balilla", "Aste"],
  ["Air Hockey", "Disco"],
  ["Freccette", "Centro"],
  ["Paintball", "Macchia"],
  ["Softair", "Pallino"],
  ["Laser Tag", "Sensore"],
  ["Quidditch", "Scopa"],
  ["Ultimate Frisbee", "Disco"],
  ["Footgolf", "Buca"],
  ["Disc Golf", "Cesto"],
  ["Dodgeball", "Palla"],
  ["Sepak Takraw", "Rete"],
  ["Kabaddi", "Respiro"],
  ["Pelota Basca", "Muro"],
  ["Jai Alai", "Cesta"],
  ["Canicross", "Cane"],
  ["Agility Dog", "Ostacoli"],
  ["Sleddog", "Muta"],
  ["Rodeo", "Toro"],
  ["Bull Riding", "Corna"],
  ["Polo su cammello", "Deserto"],
  ["Corsa dei cammelli", "Sabbia"],
  ["Corsa dei cani", "Levriero"],
  ["Corsa dei cavalli", "Frustino"],
  ["Trotto", "Calesse"],
  ["Galoppo", "Sella"],
  ["Dressage", "Eleganza"],
  ["Volteggio", "Cavallo"],
  ["Concorso completo", "Campagna"],
  ["Modern Pentathlon", "Spada"],
  ["Biathlon estivo", "Skiroll"],
  ["Aquathlon", "Scarpe"],
  ["Duathlon", "Bici"],
  ["Swimrun", "Galleggianti"],
  ["Powerlifting", "Cintura"],
  ["Strongman", "Pietra"],
  ["Calisthenics", "Sbarra"],
  ["Pole Dance", "Palo"],
  ["Cheerleading", "Pon-pon"],
  ["Twirling", "Bastone"],
  ["Danza Sportiva", "Scarpe"],
  ["Breakdance", "Pavimento"],
  ["Pattinaggio artistico", "Musica"],
  ["Hockey in-line", "Ruote"],
  ["Floorball", "Pallina"],
  ["Roller Derby", "Contatto"],
  ["Street Hockey", "Cemento"],
  ["Netball", "Canestro"],
  ["Korfball", "Palo"],
  ["Tchoukball", "Pannello"],
  ["Fistball", "Pugno"],
  ["Sepak Takraw", "Piedi"],
  ["Tamburello", "Palla"],
  ["Bocce", "Boccia"],
  ["Palla a sfratto", "Cortile"],
  ["Palla prigioniera", "Campo"]
];
