export const STORIA: [string, string][] = [
  ["Colosseo", "Arena antica"],
  ["Impero Romano", "Aquile antiche"],
  ["Medioevo", "Castelli"],
  ["Rinascimento", "Botteghe artistiche"],
  ["Peste", "Untori"],
  ["Cristoforo Colombo", "Traversata oceanica"],
  ["Rivoluzione Francese", "Ghigliottina"],
  ["Napoleone", "Bicorno"],
  ["Risorgimento", "Unità italiana"],
  ["Prima Guerra Mondiale", "Trincee"],
  ["Seconda Guerra Mondiale", "Bombardamenti"],
  ["Resistenza", "Montagne partigiane"],
  ["Muro di Berlino", "Città divisa"],
  ["Guerra Fredda", "Tensione senza spari"],
  ["Sbarco sulla Luna", "Passo storico"],
  ["Faraone", "Sarcofago"],
  ["Piramidi", "Blocchi antichi"],
  ["Cavalieri", "Armature"],
  ["Papiro", "Scrittura antica"],
  ["Archeologo", "Pennello e polvere"],
];
