export const STORIA: [string, string][] = [
  ["Colosseo", "Antichità"],
  ["Impero Romano", "Antichità"],
  ["Medioevo", "Epoca"],
  ["Rinascimento", "Epoca"],
  ["Peste", "Disgrazia"],
  ["Cristoforo Colombo", "Personaggio"],
  ["Rivoluzione Francese", "Svolta"],
  ["Napoleone", "Personaggio"],
  ["Risorgimento", "Italia"],
  ["Prima Guerra Mondiale", "Guerra"],
  ["Seconda Guerra Mondiale", "Guerra"],
  ["Resistenza", "Italia"],
  ["Muro di Berlino", "Novecento"],
  ["Guerra Fredda", "Novecento"],
  ["Sbarco sulla Luna", "Impresa"],
  ["Faraone", "Antichità"],
  ["Piramidi", "Antichità"],
  ["Cavalieri", "Epoca"],
  ["Papiro", "Antichità"],
  ["Archeologo", "Mestiere"],
];
