export const STORIA: [string, string][] = [
  ["Giulio Cesare", "Marzo"],
  ["Napoleone", "Cappello"],
  ["Cleopatra", "Nilo"],
  ["Colombo", "Bussola"],
  ["Alessandro Magno", "Cavallo"],
  ["Carlo Magno", "Corona"],
  ["Marco Polo", "Seta"],
  ["Galileo Galilei", "Lente"],
  ["Leonardo da Vinci", "Bottega"],
  ["Michelangelo", "Marmo"],
  ["Nerone", "Fiamma"],
  ["Costantino", "Croce"],
  ["Attila", "Pianura"],
  ["Federico Barbarossa", "Legnano"],
  ["Machiavelli", "Inchiostro"],
  ["Cristoforo Colombo", "Vela"],
  ["Vasco da Gama", "Speziale"],
  ["Magellano", "Stretto"],
  ["Elisabetta I", "Trono"],
  ["Enrico VIII", "Banchetto"],
  ["Luigi XIV", "Specchio"],
  ["Maria Antonietta", "Dolce"],
  ["Robespierre", "Ghigliottina"],
  ["Bonaparte", "Esilio"],
  ["Garibaldi", "Camicia"],
  ["Cavour", "Diplomazia"],
  ["Mazzini", "Lettera"],
  ["Vittorio Emanuele", "Statuto"],
  ["Bismarck", "Ferro"],
  ["Lenin", "Slogan"],
  ["Stalin", "Baffi"],
  ["Hitler", "Cartello"],
  ["Churchill", "Sigaro"],
  ["Roosevelt", "Sedia"],
  ["Gandhi", "Filo"],
  ["Mandela", "Cella"],
  ["Martin Luther King", "Sogno"],
  ["Kennedy", "Corteo"],
  ["Che Guevara", "Berretto"],
  ["Impero Romano", "Legione"],
  ["Impero Bizantino", "Mosaico"],
  ["Impero Ottomano", "Tappeto"],
  ["Sacro Romano Impero", "Aquila"],
  ["Rivoluzione Francese", "Piazza"],
  ["Rivoluzione Industriale", "Fumo"],
  ["Rivoluzione Russa", "Bandiera"],
  ["Prima Guerra Mondiale", "Trincea"],
  ["Seconda Guerra Mondiale", "Rifugio"],
  ["Guerra Fredda", "Muro"],
  ["Guerra dei Cent'anni", "Freccia"],
  ["Guerra del Vietnam", "Giungla"],
  ["Caduta di Roma", "Rovina"],
  ["Rinascimento", "Bottega"],
  ["Illuminismo", "Candela"],
  ["Medioevo", "Castello"],
  ["Preistoria", "Grotta"],
  ["Età del Bronzo", "Fonderia"],
  ["Età della Pietra", "Selce"],
  ["Colonizzazione", "Nave"],
  ["Schiavismo", "Catena"],
  ["Abolizione della schiavitù", "Firma"],
  ["Scoperta dell'America", "Orizzonte"],
  ["Fondazione di Roma", "Lupa"],
  ["Caduta del Muro di Berlino", "Martello"],
  ["Sbarco sulla Luna", "Bandiera"],
  ["Peste Nera", "Maschera"],
  ["Grande Depressione", "Coda"],
  ["Rivoluzione Americana", "Tè"],
  ["Dichiarazione d'Indipendenza", "Penna"],
  ["Costituzione", "Firma"],
  ["Monarchia", "Scettro"],
  ["Repubblica", "Voto"],
  ["Dittatura", "Silenzio"],
  ["Democrazia ateniese", "Assemblea"],
  ["Senato Romano", "Toga"],
  ["Piramidi", "Deserto"],
  ["Sfinge", "Enigma"],
  ["Faraone", "Sabbia"],
  ["Antico Egitto", "Papiro"],
  ["Mesopotamia", "Argilla"],
  ["Babilonia", "Giardino"],
  ["Antica Grecia", "Olivo"],
  ["Sparta", "Scudo"],
  ["Atene", "Colonna"],
  ["Troia", "Cavallo"],
  ["Guerra di Troia", "Freccia"],
  ["Odissea", "Naufragio"],
  ["Iliade", "Eroe"],
  ["Olimpiadi antiche", "Alloro"],
  ["Colosseo", "Arena"],
  ["Pantheon", "Cupola"],
  ["Foro Romano", "Rovina"],
  ["Pompei", "Cenere"],
  ["Vesuvio", "Lava"],
  ["Etruschi", "Tomba"],
  ["Fenici", "Porpora"],
  ["Vichinghi", "Remo"],
  ["Normanni", "Elmo"],
  ["Cavalieri Templari", "Mantello"],
  ["Crociate", "Pellegrinaggio"],
  ["Inquisizione", "Ombra"],
  ["Torquemada", "Rogo"],
  ["Giordano Bruno", "Fiamma"],
  ["Riforma Protestante", "Chiodo"],
  ["Martin Lutero", "Porta"],
  ["Controriforma", "Concilio"],
  ["Concilio di Trento", "Aula"],
  ["Papato", "Anello"],
  ["Stato Pontificio", "Confine"],
  ["Guerra dei Trent'anni", "Trattato"],
  ["Pace di Westfalia", "Firma"],
  ["Assolutismo", "Palazzo"],
  ["Versailles", "Giardino"],
  ["Rivolta di Spartaco", "Catena"],
  ["Gladiatori", "Sabbia"],
  ["Circo Massimo", "Corsa"],
  ["Giulio II", "Cantiere"],
  ["Borgia", "Veleno"],
  ["Medici", "Banca"],
  ["Firenze rinascimentale", "Cupola"],
  ["Botticelli", "Pennello"],
  ["Raffaello", "Stanza"],
  ["Dante Alighieri", "Selva"],
  ["Petrarca", "Sonetto"],
  ["Boccaccio", "Novella"],
  ["Stampa a caratteri mobili", "Piombo"],
  ["Gutenberg", "Torchio"],
  ["Isaac Newton", "Mela"],
  ["Charles Darwin", "Isola"],
  ["Albert Einstein", "Lavagna"],
  ["Nikola Tesla", "Scintilla"],
  ["Thomas Edison", "Filamento"],
  ["Alexander Graham Bell", "Cavo"],
  ["Fratelli Wright", "Sabbia"],
  ["Guglielmo Marconi", "Antenna"],
  ["Invenzione della ruota", "Terracotta"],
  ["Invenzione della scrittura", "Segno"],
  ["Invenzione dell'elettricità", "Scossa"],
  ["Rivoluzione digitale", "Chip"],
  ["Rivoluzione agricola", "Aratro"],
  ["Prima automobile", "Manovella"],
  ["Primo treno", "Fischio"],
  ["Primo aereo", "Pista"],
  ["Titanic", "Ghiaccio"],
  ["Grande incendio di Roma", "Cenere"],
  ["Grande incendio di Londra", "Fumo"],
  ["Terremoto di Lisbona", "Onda"],
  ["Peste di Milano", "Untore"],
  ["Spagnola", "Mascherina"],
  ["Olocausto", "Silenzio"],
  ["Muro di Berlino", "Filo"],
  ["Cortina di Ferro", "Confine"],
  ["Piano Marshall", "Assegno"],
  ["ONU", "Bandiera"],
  ["Unione Europea", "Stella"],
  ["Trattato di Roma", "Firma"],
  ["Nazismo", "Cartello"],
  ["Fascismo", "Manganello"],
  ["Comunismo", "Falce"],
  ["Capitalismo", "Borsa"],
  ["Feudalesimo", "Contratto"],
  ["Servi della gleba", "Zappa"],
  ["Signoria", "Torre"],
  ["Comune medievale", "Piazza"],
  ["Repubbliche marinare", "Molo"],
  ["Venezia storica", "Canale"],
  ["Genova storica", "Porto"],
  ["Unità d'Italia", "Tricolore"],
  ["Risorgimento", "Fiaccola"],
  ["Spedizione dei Mille", "Camicia"],
  ["Presa della Bastiglia", "Chiave"],
  ["Marcia su Roma", "Stivale"],
  ["Resistenza italiana", "Bosco"],
  ["Liberazione", "Campana"],
  ["25 aprile", "Fiore"],
  ["Costituente", "Penna"],
  ["Referendum del 1946", "Urna"],
  ["Guerra civile spagnola", "Poster"],
  ["Franco", "Balcone"],
  ["Mussolini", "Discorso"],
  ["Hiroshima", "Ombra"],
  ["Nagasaki", "Nube"],
  ["Bomba atomica", "Contatore"],
  ["Manhattan Project", "Segreto"],
  ["Yalta", "Tavolo"],
  ["Norimberga", "Banco"],
  ["Piano quinquennale", "Grafico"],
  ["Rivoluzione culturale cinese", "Manifesto"],
  ["Mao Zedong", "Libretto"],
  ["Muraglia Cinese", "Passo"],
  ["Dinastia Ming", "Vaso"],
  ["Samurai", "Katana"],
  ["Shogun", "Blasone"],
  ["Impero Inca", "Terrazza"],
  ["Impero Azteco", "Piuma"],
  ["Impero Maya", "Calendario"],
  ["Conquistadores", "Elmo"],
  ["Cortés", "Nave"],
  ["Pizarro", "Miniera"],
  ["Rivoluzione messicana", "Sombrero"],
  ["Guerra d'indipendenza americana", "Tamburo"],
  ["Guerra di secessione americana", "Bandiera"],
  ["Abraham Lincoln", "Barba"],
  ["Emancipazione", "Catena"],
  ["Segregazione razziale", "Panchina"],
  ["Rosa Parks", "Autobus"],
  ["Marcia su Washington", "Folla"],
  ["Apartheid", "Cancello"],
  ["Nelson Mandela", "Isola"],
  ["Guerra dei Boeri", "Savana"],
  ["Colonialismo", "Mappa"],
  ["Decolonizzazione", "Confine"],
  ["Guerra d'indipendenza indiana", "Sale"],
  ["Impero Britannico", "Tè"],
  ["Rivoluzione Cubana", "Sigaro"],
  ["Fidel Castro", "Barba"],
  ["Crisi dei missili di Cuba", "Radio"],
  ["Sputnik", "Segnale"],
  ["Corsa allo spazio", "Razzo"],
  ["Neil Armstrong", "Passo"],
  ["Guerra di Corea", "Confine"],
  ["Guerra del Golfo", "Sabbia"],
  ["Torri Gemelle", "Cielo"],
];
