export const TECNOLOGIA: [string, string][] = [
  ["Smartphone", "Tasca"],
  ["Tablet", "Leggerezza"],
  ["Laptop", "Zaino"],
  ["Computer", "Scrivania"],
  ["Monitor", "Riflesso"],
  ["Tastiera", "Clic"],
  ["Mouse", "Rotellina"],
  ["Stampante", "Inchiostro"],
  ["Router", "Angolo"],
  ["Modem", "Lucina"],
  ["Wi-Fi", "Angolo"],
  ["Bluetooth", "Vicinanza"],
  ["Internet", "Infinito"],
  ["Browser", "Scheda"],
  ["Motore di ricerca", "Suggerimento"],
  ["Google", "Doodle"],
  ["YouTube", "Pollice"],
  ["Facebook", "Notifica"],
  ["Instagram", "Filtro"],
  ["TikTok", "Trend"],
  ["Twitter", "Cinguettio"],
  ["WhatsApp", "Spunta"],
  ["Telegram", "Velocità"],
  ["Snapchat", "Fantasma"],
  ["LinkedIn", "Curriculum"],
  ["Pinterest", "Bacheca"],
  ["Reddit", "Upvote"],
  ["Discord", "Server"],
  ["Zoom", "Sfondo"],
  ["Skype", "Eco"],
  ["Netflix", "Poltrona"],
  ["Spotify", "Cuffie"],
  ["Amazon", "Pacco"],
  ["eBay", "Asta"],
  ["Apple", "Mela"],
  ["Microsoft", "Finestra"],
  ["Windows", "Avvio"],
  ["MacOS", "Eleganza"],
  ["Linux", "Pinguino"],
  ["Android", "Robottino"],
  ["iOS", "Semplicità"],
  ["Chrome", "Colori"],
  ["Firefox", "Volpe"],
  ["Safari", "Bussola"],
  ["Cloud", "Nuvola"],
  ["Server", "Sala"],
  ["Database", "Archivio"],
  ["Algoritmo", "Ricetta"],
  ["Codice", "Righe"],
  ["Programmazione", "Pazienza"],
  ["App", "Icona"],
  ["Software", "Aggiornamento"],
  ["Hardware", "Componente"],
  ["Chip", "Piccolezza"],
  ["Processore", "Calore"],
  ["Scheda madre", "Verde"],
  ["RAM", "Velocità"],
  ["Hard disk", "Rumore"],
  ["SSD", "Silenzio"],
  ["USB", "Formato"],
  ["Cavo", "Groviglio"],
  ["Batteria", "Ansia"],
  ["Caricabatterie", "Ricerca"],
  ["Powerbank", "Emergenza"],
  ["Schermo", "Impronta"],
  ["Touchscreen", "Ditata"],
  ["Webcam", "Sguardo"],
  ["Microfono", "Voce"],
  ["Altoparlante", "Volume"],
  ["Cuffie", "Isolamento"],
  ["Auricolari", "Perdita"],
  ["Smartwatch", "Polso"],
  ["Fitness tracker", "Passi"],
  ["Drone", "Vista"],
  ["Robot", "Movimento"],
  ["Intelligenza artificiale", "Domanda"],
  ["Machine learning", "Apprendimento"],
  ["ChatGPT", "Conversazione"],
  ["Chatbot", "Attesa"],
  ["Rete neurale", "Complessità"],
  ["Realtà virtuale", "Visore"],
  ["Realtà aumentata", "Sovrapposizione"],
  ["Metaverso", "Avatar"],
  ["Blockchain", "Catena"],
  ["Bitcoin", "Volatilità"],
  ["Criptovaluta", "Portafoglio"],
  ["NFT", "Unicità"],
  ["Token", "Scambio"],
  ["Hacker", "Cappuccio"],
  ["Cybersicurezza", "Allarme"],
  ["Password", "Dimenticanza"],
  ["Firewall", "Barriera"],
  ["Antivirus", "Scansione"],
  ["Malware", "Sospetto"],
  ["Virus informatico", "Contagio"],
  ["Phishing", "Esca"],
  ["Spam", "Fastidio"],
  ["Cookie", "Tracciamento"],
  ["Privacy", "Riserva"],
  ["Dati", "Quantità"],
  ["Big data", "Mole"],
  ["Streaming", "Buffer"],
  ["Podcast", "Ascolto"],
  ["Video", "Riproduzione"],
  ["Live", "Diretta"],
  ["Selfie", "Braccio"],
  ["Filtro", "Trasformazione"],
  ["Hashtag", "Cancelletto"],
  ["Meme", "Risata"],
  ["Viral", "Diffusione"],
  ["Follower", "Numero"],
  ["Like", "Pollice"],
  ["Commento", "Reazione"],
  ["Story", "Effimero"],
  ["Reel", "Brevità"],
  ["Feed", "Scorrimento"],
  ["Notifica", "Vibrazione"],
  ["Aggiornamento", "Attesa"],
  ["Bug", "Fastidio"],
  ["Crash", "Sorpresa"],
  ["Reset", "Ripartenza"],
  ["Backup", "Sicurezza"],
  ["File", "Nome"],
  ["Cartella", "Ordine"],
  ["Email", "Casella"],
  ["Allegato", "Peso"],
  ["Spam email", "Cestino"],
  ["Newsletter", "Frequenza"],
  ["QR code", "Quadrato"],
  ["Codice a barre", "Riga"],
  ["NFC", "Vicinanza"],
  ["Pagamento digitale", "Rapidità"],
  ["Carta di credito virtuale", "Numero"],
  ["Portafoglio digitale", "App"],
  ["Home banking", "Comodità"],
  ["E-commerce", "Carrello"],
  ["Marketplace", "Varietà"],
  ["Dropshipping", "Magazzino"],
  ["Startup", "Idea"],
  ["Venture capital", "Rischio"],
  ["Unicorno", "Valore"],
  ["Silicon Valley", "Ambizione"],
  ["Coworking", "Condivisione"],
  ["Smartworking", "Pigiama"],
  ["Videochiamata", "Sfondo sfocato"],
  ["Slide", "Proiezione"],
  ["Presentazione", "Nervosismo"],
  ["Tastiera meccanica", "Clic"],
  ["Gaming", "Notte"],
  ["Console", "Salotto"],
  ["PlayStation", "Controller"],
  ["Xbox", "Croce"],
  ["Nintendo", "Nostalgia"],
  ["Joystick", "Levetta"],
  ["Realtà mista", "Confine"],
  ["Streamer", "Diretta"],
  ["Twitch", "Chat"],
  ["Esports", "Competizione"],
  ["Avatar", "Rappresentazione"],
  ["Skin", "Estetica"],
  ["Loot box", "Sorpresa"],
  ["Server dedicato", "Stabilità"],
  ["Lag", "Frustrazione"],
  ["Ping", "Millisecondi"],
  ["Fibra ottica", "Velocità"],
  ["5G", "Antenna"],
  ["4G", "Copertina"],
  ["SIM", "Piccolezza"],
  ["Roaming", "Frontiera"],
  ["Operatore telefonico", "Fattura"],
  ["Segnale", "Tacca"],
  ["Antenna", "Altezza"],
  ["Satellite", "Orbita"],
  ["GPS", "Puntino"],
  ["Navigatore", "Voce"],
  ["Mappa digitale", "Zoom"],
  ["Realtà ibrida", "Fusione"],
  ["Stampante 3D", "Strato"],
  ["Scanner", "Luce"],
  ["Fotocamera digitale", "Otturatore"],
  ["Obiettivo", "Sfocatura"],
  ["Editing", "Ritocco"],
  ["Photoshop", "Livello"],
  ["Rendering", "Attesa"],
  ["Pixel", "Griglia"],
  ["Risoluzione", "Nitidezza"],
  ["HD", "Chiarezza"],
  ["4K", "Dettaglio"],
  ["Frame rate", "Fluidità"],
  ["Codec", "Compressione"],
  ["MP3", "Formato"],
  ["Playlist", "Ordine"],
  ["Equalizzatore", "Curva"],
  ["Assistente vocale", "Ascolto"],
  ["Alexa", "Casa"],
  ["Siri", "Domanda"],
  ["Google Assistant", "Comando"],
  ["Domotica", "Automazione"],
  ["Casa intelligente", "Luce"],
  ["Termostato smart", "Temperatura"],
  ["Sensore", "Rilevamento"],
  ["Telecamera di sicurezza", "Occhio"],
  ["Videocitofono", "Suono"],
  ["Serratura smart", "Chiave"],
  ["Aspirapolvere robot", "Percorso"],
  ["Frigorifero smart", "Inventario"],
  ["Lampadina smart", "Colore"],
  ["Presa smart", "Interruttore"],
  ["Realtà digitale", "Confine"],
  ["Cloud gaming", "Streaming"],
  ["API", "Ponte"],
  ["Open source", "Comunità"],
  ["Licenza software", "Contratto"],
  ["Freeware", "Gratuità"],
  ["Beta test", "Anticipo"],
  ["Patch", "Toppa"],
  ["Versione", "Numero"],
  ["Interfaccia", "Aspetto"],
  ["UX", "Esperienza"],
  ["UI", "Estetica"],
  ["Wireframe", "Bozza"],
  ["Prototipo", "Prova"],
  ["Sviluppatore", "Notte"],
  ["Programmatore", "Tastiera"],
  ["Debug", "Caccia"],
  ["Terminale", "Comando"],
  ["Script", "Automazione"],
  ["Framework", "Struttura"],
  ["Libreria di codice", "Riutilizzo"],
  ["Git", "Versione"],
  ["GitHub", "Deposito"],
  ["Repository", "Archivio"],
  ["Compilatore", "Traduzione"],
  ["Sintassi", "Regola"],
  ["Variabile", "Contenitore"],
  ["Funzione", "Compito"],
];
