export const TECNOLOGIA: [string, string][] = [
  ["Wi-Fi", "Connessione"],
  ["Password", "Sicurezza"],
  ["Batteria", "Energia"],
  ["Aggiornamento", "Fastidio"],
  ["Cavo", "Oggetto"],
  ["Schermo rotto", "Danno"],
  ["Cloud", "Dati"],
  ["Intelligenza artificiale", "Novità"],
  ["Robot", "Macchina"],
  ["Drone", "Macchina"],
  ["Stampante", "Ufficio"],
  ["Videochiamata", "Contatto"],
  ["Notifica", "Telefono"],
  ["Backup", "Sicurezza"],
  ["Virus", "Minaccia"],
  ["Tastiera", "Oggetto"],
  ["Mouse", "Oggetto"],
  ["Auricolari", "Ascolto"],
  ["Caricabatterie", "Energia"],
  ["Spam", "Fastidio"],
];
