export const TECNOLOGIA: [string, string][] = [
  ["Wi-Fi", "Barrette"],
  ["Password", "Dimenticata"],
  ["Batteria", "Ansia rossa"],
  ["Aggiornamento", "Momento sbagliato"],
  ["Cavo", "Nodo"],
  ["Schermo rotto", "Ragnatela"],
  ["Cloud", "Altrove"],
  ["Intelligenza artificiale", "Risposte istantanee"],
  ["Robot", "Braccio metallico"],
  ["Drone", "Ronzio alto"],
  ["Stampante", "Nemica domestica"],
  ["Videochiamata", "Microfono muto"],
  ["Notifica", "Vibrazione"],
  ["Backup", "Rimpianto evitato"],
  ["Virus", "Contagio digitale"],
  ["Tastiera", "Tasti consumati"],
  ["Mouse", "Coda"],
  ["Auricolari", "Uno perso"],
  ["Caricabatterie", "Prestito mai restituito"],
  ["Spam", "Cestino"],
];
