export const VIAGGI: [string, string][] = [
  ["Aeroporto", "Luogo"],
  ["Valigia", "Oggetto"],
  ["Passaporto", "Documento"],
  ["Ostello", "Alloggio"],
  ["Souvenir", "Ricordo"],
  ["Cartolina", "Ricordo"],
  ["Autostrada", "Strada"],
  ["Traghetto", "Mezzo"],
  ["Zaino in spalla", "Stile"],
  ["Guida turistica", "Persona"],
  ["Mappa", "Oggetto"],
  ["Crema solare", "Estate"],
  ["Spiaggia", "Estate"],
  ["Montagna", "Natura"],
  ["Campeggio", "Vacanza"],
  ["Jet lag", "Stanchezza"],
  ["Dogana", "Controllo"],
  ["Bagaglio a mano", "Regole"],
  ["Ritardo", "Imprevisto"],
  ["Ritorno", "Fine"],
];
