export const VIAGGI: [string, string][] = [
  ["Aeroporto", "Attesa annunciata"],
  ["Valigia", "Cerniera forzata"],
  ["Passaporto", "Timbri"],
  ["Ostello", "Letti condivisi"],
  ["Souvenir", "Polvere futura"],
  ["Cartolina", "Francobollo"],
  ["Autostrada", "Casello"],
  ["Traghetto", "Ponte ventoso"],
  ["Zaino in spalla", "Pochi soldi"],
  ["Guida turistica", "Ombrellino alzato"],
  ["Mappa", "Pieghe sbagliate"],
  ["Crema solare", "Scottatura evitata"],
  ["Spiaggia", "Sabbia ovunque"],
  ["Montagna", "Rifugio"],
  ["Campeggio", "Tenda"],
  ["Jet lag", "Occhi pesanti"],
  ["Dogana", "Controllo"],
  ["Bagaglio a mano", "Misure"],
  ["Ritardo", "Tabellone"],
  ["Ritorno", "Lavatrice piena"],
];
