export const VIAGGI: [string, string][] = [
  ["Aeroporto", "Attesa"],
  ["Valigia", "Peso"],
  ["Passaporto", "Timbro"],
  ["Fontana di Trevi", "Moneta"],
  ["Torre di Pisa", "Equilibrio"],
  ["Colosseo", "Eco"],
  ["Torre Eiffel", "Altezza"],
  ["Louvre", "Silenzio"],
  ["Big Ben", "Rintocco"],
  ["Piramidi di Giza", "Sabbia"],
  ["Muraglia Cinese", "Lunghezza"],
  ["Statua della Libertà", "Fiaccola"],
  ["Taj Mahal", "Amore"],
  ["Machu Picchu", "Nebbia"],
  ["Cristo Redentore", "Vista"],
  ["Sagrada Familia", "Cantiere"],
  ["Grand Canyon", "Vertigine"],
  ["Niagara Falls", "Rombo"],
  ["Venezia", "Riflesso"],
  ["Firenze", "Rinascita"],
  ["Napoli", "Vulcano"],
  ["Roma", "Storia"],
  ["Milano", "Fretta"],
  ["Parigi", "Romanticismo"],
  ["Londra", "Pioggia"],
  ["Berlino", "Muro"],
  ["Madrid", "Sole"],
  ["Barcellona", "Ritmo"],
  ["Amsterdam", "Canale"],
  ["Vienna", "Valzer"],
  ["Praga", "Mistero"],
  ["Budapest", "Terme"],
  ["Atene", "Filosofia"],
  ["Istanbul", "Confine"],
  ["Mosca", "Freddo"],
  ["San Pietroburgo", "Bianco"],
  ["Dublino", "Verde"],
  ["Lisbona", "Malinconia"],
  ["Zurigo", "Precisione"],
  ["New York", "Grattacielo"],
  ["Los Angeles", "Fama"],
  ["Las Vegas", "Luce"],
  ["San Francisco", "Salita"],
  ["Miami", "Colore"],
  ["Chicago", "Vento"],
  ["Toronto", "Ordine"],
  ["Tokyo", "Velocità"],
  ["Kyoto", "Quiete"],
  ["Pechino", "Antichità"],
  ["Shanghai", "Neon"],
  ["Seoul", "Karaoke"],
  ["Bangkok", "Spezia"],
  ["Singapore", "Pulizia"],
  ["Hong Kong", "Skyline"],
  ["Sydney", "Onda"],
  ["Melbourne", "Caffè"],
  ["Auckland", "Isolamento"],
  ["Rio de Janeiro", "Samba"],
  ["Buenos Aires", "Tango"],
  ["Città del Messico", "Altitudine"],
  ["Cancun", "Turchese"],
  ["L'Avana", "Nostalgia"],
  ["Il Cairo", "Polvere"],
  ["Marrakech", "Labirinto"],
  ["Città del Capo", "Contrasto"],
  ["Nairobi", "Savana"],
  ["Zanzibar", "Spiaggia"],
  ["Dubai", "Lusso"],
  ["Doha", "Miraggio"],
  ["Gerusalemme", "Devozione"],
  ["Petra", "Roccia"],
  ["Bali", "Incenso"],
  ["Maldive", "Trasparenza"],
  ["Seychelles", "Palma"],
  ["Santorini", "Tramonto"],
  ["Mykonos", "Vento"],
  ["Capri", "Grotta"],
  ["Sicilia", "Agrume"],
  ["Sardegna", "Granito"],
  ["Costiera Amalfitana", "Curva"],
  ["Cinque Terre", "Colore"],
  ["Dolomiti", "Cima"],
  ["Alpi", "Ghiaccio"],
  ["Lago di Como", "Riflesso"],
  ["Lago di Garda", "Brezza"],
  ["Toscana", "Collina"],
  ["Puglia", "Ulivo"],
  ["Umbria", "Silenzio"],
  ["Val d'Aosta", "Neve"],
  ["Isole Canarie", "Vulcano"],
  ["Ibiza", "Musica"],
  ["Costa Azzurra", "Yacht"],
  ["Provenza", "Lavanda"],
  ["Loira", "Castello"],
  ["Baviera", "Birra"],
  ["Foresta Nera", "Ombra"],
  ["Islanda", "Geyser"],
  ["Norvegia", "Fiordo"],
  ["Aurora Boreale", "Danza"],
  ["Lapponia", "Slitta"],
  ["Groenlandia", "Vastità"],
  ["Amazzonia", "Umidità"],
  ["Patagonia", "Solitudine"],
  ["Deserto del Sahara", "Orizzonte"],
  ["Deserto di Gobi", "Vento"],
  ["Everest", "Sfida"],
  ["Kilimangiaro", "Ascesa"],
  ["Ande", "Altitudine"],
  ["Alpi Svizzere", "Cartolina"],
  ["Yellowstone", "Geiser"],
  ["Route 66", "Nostalgia"],
  ["Silk Road", "Carovana"],
  ["Trans-Siberiana", "Lunghezza"],
  ["Crociera", "Dondolio"],
  ["Aereo", "Turbolenza"],
  ["Treno", "Binario"],
  ["Autobus", "Fermata"],
  ["Nave", "Salsedine"],
  ["Traghetto", "Attesa"],
  ["Bicicletta", "Fatica"],
  ["Auto a noleggio", "Libertà"],
  ["Camper", "Avventura"],
  ["Zaino", "Spalla"],
  ["Cartina", "Piega"],
  ["Bussola", "Direzione"],
  ["Guida turistica", "Consiglio"],
  ["Ostello", "Compagnia"],
  ["Hotel a cinque stelle", "Comfort"],
  ["Bed and Breakfast", "Colazione"],
  ["Campeggio", "Tenda"],
  ["Villaggio turistico", "Animazione"],
  ["Souvenir", "Ricordo"],
  ["Cartolina", "Francobollo"],
  ["Fuso orario", "Confusione"],
  ["Jet lag", "Stanchezza"],
  ["Dogana", "Controllo"],
  ["Visto", "Burocrazia"],
  ["Check-in", "Coda"],
  ["Imbarco", "Fretta"],
  ["Bagaglio a mano", "Limite"],
  ["Overbooking", "Fastidio"],
  ["Turista", "Curiosità"],
  ["Local", "Autenticità"],
  ["Escursione", "Fatica"],
  ["Safari", "Emozione"],
  ["Immersione subacquea", "Silenzio"],
  ["Snorkeling", "Trasparenza"],
  ["Trekking", "Sudore"],
  ["Sci", "Discesa"],
  ["Surf", "Equilibrio"],
  ["Vela", "Vento"],
  ["Rafting", "Adrenalina"],
  ["Mongolfiera", "Leggerezza"],
  ["Parapendio", "Coraggio"],
  ["Città fantasma", "Abbandono"],
  ["Borgo medievale", "Pietra"],
  ["Mercatino locale", "Odore"],
  ["Street food", "Sapore"],
  ["Ristorante tipico", "Tradizione"],
  ["Cucina locale", "Scoperta"],
  ["Vino locale", "Degustazione"],
  ["Spiaggia tropicale", "Sabbia"],
  ["Isola deserta", "Solitudine"],
  ["Grotta marina", "Eco"],
  ["Cascata", "Rombo"],
  ["Vulcano attivo", "Tensione"],
  ["Terme naturali", "Vapore"],
  ["Foresta pluviale", "Umidità"],
  ["Savana africana", "Distesa"],
  ["Ghiacciaio", "Scricchiolio"],
  ["Fiordo norvegese", "Quiete"],
  ["Canyon", "Profondità"],
  ["Oasi nel deserto", "Sollievo"],
  ["Barriera corallina", "Colore"],
  ["Vacanza studio", "Disciplina"],
  ["Viaggio di nozze", "Romanticismo"],
  ["Gita scolastica", "Confusione"],
  ["Weekend fuori porta", "Fretta"],
  ["Vacanza last minute", "Sorpresa"],
  ["Tour organizzato", "Orario"],
  ["Viaggio in solitaria", "Riflessione"],
  ["Interrail", "Gioventù"],
  ["Zaino in spalla", "Leggerezza"],
  ["Souvenir kitsch", "Ironia"],
  ["Meta esotica", "Fascino"],
  ["Isola tropicale", "Palma"],
  ["Città d'arte", "Cultura"],
  ["Capitale europea", "Storia"],
  ["Metropoli asiatica", "Frenesia"],
  ["Villaggio di pescatori", "Semplicità"],
  ["Stazione ferroviaria", "Annuncio"],
  ["Porto turistico", "Ormeggio"],
  ["Frontiera", "Attesa"],
  ["Isola greca", "Bianco"],
  ["Regione vinicola", "Profumo"],
  ["Cammino di Santiago", "Fede"],
  ["Via Francigena", "Passo"],
  ["Sentiero di montagna", "Vertigine"],
  ["Rifugio alpino", "Calore"],
  ["Baita", "Legno"],
  ["Pista da sci", "Freddo"],
  ["Resort all inclusive", "Comodità"],
  ["Villaggio vacanze", "Animazione"],
  ["Agriturismo", "Genuinità"],
  ["Cantina vinicola", "Aroma"],
  ["Mercato dei souvenir", "Contrattazione"],
  ["Spiaggia affollata", "Rumore"],
  ["Baia nascosta", "Segreto"],
  ["Faro", "Guida"],
  ["Molo", "Passeggiata"],
  ["Lungomare", "Brezza"],
  ["Piazza principale", "Incontro"],
  ["Vicolo stretto", "Mistero"],
  ["Duomo", "Maestosità"],
  ["Castello medievale", "Leggenda"],
  ["Museo", "Silenzio"],
  ["Galleria d'arte", "Riflessione"],
  ["Parco naturale", "Respiro"],
  ["Riserva marina", "Protezione"],
  ["Isola vulcanica", "Fumo"],
  ["Terrazza panoramica", "Vista"],
  ["Funivia", "Vertigine"],
  ["Trenino turistico", "Lentezza"],
  ["Bicicletta a noleggio", "Libertà"],
  ["Risciò", "Curiosità"],
  ["Tuk tuk", "Caos"],
  ["Taxi locale", "Trattativa"],
  ["Gondola", "Romanticismo"],
  ["Traghetto notturno", "Stanchezza"],
];
