export const VIDEOGIOCHI: [string, string][] = [
  ["Minecraft", "Cubetto"],
  ["Tetris", "Blocchi"],
  ["Pac-Man", "Fantasmi"],
  ["Super Mario", "Baffi"],
  ["Zelda", "Triforza"],
  ["Dark Souls", "Falò"],
  ["Elden Ring", "Anello"],
  ["The Witcher", "Medaglione"],
  ["Fortnite", "Ballo"],
  ["Call of Duty", "Zaino"],
  ["FIFA", "Fischietto"],
  ["GTA", "Sirena"],
  ["Halo", "Anello Verde"],
  ["Portal", "Torta"],
  ["Half-Life", "Piede di Porco"],
  ["Pokémon", "Pallina"],
  ["Sonic", "Anelli"],
  ["Doom", "Motosega"],
  ["Overwatch", "Portale"],
  ["League of Legends", "Nexus"],
  ["Dota", "Corriere"],
  ["World of Warcraft", "Portale"],
  ["Skyrim", "Freccia Ginocchio"],
  ["Fallout", "Bottiglia"],
  ["Cyberpunk", "Neon"],
  ["Red Dead Redemption", "Cavallo"],
  ["Assassin's Creed", "Salto"],
  ["God of War", "Barba"],
  ["Uncharted", "Cimelio"],
  ["Last of Us", "Spora"],
  ["Resident Evil", "Erba"],
  ["Silent Hill", "Nebbia"],
  ["Metal Gear Solid", "Scatola"],
  ["Final Fantasy", "Cristallo"],
  ["Kingdom Hearts", "Chiave"],
  ["Street Fighter", "Ken"],
  ["Tekken", "Torneo"],
  ["Mortal Kombat", "Fatality"],
  ["Super Smash Bros", "Trofeo"],
  ["Animal Crossing", "Debito"],
  ["Stardew Valley", "Zucca"],
  ["Terraria", "Piccone"],
  ["Among Us", "Sospetto"],
  ["Roblox", "Robux"],
  ["Candy Crush", "Zucchero"],
  ["Angry Birds", "Fionda"],
  ["Flappy Bird", "Tubi"],
  ["Subway Surfers", "Skateboard"],
  ["Clash of Clans", "Baule"],
  ["Clash Royale", "Torre"],
  ["Genshin Impact", "Aquilone"],
  ["Valorant", "Spike"],
  ["Apex Legends", "Paracadute"],
  ["Rainbow Six", "Trappola"],
  ["Battlefield", "Trincea"],
  ["PUBG", "Isola"],
  ["Cuphead", "Guanto"],
  ["Hollow Knight", "Charm"],
  ["Celeste", "Fragola"],
  ["Ori", "Spirito"],
  ["Undertale", "Anima"],
  ["Stray", "Zampe"],
  ["It Takes Two", "Coppia"],
  ["Journey", "Sciarpa"],
  ["Limbo", "Ombra"],
  ["Inside", "Silenzio"],
  ["Little Nightmares", "Bambola"],
  ["Bloodborne", "Sangue"],
  ["Sekiro", "Protesi"],
  ["Bayonetta", "Tacchi"],
  ["Devil May Cry", "Cappotto"],
  ["Nier Automata", "Bendaggio"],
  ["Persona", "Maschera"],
  ["Dragon Quest", "Slime"],
  ["Monster Hunter", "Zanna"],
  ["Nintendo Switch", "Joy-Con"],
  ["PlayStation", "Croce"],
  ["Xbox", "Trigger"],
  ["Game Boy", "Cartuccia"],
  ["Sega Genesis", "Console anni 90"],
  ["Arcade", "Gettoni"],
  ["Joystick", "Leva"],
  ["Controller", "Vibrazione"],
  ["Mouse Gaming", "Click"],
  ["Tastiera Meccanica", "Rumore"],
  ["Cuffie Gaming", "Chat"],
  ["Monitor 144Hz", "Fluidità"],
  ["Scheda Video", "Ventole"],
  ["Lag", "Frustrazione"],
  ["Framerate", "Scatti"],
  ["Rispawn", "Attesa"],
  ["Checkpoint", "Salvezza"],
  ["Save Point", "Sollievo"],
  ["Boss Finale", "Sudore"],
  ["Mini Boss", "Ostacolo"],
  ["Tutorial", "Pazienza"],
  ["Livello", "Progresso"],
  ["Achievement", "Trofeo Digitale"],
  ["Trofeo Platino", "Orgoglio"],
  ["Speedrun", "Cronometro"],
  ["Glitch", "Bug"],
  ["Easter Egg", "Sorpresa"],
  ["DLC", "Extra"],
  ["Espansione", "Mappa Nuova"],
  ["Season Pass", "Abbonamento"],
  ["Loot Box", "Scommessa"],
  ["Skin", "Estetica"],
  ["Emote", "Balletto"],
  ["Battle Pass", "Progressione"],
  ["Microtransazione", "Portafoglio"],
  ["Free to Play", "Gratis"],
  ["Pay to Win", "Ingiustizia"],
  ["Grinding", "Ripetizione"],
  ["Farming", "Pazienza"],
  ["Loot", "Bottino"],
  ["Drop Rate", "Fortuna"],
  ["Crafting", "Banco"],
  ["Inventario", "Zaino"],
  ["Equipaggiamento", "Armatura"],
  ["Livello Esperienza", "Numero"],
  ["Punti Vita", "Barra Rossa"],
  ["Mana", "Barra Blu"],
  ["Barra Stamina", "Fiato"],
  ["Combo", "Sequenza"],
  ["Critico", "Fortuna"],
  ["Parry", "Riflesso"],
  ["Dodge Roll", "Schivata"],
  ["Hitbox", "Invisibile"],
  ["Frame Data", "Numeri"],
  ["Nerf", "Depotenziamento"],
  ["Buff", "Potenziamento"],
  ["Patch", "Aggiornamento"],
  ["Server", "Connessione"],
  ["Ping", "Latenza"],
  ["Matchmaking", "Attesa"],
  ["Ranked", "Ansia"],
  ["Elo", "Numero Segreto"],
  ["Leaderboard", "Classifica"],
  ["Clan", "Gruppo"],
  ["Gilda", "Alleanza"],
  ["Guild", "Chat Vocale"],
  ["Streamer", "Webcam"],
  ["Twitch", "Donazione"],
  ["YouTuber Gaming", "Intro"],
  ["E-Sport", "Arena"],
  ["Torneo Online", "Premio"],
  ["Cosplay", "Costume"],
  ["Fan Art", "Disegno"],
  ["Modding", "Cartella"],
  ["Mod", "Personalizzazione, community"],
  ["Retrogaming", "Polvere"],
  ["Emulatore", "Nostalgia"],
  ["Pixel Art", "Quadretti"],
  ["Voxel", "Cubo"],
  ["Open World", "Orizzonte"],
  ["Sandbox", "Libertà"],
  ["Roguelike", "Ricomincia"],
  ["Metroidvania", "Labirinto"],
  ["Platform", "Salto"],
  ["Puzzle Game", "Rompicapo"],
  ["Rhythm Game", "Battito"],
  ["Visual Novel", "Testo"],
  ["Simulatore", "Realismo"],
  ["Gestionale", "Numeri"],
  ["Strategico", "Piano"],
  ["Turni", "Attesa"],
  ["Tempo Reale", "Fretta"],
  ["Tower Defense", "Torretta"],
  ["Shooter", "Mira"],
  ["FPS", "Prima Persona"],
  ["Terza Persona", "Spalle"],
  ["Sparatutto", "Proiettile"],
  ["Corsa", "Motore"],
  ["Racing Game", "Curva"],
  ["Drift", "Fumo Gomme"],
  ["Kart", "Guscio"],
  ["Picchiaduro", "Pugno"],
  ["Beat 'em Up", "Folla"],
  ["Souls-like", "Difficoltà"],
  ["Horror Game", "Buio"],
  ["Jump Scare", "Spavento"],
  ["Survival", "Fame"],
  ["Crafting Survival", "Legna"],
  ["Base Building", "Mattoni"],
  ["City Builder", "Grattacielo"],
  ["Farming Game", "Raccolto"],
  ["Dating Sim", "Cuore"],
  ["Party Game", "Risate"],
  ["Board Game Digitale", "Dado"],
  ["Carte Collezionabili", "Mazzo"],
  ["Deck Building", "Mazzo"],
  ["Hearthstone", "Mana"],
  ["Magic Digitale", "Terra"],
  ["VR", "Visore"],
  ["Realtà Virtuale", "Cinetosi"],
  ["Realtà Aumentata", "Telefono"],
  ["Motion Control", "Braccio"],
  ["Split Screen", "Divano"],
  ["Co-op", "Squadra"],
  ["Multiplayer", "Amici"],
  ["Single Player", "Solitudine"],
  ["Storia", "Cutscene"],
  ["Cutscene", "Popcorn"],
  ["Doppiaggio", "Voce"],
  ["Colonna Sonora", "Orecchie"],
  ["Level Design", "Architettura"],
  ["Game Designer", "Idea"],
  ["Sviluppatore Indie", "Garage"],
  ["Beta Test", "Anteprima"],
  ["Early Access", "Rischio"],
  ["Uscita Ritardata", "Attesa"],
  ["Hype", "Trailer"],
  ["Preordine", "Bonus"],
  ["Edizione Speciale", "Statuetta"],
  ["Steam", "Saldi"],
  ["Epic Games Store", "Gratis Settimanale"],
  ["Console War", "Rivalità"],
  ["Retrocompatibilità", "Vecchio"],
  ["Cloud Gaming", "Nuvola"],
  ["Abbonamento Gaming", "Catalogo"],
  ["Achievement Hunter", "Caccia"],
  ["Platino", "Ultimo Trofeo"],
  ["New Game Plus", "Ricomincio"],
  ["Permadeath", "Definitivo"],
  ["Iron Man Mode", "Coraggio"],
  ["Difficoltà Estrema", "Sudore Freddo"],
];
