export const VIDEOGIOCHI: [string, string][] = [
  ["Minecraft", "Titolo famoso"],
  ["Fortnite", "Titolo famoso"],
  ["Super Mario", "Classico"],
  ["Tetris", "Classico"],
  ["Pac-Man", "Classico"],
  ["Zelda", "Saga"],
  ["FIFA", "Sport"],
  ["Call of Duty", "Online"],
  ["Among Us", "Compagnia"],
  ["Pokémon", "Saga"],
  ["Joystick", "Oggetto"],
  ["Console", "Oggetto"],
  ["Checkpoint", "Meccanica"],
  ["Game over", "Fine"],
  ["Boss finale", "Sfida"],
  ["Livello", "Meccanica"],
  ["Lag", "Problema"],
  ["Speedrun", "Sfida"],
  ["Cheat", "Furbizia"],
  ["Multiplayer", "Compagnia"],
];
