export const VIDEOGIOCHI: [string, string][] = [
  ["Minecraft", "Cubi infiniti"],
  ["Fortnite", "Balletti vittoria"],
  ["Super Mario", "Idraulico saltellante"],
  ["Tetris", "Incastri"],
  ["Pac-Man", "Labirinto goloso"],
  ["Zelda", "Spada leggendaria"],
  ["FIFA", "Partita sul divano"],
  ["Call of Duty", "Cuffie urlanti"],
  ["Among Us", "Sospetti"],
  ["Pokémon", "Collezione tascabile"],
  ["Joystick", "Pollici"],
  ["Console", "Salotto"],
  ["Checkpoint", "Sollievo"],
  ["Game over", "Rabbia"],
  ["Boss finale", "Ultimo ostacolo"],
  ["Livello", "Progressione"],
  ["Lag", "Ritardo maledetto"],
  ["Speedrun", "Cronometro"],
  ["Cheat", "Scorciatoia sleale"],
  ["Multiplayer", "Amici online"],
];
